### ISSUE TITLE
Credentials setup documentation is out-of-date

### ISSUE THREAD

**Issue by willharris** [jenkinsci/ghprb-plugin#108]
It seems in v1.23 the method for defining credentials has changed. Please update the documentation regarding setting up credentials for GitHub access.

**Comment by DavidTanner** [comment]
I will try to get to this today.

**Comment by DavidTanner** [comment]
I am open to changes to how the readme is done if you want to make a pull request, and I also updated the wiki page.

**Comment by willharris** [comment]
Fantastic, thanks a lot for the fast turn-around! I'll take a look and see if I have any ideas for improvement.
