### ISSUE TITLE
How to change the status URL sent to Github?

### ISSUE THREAD

**Issue by jsquyres** [jenkinsci/ghprb-plugin#109]
We have an internal Jenkins running some testing on a Github project's PRs.  There is, unfortunately, no possibility of being able to expose our Jenkins to the outside world.  This is obviously problematic when Jenkins finds a problem -- it can set a "Failed" status on the PR commit, but none of our external collaborators can see the details of the actual problem (since they can't reach our internal Jenkins instance).

To work around that, we came up with the scheme of publishing our build logs to gists (see https://gist.github.com/cisco-usnic-bot).  This allows our external collaborators to see the full build log via gist (since they can't see our Jenkins) -- it's quite useful.

I'd really like to be able to associate the gist URL with the commit status.  Is there a way to do that?

Specifically, I see the Jenkins GHPRB Advanced config field named "Published Jenkins URL", which lets me change the base of the commit status URL that is sent back to Github.  But GHPRB appends the rest of the Jenkins-form URL after that base URL (e.g., `job/JENKINS_JOB_NAME/JOB_ID/`).

Is there a way I can tell GHPRB to wholly replace the status URL with a URL that I provide?  Since we use gists, we need to generate a unique URL during every job run -- i.e.,  we generate the gist URL in the Build/Execute Shell phase of our Jenkins job.

Thanks for any advice you can provide.

**Comment by DavidTanner** [comment]
I think you would want to use the GitHub plugin to do that.  You can also append a portion of the build logs to the comment that gets made when the job fails.
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin
http://stackoverflow.com/questions/14274293/show-current-state-of-jenkins-build-on-github-repo/26910986#26910986

**Comment by DavidTanner** [comment]
It looks like that will just give you the status, not a custom message.
The plugin is set up to use extensions now, so you are welcome to add one that will do just what you want, and add it to the extensions.status package.

**Comment by jsquyres** [comment]
I'm sorry, I don't think I was clear.  I was specifically referring to the "Details" link at the bottom of GH PRs.  That link is being set to the URL of our internal Jenkins server.

Specifically, I'd like to provide a per-job value for the target_url in the JSON that is being sent back by GHPRB to set the commit status (i.e., the gist URL that I generate during my job build steps).

**Comment by DavidTanner** [comment]
I am pretty sure we are on the same page.  The status update is what sets that details link, or the icon to the right of the commit.  Right now it is just set to use the internal url, but an extension would allow that to change to whatever you want.

**Comment by jsquyres** [comment]
Ah, ok.

Any suggestions for how I would do that in an extension?  (forgive me; I'm unfamiliar with the GHPRB extensions...)  Is there a "usual" way for a child process to pass some info back up to Jenkins (other than the exit status of the build script)?

**Comment by DavidTanner** [comment]
Use this file as a starting point.  You just have to handle updating the status when the build is scheduled, starting, and complete.
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.23.2/src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java

**Comment by jsquyres** [comment]
Ok, we'll have a look at that.  Thanks!

**Comment by DavidTanner** [comment]
I think I will just add it to #113 since it hasn't been merged yet.

**Comment by jsquyres** [comment]
Sweet; thank you!

Do you have a guesstimate on when this will be in a published release of GHPRB?

**Comment by DavidTanner** [comment]
The changes landed in build 1.24 and will be in the update center within the next few hours, whenever their process runs next.

**Comment by jsquyres** [comment]
I've updated my Jenkins to use 1.24 of GHPRB and I'm a little confused at to how to do what I want.

Forgive me -- I might have used the wrong terminology to define what I want to do.  I see this screenshot:

![jenkins-ghprb-status-update-1 24](https://cloud.githubusercontent.com/assets/617316/8296743/493c3f5a-1909-11e5-870d-b668f6fe6d5b.png)

I think I said "job" earlier in this issue when I really should have said "build".  I.e., I have build-specific output that I want to include in the details/status link on github (in this case, I dump my build log to a gist that is specific to that build).

**Comment by DavidTanner** [comment]
The "Commit Status URL" will be resolved when the plugin updates the status of a commit.  If you put an environment variable in there then it will be resolved during the build

**Comment by jsquyres** [comment]
How do I set an environment variable from my build steps (potentially executing on a separate slave node) that the GHPRB plugin will see?

**Comment by DavidTanner** [comment]
I recommend using https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin, then you can inject variables at any stage of the build using a properties file, a properties script, a groovy script, or a groovy file.

**Comment by jsquyres** [comment]
Sweet.  Let me go check that out.

(many thanks for your patience and all the help!)

**Comment by hppritcha** [comment]
I'm checking how to use the Commit Status URL box in the GHPRB global configure section.
It doesn't seem to have any impact on the link pointed to by ```details```.  Do I need to supply values for
the other two fields - Commit Status Build Triggered and Commit Status BuildStarted?

**Comment by DavidTanner** [comment]
So it looks like I forgot to add the getter for the field, so the configure page won't show the url you saved.  I just fixed it locally and will release a patch, but the functionality should still work.  

https://github.com/DavidTanner/Testing/pull/12
Currently the last status details is for google.com, which is what I saved in the config.

**Comment by jeevandev** [comment]
@jsquyres I want do the same thing as you have done, pushing our jenkins(behind firewall) console logs to a gist & then publishing it using custom url. I have figured the custom url part but i am not sure how should i push the console logs to gist. It would be great if you can let me know how you did that. Thank you

**Comment by jsquyres** [comment]
@jeevandev We just use a CLI gist uploader -- https://github.com/defunkt/gist.

**Comment by jeevandev** [comment]
@jsquyres perfect thanks, i was trying to do it using groovy & bash
