### ISSUE TITLE
Get the passphrase as a environment variable

### ISSUE THREAD

**Issue by houbena** [jenkinsci/ghprb-plugin#120]
I'm wondering if there is a way to get the trigger passphrase and to use it in the job as a environment variable.

Thanks i.A.

The origin of the whole issue: For now am creating a new job for every passphrase. I want to reduce the number of jobs in a way similar jobs are gathered together, the passphrase is analysed in a build step and then it launches its corresponding task.

**Comment by jdonald** [comment]
By trigger passphrase do you mean the trigger comment?

I believe this is resolved in #313 i.e. aeb85d47

**Comment by bjoernhaeuser** [comment]
I will close this, if this still an issue please feel free to comment.
