### ISSUE TITLE
Github "pull_request" event not supported?

### ISSUE THREAD

**Issue by brunobasto** [jenkinsci/ghprb-plugin#121]
This is the message I get when my webhook tries to send the pull_request event to my Jenkins instance: 

    A problem occurred while processing the request.
        Please check <a href="https://issues.jenkins-ci.org/">our bug tracker</a> to see if a similar problem has already been reported.
        If it is already reported, please vote and put a comment on it to let us gauge the impact of the problem.
        If you think this is a new issue, please file a new issue.
        When you file an issue, make sure to add the entire stack trace, along with the version of Jenkins and relevant plugins.
        <a href="http://jenkins-ci.org/content/mailing-lists">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style="margin:2em; clear:both">javax.servlet.ServletException: java.lang.IllegalArgumentException: Github Webhook event of type pull_request is not supported. Only push events are current supported

I just updated the plugin.

These are the request headers:

    Request URL: ###/github-webhook/
    Request method: POST
    Authorization: ********
    content-type: application/x-www-form-urlencoded
    Expect: 
    User-Agent: GitHub-Hookshot/2f00e0f
    X-GitHub-Delivery: 31deb900-1ba2-11e5-8476-6f14de4238e3
    X-GitHub-Event: pull_request

Notice I omitted the actual URL to Jenkins instance.

**Comment by DavidTanner** [comment]
I have not seen this issue, but I think it belongs in the github-plugin.  Check which versions you are using and post them here.

**Comment by KostyaSha** [comment]
github-webhook belongs to github-plugin.

**Comment by brunobasto** [comment]
Thank you for your answers. Here are the versions of my plugins:

GitHub Pull Request Builder Plugin - 1.24.2
GitHub Plugin - 1.11.3
GitHub API Plugin - 1.68

What versions do you recommend using? In my scenario, all I want the ghprb plugin for is to build only the branch of the pull request that had just been sent. Right now it just doesn't work.

I'll post this issue to the GitHub Plugin issues tracker as well.

Thanks,
