### ISSUE TITLE
More build information available on Github comments.

### ISSUE THREAD

**Issue by QuinRogers** [jenkinsci/ghprb-plugin#126]
Hello, I would like to be able to post of the build information from Jenkins to the comment made on the Github pull request. Currently the list of environment variables that can be used is somewhat limited.

I would like to be able to post information such as the build duration, test results, build health and so on.

I have found a way to implement this functionality but it is pretty basic. I would be happy to contribute to the plugin as a whole and was wondering what the best way to add this functionality in would be. I looked at the possibility of making some of these things environment variables but those are set when the build starts and thus would not work for things like duration or test results.

How should I implement this to be consistent with the current way of doing things and how should it be offered as an option to users?

**Comment by benpatterson** [comment]
This can be accomplished using the downstream job pattern that was introduced in v 1.28. I'm closing this for now.
