### ISSUE TITLE
feature request: be able to override api url per job so can use both gh and ghe

### ISSUE THREAD

**Issue by paulczar** [jenkinsci/ghprb-plugin#127]
We have both github and github enterprise.  right now we can only use this with one or the other because the API uri is a global setting.  Would be great to be able to override this per job so that we can have PRs to both trigger different jobs.

**Comment by DavidTanner** [comment]
Version 1.24.x uses Jenkins credentials and provides this functionality.  There have been some issues switching over, but mostly that has settled out.
