### ISSUE TITLE
Caused by: java.io.IOException: Server returned HTTP response code: 401 

### ISSUE THREAD

**Issue by rourke750** [jenkinsci/ghprb-plugin#129]
http://pastebin.com/k0y0WA2M

No longer does the bot post updates to the github repo.  Any ideas?

**Comment by DavidTanner** [comment]
If you are using the latest version would you please add a logger for org.jenkinsci.plugins.ghprb, then we can verify that it is getting the credentials as expected

**Comment by rourke750** [comment]
I got this http://pastebin.com/h1x1Ygx6 after doing ok to test on a pull request in realistic biomes.

**Comment by DavidTanner** [comment]
It looks like the listing of credentials works, but for some reason the last filter didn't return them.

**Comment by DavidTanner** [comment]
Can I send you a rogue version with some alternate code?

**Comment by rourke750** [comment]
Sure how would it work.

**Comment by DavidTanner** [comment]
Download the file from this link, then go to the updates page and pick the file.  
https://drive.google.com/file/d/0B8rz_7UCga_nQWZQNm9KMzg0aEE/view?usp=sharing

**Comment by rourke750** [comment]
@DavidTanner new logs http://pastebin.com/m8dJFPtY  Also if it makes a difference I normally copy a project that is already done and update it with the corrected info although those projects used to work until some time later.

**Comment by DavidTanner** [comment]
So from the logs it would appear that the credentialsID is incorrect.  Try saving the configuration for the job that is failing again, then it should get the right setting.

**Comment by rourke750** [comment]
Would this be under GitHub Pull Request Builder?  I have the Github server API url set to: https://api.github.com and the credentials set for username and password.  When I press Connect to API it says Connected to https://api.github.com as null

**Comment by DavidTanner** [comment]
There are three different places to look for this.  There are the Jenkins credentials, then the global setup under /configure, finally there is the credentials selection on the job.  I am trying to think which one is set up incorrectly.  Check the job configuration.

**Comment by rourke750** [comment]
Under the project the credentials are set to none.  After changing them to the globally defined still getting the error.  Does testing the connection and it saying null mean anything?
http://pastebin.com/LYAq610p

Also thx for the help.

**Comment by rourke750** [comment]
Just ran with only credentials in the repo set http://pastebin.com/Ezwgki8U (from the jenkins log).

And this http://pastebin.com/db9Jk7jN was from the jar log while being built.  It says that is sent a comment when it did not.  Also at the bottom it does in fact set up the correct message in that special box that goes green saying that build was successful.  It just does not comment.

**Comment by DavidTanner** [comment]
So it looks like you have removed all credentials.  Add some more through the pull request section of the global configure page

**Comment by DavidTanner** [comment]
Would you please check 1.24.8?

**Comment by rourke750** [comment]
@DavidTanner Got [this](http://pastebin.com/A2AHrK9n) log but no jars are being built.  Only in the jenkins config is the username/password configured.

**Comment by DavidTanner** [comment]
There is an issue with the webhooks where the rep name has to match the case.  This is fixed in 1.25 or you can check that the repository url in the job matches the case of the GitHub repo

**Comment by rourke750** [comment]
@DavidTanner http://build.civcraft.co:8080/job/PrisonPearl-pull/

It's just stuck.

**Comment by DavidTanner** [comment]
can you see anything in the system logs?

**Comment by DavidTanner** [comment]
You might want to just restart that instance.

**Comment by rourke750** [comment]
http://pastebin.com/2HU5sWCq

**Comment by DavidTanner** [comment]
Can you please post a job configuration

**Comment by rourke750** [comment]
Is there an easy way to do that?

**Comment by DavidTanner** [comment]
The easiest is to get the config.xml

**Comment by rourke750** [comment]
Where can i find the file?

**Comment by rourke750** [comment]
Is this it http://pastebin.com/L59sqNR1

**Comment by DavidTanner** [comment]
That is the job config file for job PrisonPearl UUID development, and it doesnt have the pull request builder set up as its trigger.  Did you mean to post a different job?

**Comment by rourke750** [comment]
Sorry havent commented in a while.  Anyways recently tried removing everything and still have an issue which was weird.  By removing everything I uninstalled the plugin and when to manage old data and deleted it and reinstalled.  Still not get messages about build status.

What I did notice is it tends to double post on pull request creation, here are latest logs from newest version. http://pastebin.com/0aM03q50

**Comment by rourke750** [comment]
I'll get you the job config for this

**Comment by rourke750** [comment]
http://pastebin.com/kVZQct3e

**Comment by DavidTanner** [comment]
The build is being triggered?  Can you post the logs of the actual build?

**Comment by rourke750** [comment]
http://pastebin.com/dpxSU5kQ there you go.  It says its posting the message when it is not.

**Comment by DavidTanner** [comment]
From your post it is updating the status.  ```Setting status of 1f268b37ad5f0b206d71d81c7ed5f57b7308b8f5 to FAILURE with url http://build.civcraft.co:8080/job/FactoryMod-pull/42/ and message: 'Build failed.
 No test results found.'```
https://github.com/Civcraft/FactoryMod/pull/138 Look at the latest build results for ```default``` status and you will see that the status and link matches.  Are you looking for comments to be posted instead?

**Comment by DavidTanner** [comment]
the trigger plugin handles updating the comment for you, so you don't need the extra status updates, and they are probably being overridden?

**Comment by rourke750** [comment]
I am, is that no longer the case?  Also any idea on why it is double posting the type ok to test when someone sends a pull?

**Comment by DavidTanner** [comment]
The double post, I think, happens because you have multiple jobs that are set up for that repo???  The trigger has always posted the status to the commit, only recently I have added a way to remove any kind of status updates.

**Comment by DavidTanner** [comment]
In order for there to be comments, instead of status updates, you want to add the Build Status Messages and put something in there.
