### ISSUE TITLE
Trigger phrase doesn't accept regexp pattern

### ISSUE THREAD

**Issue by dtweston** [jenkinsci/ghprb-plugin#150]
According to the documentation here:
- Under Advanced, you can modify:
  - The phrase for adding users to the whitelist via comment. (Java regexp)
  - The phrase for accepting a pull request for testing. (Java regexp)
  - The phrase for starting a new build. (Java regexp)
  - The crontab line. This specify default setting for new jobs.

However, according to the source, this isn't interpreted as a regular expression, it's just a plain string:
https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java#L178-L180

Is this a bug? Or an error in the documentation?

**Comment by DavidTanner** [comment]
That is a little misleading.  The phrases that it is talking about are:
Add to white list phrase
Accept to test phrase
Test phrase

The trigger phrase is configured in the job config, and you are right, it is not a regex.

**Comment by dtweston** [comment]
Ah, I see what the difference is. Is there a reason why the trigger phrase is different?

Would you accept a patch to make it work like the others?

**Comment by KostyaSha** [comment]
> Ah, I see what the difference is. Is there a reason why the trigger phrase is different?

It is the result of maintainer merges without keeping uniform configuration in plugin.

**Comment by DavidTanner** [comment]
the only problem with a direct changeover would be that some trigger phrases may have reserved characters.  In your pull request if you accommodated that and escaped those trigger phrases I would merge it in.

**Comment by jdonald** [comment]
The recent fix works for me most of the time, but every day or so the trigger phrase gets corrupted with extra characters. <tt>\.\*ok to simul\.\*</tt> becomes <tt>\Q\.\*ok to simul\.\*\E</tt>. Sometimes there are multiple <tt>\Q\Q</tt> chars. When this happens, it no longer matches a string like <tt>ok to simulate</tt>, and we have to go back and edit the job configuration manually to remove the extra chars.

![image](https://cloud.githubusercontent.com/assets/1616866/10067217/6123ab96-624f-11e5-9396-f32d7be03a42.png)

Is this a known issue or some consequence of how it's attempting to sanitize the regular expressions?

**Comment by dtweston** [comment]
Fixed in #157

**Comment by DavidTanner** [comment]
@jdonald please open a new issue.  In the new issue please post the config.xml configVersion value.  It should be three.

**Comment by jdonald** [comment]
I have opened #197, and noted there that our configVersion is not 3.
