### ISSUE TITLE
Ignoring pull requests?

### ISSUE THREAD

**Issue by peymano** [jenkinsci/ghprb-plugin#151]
We have a tradition on our team of creating early pull requests for big features to solicit feedback. These PRs are incomplete, so triggering a build + running tests generates unnecessary noise (triggers emails, messages in Slack, etc). We mark these early pull requests with a pencil (✎) or "WIP" in the title. Is there a way to have ghprb skip over these PRs until we've removed these markers?

**Comment by DavidTanner** [comment]
Use the skip tests phrase in the pr description.  You can set it to be whatever you want in the regex.

**Comment by DavidTanner** [comment]
Sorry, did that answer your question?

**Comment by peymano** [comment]
I added "[skip ci]" to the PR's description and I'm still seeing builds & tests run after each commit.

**Comment by DavidTanner** [comment]
can you post here one of the descriptions?

**Comment by peymano** [comment]
We are updating the app to the new font styles. 

Today, we have approx. 200 places in code, where we load the font by calling `UIFont fontWithName:size`. The sizes don't map perfectly to the new styles. For each occurrence, we need to decide on the mapping, build it, find it in the app, correct it if needed and so forth. I've tried going down this path and it's very time consuming. I'd like to cap this effort to roughly 1 week.

So here's the plan I'm going with (I'm currently on 3):

1. I've defined preferred font styles that we'll use exclusively going forward when implementing new features (see: `Add preferred font styles` commit).

2. I've replaced all the occurrences of the calls to `UIFont fontWithName:size` to one of the calls we'll use for **style exceptions** e.g. `cz_regularFontWithSize:`, `cz_mediumFontWithSize:`, `cz_mediumItalicFontWithSize:` etc.

3. I'll fix up the calls above to make the app look good (based on Holly's and my own discretion), but I'll use the new styles only in the few major areas e.g. list headers, text body etc. 

4. If 3) doesn't take too much time (say 2-3 days), Holly and I will spend another day or two to migrate key modules (Meds, Inbox) to use the new styles exclusively.

I know everyone has an option on this, so this is your chance to voice it. See `UIFont+CZFont.m` to see where I'm going with this. 

If you run a build from this branch, you can tap the `ADD A NEW PERSON` button to see Font Guideline view that Holly and I used to finesse the fonts so that they appear almost identical to the ones used in PhotoShop. Unfortunately size X in PS is not size X on the actual device. Also, kerning is just very slightly off between the two.

[skip ci]
 
/cc: @peymano @wesgibbs @yas375

**Comment by DavidTanner** [comment]
I believe you have found a bug.  Something in the code isn't adding up.

**Comment by peymano** [comment]
We're running 1.16-8.

Settings:
![image](https://cloud.githubusercontent.com/assets/32817/8805706/92b15140-2f87-11e5-80b2-518e97442dbf.png)

**Comment by DavidTanner** [comment]
Looks to be because of the newline characters?  Not sure. I  will investigate and see if I can get a patch out today.

**Comment by DavidTanner** [comment]
For now you can add (?s) to the skip phrase and see if that works. 

As per the documentation:

DOTALL
public static final int DOTALL
Enables dotall mode.
In dotall mode, the expression . matches any character, including a line terminator. By default this expression does not match line terminators.
Dotall mode can also be enabled via the embedded flag expression (?s). (The s is a mnemonic for "single-line" mode, which is what this is called in Perl.)

**Comment by peymano** [comment]
Thanks @DavidTanner
