### ISSUE TITLE
Feature request: update commit status while waiting for permission to test a PR

### ISSUE THREAD

**Issue by ixdy** [jenkinsci/ghprb-plugin#152]
The developers on our project feel safe to merge a PR when all of the commit checks are green, including usually our Jenkins run.

However, if the Jenkins plugin asks for permission to test a PR, it doesn't update the commit status, and so a developer may miss that the tests weren't run. (For example, this recently happened on GoogleCloudPlatform/kubernetes#11379.)

If the plugin would mark a commit as pending while waiting for permission to run tests, it would make it very obvious that tests hadn't run yet. (Extra bonus if the commit status mentioned that it was waiting for permission.)

**Comment by mikedanese** [comment]
+1 this option would be super helpful.

**Comment by pmorie** [comment]
+1

**Comment by bjoernhaeuser** [comment]
For me it looks like this will be closed by #398

**Comment by bjoernhaeuser** [comment]
Closing this in favor of #398
