### ISSUE TITLE
How to build this plugin or an enhancement of the mergable state checking?

### ISSUE THREAD

**Issue by springw** [jenkinsci/ghprb-plugin#155]
Im using this plugin with an github enterprise server，for same reason，the server compares pull request a little slow. This makes some problem: I found this plugin wait up to only 5 seconds to check if a pull request mergable. So I want to modify the wait time and build one for the server.with the Java and maven installed, I build multijob and multi scm success,but have many exceptions and errors when build this plugin.Is the plugin need some special build environments ?

**Comment by benpatterson** [comment]
@springw I can't make a statement to who it was building this last summer, but at this point on master you should be good to go with mvn3 and just running `mvn package`. Closing this issue for now.
