### ISSUE TITLE
Broken PR <a> tag

### ISSUE THREAD

**Issue by gl0om** [jenkinsci/ghprb-plugin#162]
![2015-08-20 15 21 29](https://cloud.githubusercontent.com/assets/634726/9383206/c8534760-474f-11e5-86cb-5acc3799b454.png)
![2015-08-20 15 28 15](https://cloud.githubusercontent.com/assets/634726/9383365/20533a64-4751-11e5-98f7-9089cd57fa56.png)

GitHub Pull Request Builder v 1.27
GitHub plugin v 1.12.1
GitHub API Plugin v 1.69

**Comment by jlebon** [comment]
This may be due to the Markup Formatter being set to Escaped HTML. If that is the case, you can change this by going to "Configure Jenkins" --> "Configure Global Security" --> "Markup Formatter" --> "Raw HTML" (at the expense of slightly less security).

**Comment by gl0om** [comment]
thanks!
