### ISSUE TITLE
[Question/Feature Request] Commenting @user when a build succeeds/fails

### ISSUE THREAD

**Issue by isuda** [jenkinsci/ghprb-plugin#163]
Is it possible to do the following?

1. If the build fails, make a comment on the pull request telling the pull request author that the build failed?
example: "Build failed, @isuda". 

2. If the build succeeds, make a comment on the pull request telling the pull request assignee that the build succeeded and is ready to merge.
example: "All is well, @isuda".

This would be in conjunction with updating the github commit status.

Since builds take time to run it would be nice to notify the people responsible when the testing is completed, so that a person does not need to constantly check the pull request to see if it passed/succeeded.

**Comment by DavidTanner** [comment]
with the latest build you can use ```${ghprbPullAuthorLoginMention}``` under ```Trigger Setup``` select ```Build Result Message``` and you can add messages for success/error/failure.

**Comment by isuda** [comment]
Awesome, thanks!
