### ISSUE TITLE
org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook abuses Rate Limit

### ISSUE THREAD

**Issue by gbougeard** [jenkinsci/ghprb-plugin#165]
I have more than 300 jobs and 300 github repositories and I noticed `handleWebHook` runs every 10mn (I did not find where it is configured and if it is) but it burts my rate limit and fail not fast (maybe due to github-api lib which has no timeout on http calls and multiple retries?) .

So, is there a way to configure the frequency of calls to `handleWebHook` ? or at least debug or fine logs when an API call (and an effective http call) is done?

This is really critical has the entire Jenkins is affected and do not respond when this happens.

**Comment by DavidTanner** [comment]
The WebHook runs anytime that github sends something to Jenkins.  Github sends notifications every time there is a new pull request, or a change to one.

**Comment by gbougeard** [comment]
According to my logs I think there is a loop : 

```
Aug 28, 2015 8:05:48 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ccc-service-email_pr
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.GhprbWebHook
Comparing repository names: ebuzzing/service-kafka to ebuzzing/service-media-format, case is ignored
Aug 28, 2015 8:05:48 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials forb2daf6d6-*****************, using context lib-front-validators_pr for url https://api.github.com
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Aug 28, 2015 8:05:48 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context lib-front-validators_pr
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.GhprbWebHook
Comparing repository names: ebuzzing/ccc-service-email to ebuzzing/service-media-format, case is ignored
Aug 28, 2015 8:05:48 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for b2daf6d6-*****************, using context ccc-service-soizencoder_pr for url https://api.github.com
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
Aug 28, 2015 8:05:48 PM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using OAuth token for context ccc-service-soizencoder_pr
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.GhprbWebHook
Comparing repository names: ebuzzing/lib-front-validators to ebuzzing/service-media-format, case is ignored
Aug 28, 2015 8:05:48 PM INFO org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
Got payload event: pull_request
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for b2daf6d6-*****************, using context tests-integration-campaign-delivery_pr for url https://api.github.com
Aug 28, 2015 8:05:48 PM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 2 credentials
```

and so on. Like the `matchRepo` loop...

**Comment by DavidTanner** [comment]
It is looking through all of your projects trying to find the matching repo.  Are your sure that is abusing the rate limit though?  Looks like it needs to look up the jobs from a map instead of every job.

**Comment by gbougeard** [comment]
Github support tells me I have peaks to 250 queries/s . You can imagine with 300 repositories and jobs when 10 pull requests are submitted at the same time, it could call 3000 times github in few seconds! As the rate limit is 5k calls per hour...

**Comment by gbougeard** [comment]
And by the way, I understand it tries to find the matching repo, the thing I don't understand it's why it is looking for the credentials if the repo does not match! I believe this check does a call to the api.github.com/user route and this is the one Github reported to me.

**Comment by DavidTanner** [comment]
So each time that it accesses a job and tries to parse the message, it needs the auth details to see if there is a signature involved.  https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.27/src/main/java/org/jenkinsci/plugins/ghprb/GhprbWebHook.java#L28  

Part of the problem is that it checks the signature, then parses the event, then checks if the repo matches.

**Comment by gbougeard** [comment]
I understand. So it confirms there are X API calls for each pull_request where X is the number of repositories having jenkins jobs.

Could it not be possible before parse the whole payload to just get the repository involved before doing any API call?
In scala, using play-json we could get it with something like `repository \ name`.

**Comment by gbougeard** [comment]
Could we consider the possibility to only `checkSignature` after finding the matching repo?

**Comment by gbougeard** [comment]
Great! when could you release it?
