### ISSUE TITLE
Builds always set GitHub commit status to "No test result found"

### ISSUE THREAD

**Issue by martin-brennan-csnet** [jenkinsci/ghprb-plugin#168]
For every passing build the message "No test result found" is passed to the GitHub status is passed:

![image](https://cloud.githubusercontent.com/assets/10840857/9708867/866756ce-5565-11e5-988f-4a374252b823.png)

I see that this line is generated by the source file https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/manager/impl/GhprbBaseBuildManager.java . 

My question is, does this test result parser only work for JUnit tests? I'm using a TAP test reporter and result parser and I would like this output to determine the test results sent to GitHub. Is there any way to do this or would I have to use JUnit for this plugin to use the test results in the commit status? Thanks.

**Comment by slaunay** [comment]
You should try again with version `1.29.5` (see https://github.com/janinko/ghprb/issues/315).

**Comment by mrchief** [comment]
I'm using 1.29.8 and I don't see reports. I'm using `mocha` to run tests:

```
  "scripts": {
    "test": "mocha --compilers js:babel-core/register src/**/*spec.js"
  },
```

**Comment by benpatterson** [comment]
Hi - I'm helping out with this plugin...labeling some tickets where I need to take a closer look.

**Comment by benpatterson** [comment]
I've ramped up a bit and I agree with previous comments that this can be dealt with now with the latest version of the plugin. Closing.
