### ISSUE TITLE
Multiple build status

### ISSUE THREAD

**Issue by Puneeth-n** [jenkinsci/ghprb-plugin#170]
Hi,

Does ghprb-plugin provide the functionality of multiple build-status? I have 2 jobs listening on PRs of a repo. One job is a lint job and the other a test job. Is it possible to have the results of both on github PR? something like, `tests passed` `lint failed`

Thanks in advance.

**Comment by DavidTanner** [comment]
I would recommend updating the commit status, and using the context to differentiate which job ran.   But no, you couldn't combine the status directly

**Comment by Puneeth-n** [comment]
Thanks! :) Worked like a charm :)
