### ISSUE TITLE
Incorrect revision is picked up by matrix builds

### ISSUE THREAD

**Issue by p0deje** [jenkinsci/ghprb-plugin#171]
There is a problem which prevents configuration builds of multi-configuration (aka matrix) jobs to properly pick up the revision to be built against. There is no similar problem in usual freestyle jobs. When matrix job is configured to run at pull requests, the first time it's being run against a particular pull request, everything works fine. However, all other subsequent builds of this job against the same pull request will do the following:

1. Parent build is checked to correct revision.
2. Configuration builds are checked to the revision of previous parent build.

I'll try to follow this bug step by step:

1. When new build is started, Ghprb [adds last build BuildData to this run](https://github.com/janinko/ghprb/blob/a6d794f974fb66be7e2945be4dd62065ddcb585a/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L173) to calculate changelog (`findPreviousBuildForPullId` call).
2. The revision is correctly determined and checked out to by parent build.
3. Configuration builds now start. Git plugin has to ensure that both parent and configuration builds are checked out to the same revision, so [it tries to determine parent revision by looking at parent's BuildData](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/GitSCM.java#L920-931).
4. Since parent has 2 build datas (one from current build, one from last build), configuration builds check out to last build revision, not the current one.

I'm not sure how this can be fixed, so I simply removed the line to add last build data (I don't really use since I configure job to always calculate changelog against pull request target branch):

```diff
-        return this.job.scheduleBuild2(job.getQuietPeriod(), cause, new ParametersAction(values), findPreviousBuildForPullId(pullIdPv));
+        return this.job.scheduleBuild2(job.getQuietPeriod(), cause, new ParametersAction(values));
```

**Comment by DavidTanner** [comment]
Please check again with the latest version to see if this is still an issue.

**Comment by adelyafatykhova** [comment]
Hi! So once you removed the last line to add the build data, it fixed the issue for you? How do you configure your job to calculate the changelog against the pull request target branch? I'm running into the same issue now with Jenkings child jobs picking up the wrong info from the parent.

**Comment by p0deje** [comment]
@DavidTanner Sorry for not getting back to the issue, I think it got lost in my inbox. With the setup described below the issue no longer reproduces, so I guess it's fixed.

@adelyafatykhova Here is how our job Git config looks like:

1. Checkout to `${ghprbActualCommit}`
2. Enabled "Calculate changelog against a specific branch" set to `origin/${ghprbTargetBranch}`
3. Enabled "Merge before build" set to `origin/${ghprbTargetBranch}`
