### ISSUE TITLE
Possible to tell the pull request builder to ignore a PR

### ISSUE THREAD

**Issue by davidkiser** [jenkinsci/ghprb-plugin#194]
My org tends to use PRs for reviews,  even when theyre not ready to be officially run through our CI process.  

We use a WIP label to indicate that its not ready for CI to kick in,  so I'd like a way for the build to completely pass over a PR labelled with WIP.   Right now,  in my build script I parse through the labels,  find the 'WIP' label,  then exit out of the build with a failed status,  but this is a bit kludgey.  Is there a way to have the PR skipped completely if a corresponding label is found, similiar to how git polling will skip over it if no commits are found?

I saw a similiar question regarding using the skip phrase in the title/description,  I was curious if this might work with a Label

Thanks!

**Comment by DavidTanner** [comment]
There is a skip build option on the global configuration page.  By default it is ```[skip ci]```
