### ISSUE TITLE
Trigger phrase accumulates unwanted escape characters

### ISSUE THREAD

**Issue by jdonald** [jenkinsci/ghprb-plugin#197]
We are using a regular expression in the trigger phrase via the new feature in #157. However, it tends to stop functioning after each day as the trigger phrase accumulates special characters. For example, <tt>\.\*ok to sim\.\*</tt> becomes <tt>\Q\.*ok to sim\.\*\E</tt>

![image](https://cloud.githubusercontent.com/assets/1616866/10080229/53141bae-62a3-11e5-999c-b85a20cc5911.png)

This makes the regular expression no longer matching phrases it did before like <tt>ok to simulate</tt>.

The accumulated characters actually happen on non-regexp phrases too, but seem to be less of a problem when not concatenated with <tt>.*</tt>

![image](https://cloud.githubusercontent.com/assets/1616866/10082375/362986c2-62ae-11e5-8c5f-892f57fd211d.png)

@DavidTanner said to post the config.xml configVersion value and it should be three.
```
  <scm class="hudson.plugins.git.GitSCM" plugin="git@2.4.0">
    <configVersion>2</configVersion>
```
The version is two. Could that be tied to the problem?

**Comment by DavidTanner** [comment]
Please check with 1.28.6

**Comment by jdonald** [comment]
We upgraded, restarted Jenkins, and removed \Q and \E from the trigger phrase. However, the characters were added spontaneously again, possibly when we restarted Jenkins a second time.

Last time I only noticed one configVersion in config.xml, but perhaps I didn't search completely. AS of now there are several, many of which are not 3.

```

      <matrixOptions>
        <throttleMatrixBuilds>true</throttleMatrixBuilds>
        <throttleMatrixConfigurations>false</throttleMatrixConfigurations>
      </matrixOptions>
      <configVersion>1</configVersion>
```
and slightly below that:
```
  <scm class="hudson.plugins.git.GitSCM" plugin="git@2.4.0">
    <configVersion>2</configVersion>
```
The one next to the trigger phrase does say 3 though :
```
  <triggers>
    <org.jenkinsci.plugins.ghprb.GhprbTrigger plugin="ghprb@1.28.6">
      <spec>*/1 * * * *</spec>
      <triggerPhrase>\Q.*ok to simul.*\E</triggerPhrase>
      <configVersion>3</configVersion>
```

**Comment by DavidTanner** [comment]
So once the version is 3 the plugin won't change the trigger phrase anymore.  The idea was that if there were regex characters in the trigger phrase that weren't intended for a regex then they should be escaped.  Once it is on configVersion 3, just for the trigger, then it won't touch the value any more.

As a final test, if you were to restart Jenkins now you would not have the triggerPhrase be changed anymore.

**Comment by jdonald** [comment]
Last Friday we restarted our Jenkins master several times and it seemed to accumulate \Q and \E characters regardless, which I had to then promptly remove. Nonetheless I opted to let it bake over the weekend and it was pleasing to see no unwanted escape characters had appeared again up through yesterday.

However, this morning it is back. `\Q.*ok to simul.*\E` as a trigger phrase, so this is not fixed on our end. The pluginManager still says we still have version 1.28.6 of ghprb.

Anything else I can look at for troubleshooting?

**Comment by DavidTanner** [comment]
This is fixed in 1.29  The configVersion isn't saved until each job config is saved again, except in the new code the configVersion is saved when the trigger starts.

**Comment by jdonald** [comment]
Since 1.29, we haven't seen this issue recur and it has been a few days. Will reopen if that changes.

**Comment by mmitche** [comment]
@DavidTanner What happens if the Job DSL plugin generates a job that doesn't have configVersion set (which is what happens today)?  We're seeing this in our CI, which uses generated jobs.  I am thinking that the DSL plugin needs to set the configVersion.

**Comment by DavidTanner** [comment]
@mmitche lines affected by configVersion are:
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.29/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTriggerBackwardsCompatible.java#L53

And in the global configuration:
https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.29/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L806

**Comment by mmitche** [comment]
@DavidTanner Okay that makes sense now.  so would that mean that if you used the job DSL plugin to create a new job and it didn't set that field, that when that gets initially saved it would have configVersion 1?

**Comment by mmitche** [comment]
(which would then get incremented after saving again?)

**Comment by DavidTanner** [comment]
I don't know how that plugin works, but it would start out with whatever version it is created with, run the checks on the versions, and finally update the version to 3.  When the trigger is started afterwards that version would be saved to a config.xml, so if each job is created on the fly, then the check would run every time.

**Comment by mmitche** [comment]
@DavidTanner I want to understand the change that was made so I can make the right change in the DSL plugin.  Prior to configVersion 3, was it not using a regex?  Why would quoting version < 3 be the right thing but not for version == 3

**Comment by DavidTanner** [comment]
before version 3 the trigger phrase was just matching the string directly, as of 3 it is a regex.  I am assuming the pre version 3 you didn't intend for the trigger to match regex special characters.

**Comment by mmitche** [comment]
Oh oh okay.  Makes perfect sense now.  So, the right thing to do here is to update the DSL plugin to generate config version 3 directly.

**Comment by jmdh** [comment]
FWIW, we're seeing the behaviour described at the top of this issue; when the job config is saved manually (with no changes) the configVersion is being reset to 1, and then when Jenkins is restarted, the doubled up quote characters appear.We're running 1.29 (and Jenkins 1.633).

**Comment by jdonald** [comment]
Thanks @jmdh. We had no issues for a week or so, then it recurred and when I investigated the configVersion was set back to 1. I don't know what triggered that, but possibly one of our admins saved it with no changes, and yes we're still on 1.29.

I'll go ahead and reopen this as it has been confirmed for multiple parties.

**Comment by DavidTanner** [comment]
@jdonald @jmdh My bad.  https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.29.1/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L136

**Comment by jdonald** [comment]
We have not seen the issue recur in the past 8 days after upgrading to 1.29.2, so I believe this is indeed fixed now.
