### ISSUE TITLE
Pull Request Trigger only if changed file matches a regex

### ISSUE THREAD

**Issue by nitinpadalia** [jenkinsci/ghprb-plugin#205]
I want to use this plugin with a maven multi maven project. I've different jobs for each of my module, I would be invoking each job for a pull request using some phrase like 'please test'. Appropriate job should be triggered based on which files changed; e.g.; if I have two folders mod1 and mod2 then jobs job1 and job2 respectively then if I raise a pull request and issue a comment in pull request 'please test' then job1 should trigger if pull request has file changes as mod1/\* and if file changes are in mod2/\* then job2 should be triggered.

Is this possible with this plugin? or can we add support like we've in polling scm plugin for include or exclude regions.

**Comment by DavidTanner** [comment]
Please close janinko/ghprb#337

**Comment by bina-abhinav** [comment]
+1

**Comment by archmonk** [comment]
+1 this idea. I have  a much similar use case.

**Comment by faheem-cliqz** [comment]
Are there any updates on this one? It would be nice to have this :)

**Comment by bjoernhaeuser** [comment]
These settings are available in the git sections.

**Comment by bjoernhaeuser** [comment]
Actually you can set the "regions" which you want to include. That should work.
