### ISSUE TITLE
Triggering build with secondary commit status context discards default build status

### ISSUE THREAD

**Issue by jdonald** [jenkinsci/ghprb-plugin#208]
At our organization, for a long time we have been using one build status per commit, like so :

![image](https://cloud.githubusercontent.com/assets/1616866/10252938/687d2600-68ef-11e5-960f-e9e86ca2432d.png)

We have introduced a second optional build with the *Only use trigger phrase for build triggering* box checked, and a non-default *Commit Status Context* of `simulate`.

If a secondary build has been triggered after the primary one has passed (green checkmark), we then lose the previous result, and the commit status can never turn green again unless we force a Rebuild the default Commit Status Context job.

![image](https://cloud.githubusercontent.com/assets/1616866/10253080/48d0b078-68f0-11e5-932e-dbb1d8282508.png)

![image](https://cloud.githubusercontent.com/assets/1616866/10253099/630952b0-68f0-11e5-9ea7-cb0103133b5a.png)

@codemercenary has investigated and so far it appears that
> the `triggered` status is always set to the `default` status context, which is incorrect.

He may be able to provide further details.

We typically leave the *Commit Status URL*, *Commit Status Build Triggered*, and *Commit Status Build Started* fields blank, but we have also tried setting the latter two to `triggered` and `started`, to no avail. We have also tried putting an arbitrary *Commit Status Context* for the primary build, e.g. `buildsomething`, but this just worsens the situation with the default build remaining yellow forever.

**Comment by codemercenary** [comment]
Yep, this is pretty much like what I'm observing.  It seems like, for matrix builds, the status context when the build is triggered is always "default".  This is just something I observe on the GHE side; I haven't taken to setting breakpoints in GHPRB yet.

This is the case when we alter the "commit triggers" setting for the pull request builder.  We leave the "build status" assignment option blank, and only set commit statuses when we are triggered via pull request.

**Comment by jdonald** [comment]
We have yet to attach a debugger in Jenkins, but any additional insight would be appreciated.

Has anyone else here used ghprb with multiple build jobs and thus multiple status marks per commit? If you have seen this issue, or been able to run without encountering it, that would be useful to know.

**Comment by jdonald** [comment]
This issue appears to be fixed in our environment now, or at least we have not seen it for weeks.

I suspect that the problem was this additional configuration on one or both of our triggered jobs :
![image](https://cloud.githubusercontent.com/assets/1616866/12440340/4cc56d36-beef-11e5-8491-b991ec6e733f.png)

As this had been added by another engineer, I had thought that the Commit Status Build Result was a mandatory field, but it turns out it can be removed. Without it, we have not seen such status reporting issues.
