### ISSUE TITLE
Use token macro in comment message

### ISSUE THREAD

**Issue by rborer** [jenkinsci/ghprb-plugin#211]
Hi,

It would be great if we could use token macros from https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin when posting comments to github. This would give much more flexibility to the message content.

If you think it is a good idea, I would be happy to submit a PR with this change.

**Comment by anderssonjohan** [comment]
:+1:

**Comment by mprokopowicz** [comment]
:+1:

**Comment by edwardvfluke** [comment]
+1

**Comment by benpatterson** [comment]
This should be possible now with the downstream job pattern described in the (current version of the) README. That is, by creating a downstream job that receives whatever parameters you send, and sets something using the macro plugin. Let us know if that suffices?

**Comment by benpatterson** [comment]
No response (and admittedly this issue did not get a response from our side for a very long time either...I just jumped into help with the plugin recently). 

Anyway I think this is possible now so I'm closing the issue.
