### ISSUE TITLE
GitHub project property is missing the URL

### ISSUE THREAD

**Issue by mehtadev17** [jenkinsci/ghprb-plugin#218]
Error Message: 
```
Stopping the ghprb trigger for project cr-search-dev-frontend-fullregression
Oct 15, 2015 11:22:10 AM INFO org.jenkinsci.plugins.ghprb.GhprbTrigger start
GitHub project property is missing the URL, cannot start ghprb trigger for job job-name-here
```
Description: 
Trying to set up the plugin with GIT plugin. I set the repository url and have tested my connection to the target repo via the github api. The problem is not the API.  
The plugin doesn't seem to pull the repository url from GIT plugin -- https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin. 
I updated to the latest version of this plugin but had no luck. I will try updating the GIT plugin and see what happens. The version I have is 2.3.1

**Comment by efontana** [comment]
I am also seeing this error.

**Comment by onion-soup** [comment]
Same error here

**Comment by mehtadev17** [comment]
There are two places where you have to set the GIT URL on Jenkins: 
 1) Under "Do not Scan failed builds" called "Github Project"
 2) Under "Source Code Management" called "Git Repositories"

**Comment by mehtadev17** [comment]
![screen shot 2015-11-05 at 9 09 51 am](https://cloud.githubusercontent.com/assets/6795712/10970509/1b2b29ce-839d-11e5-9112-87109f177055.png)

**Comment by onion-soup** [comment]
I see. It works now. Thanks

**Comment by mehtadev17** [comment]
I have another error where the plugin doesn't support multiple Github apis. When I select the second one from the list, it reverts back to the original one for some reason. Let me know if you run into this issue.

**Comment by heisian** [comment]
I put in a valid URL to the repo, the problem is that it is a private repo...

**Comment by heisian** [comment]
ah.. forget this plugin.. the entire workflow can be easily configured w/ github and jenkins' github plugin...

**Comment by diogosimao** [comment]
Really, @heisian ?

**Comment by heisian** [comment]
well yes, if a plugin is no longer maintained there's no use trying to revive it. Other workarounds must be used.
