### ISSUE TITLE
Skip building when certain paths/file in a PR hasn't changed.

### ISSUE THREAD

**Issue by ghost** [jenkinsci/ghprb-plugin#221]
It would be really nice if there was an ability to skip building a pr if a particular path or file hasn't changed in a PR. 

Right now the prbuilder builds everytime a pr is opened against a branch but it would be nice if there was a way to tell it to build only when a particular path/file changes.

And unforunately this doesn't work in conjunction with the existing option("polling ignores commits in  certain paths") on the git plugin.

**Comment by DavidTanner** [comment]
There would need to be more logic around how a build gets triggered than there currently is.  I am looking to refactor the trigger logic anyways, so then this would be much easier to add.

**Comment by kz-flavius** [comment]
I've done it. I need it really fast, and I just finished the implementation. I will submit a pull request in the next 2 days. I've used janinko/ghprb but I will fork from this repo and add the changes. If it get's accepted you can use it in the same way as Include/Exclude regions from the SCM/git section.

**Comment by ysammy** [comment]
Did this enhancement make it into a PR? I would also love to see this functionality.

**Comment by DavidTanner** [comment]
It looks like there is an API call to get a list of files that have changed.  This would require that every time we check a PR we also call out to get the list of changed files.  

https://developer.github.com/v3/pulls/#list-pull-requests-files

**Comment by botchniaque** [comment]
@DavidTanner is the extra API call a problem?

**Comment by benpatterson** [comment]
Fixed with #293
