### ISSUE TITLE
401 Auth error connecting to enterprise instance

### ISSUE THREAD

**Issue by tylersmith34** [jenkinsci/ghprb-plugin#227]
I have an enterprise instance of GH v2.4 and I'm unable to get my pull request builds to work.  I have configured the access token and I am able to verify the credentials in the master jenkins settings.  I can even post a comment to an open pull request.

However, when the pull request is created or a comment/commit is added, Jenkins throws a 401.

The corporate Jenkins is behind HTTPS.

Here's a piece of the log:

```
Oct 30, 2015 4:08:49 PM WARNING org.jenkinsci.plugins.ghprb.GhprbPullRequest obtainAuthorEmail

Couldn't obtain author email.
java.io.IOException: Server returned HTTP response code: 401 for URL: http://github.company.com/api/v3/users/username
```

**Comment by bjoernhaeuser** [comment]
Closing this for now due to inactivity.
