### ISSUE TITLE
"Add link to Jenkins" and "Append portion of build log" options don't always show up in Application Setup

### ISSUE THREAD

**Issue by jameschao** [jenkinsci/ghprb-plugin#231]
I'm not sure what the conditions that trigger this is, but I've noticed that the "Add link to Jenkins" and "Append portion of build log" don't always show up. Right after I restart Jenkins I would see these options, but there are times when these don't show up, which totally threw me off when I was trying to re-enable the links to the Jenkins build.

**Comment by emoshaya-cognito** [comment]
I have the exact same issue..

**Comment by jameschao** [comment]
This is still happening, and the "add link to Jenkins" field disappears every few days. It only comes back after a Jenkins reboot...

**Comment by firon** [comment]
This happens to me as well. What seems to happen is that after the system configuration is saved once after running for a few hours, the plugin removes the extension to add links from the xml, then hides it from the UI.

**Comment by jameschao** [comment]
Thanks @DavidTanner!
