### ISSUE TITLE
ghprbCommentBody is wrong when new commits are pushed

### ISSUE THREAD

**Issue by robertfalconer** [jenkinsci/ghprb-plugin#233]
To allow retesting of only specific tests, in the case of an intermittent failure, I have added a step to a build script that checks `ghprbCommentBody` for a retest message that matches a certain pattern (e.g. `retest tests1 please`). When the plugin triggers a build after a `retest` comment is posted everything works fine, but if a new commit is added to the PR branch to trigger a build, the `ghprbCommentBody` is still set to previous `retest` message used. Even if I were to add in another comment to the PR (thinking it might only be looking at the most recently comment) before pushing a new commit, the `ghprbCommentBody` remains set as the previous `retest` message.

**Comment by jmdh** [comment]
This appears to be the same as https://issues.jenkins-ci.org/browse/JENKINS-40802, which contains a trivial fix.
