### ISSUE TITLE
doesn't support two-factor authentication

### ISSUE THREAD

**Issue by amejiarosario** [jenkinsci/ghprb-plugin#240]
I'd like to use this plugin for our enterprise account, which requires all users to have enabled two-factor authentication.
With regular auth, it will work fine....but when I try to use it with a user with two factor authentication it would give the following error:
`Unable to connect to GitHub API: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user`
Is there any way to make it work?

**Comment by mmitche** [comment]
Do you mean authenticating as the user to run the build?  In that case your username/password will be the username + generated access token.

**Comment by benpatterson** [comment]
With two-factor authentication, you should have an API endpoint that will accept an access token as the form of verification.

**Comment by bjoernhaeuser** [comment]
this plugin only needs an oauth token. No need to 2FA for this, right?
