### ISSUE TITLE
Cancel old jobs when a PR is updated multiple times

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [jenkinsci/ghprb-plugin#241]
When a job is updated quickly several times, one job is queued for each update. In cases where no concurrent jobs are allowed, this means a bunch of job will be run when they are completely obsolete.

It would be nice to have an option to automatically cancel any existing jobs for a particular PR when a trigger is received. An option to even abort the current build (if any) for the PR could be useful too.

**Comment by pratik60** [comment]
+1

**Comment by mathroc** [comment]
:+1:

**Comment by wI2L** [comment]
+1

**Comment by eyphka** [comment]
:+1:

**Comment by mmitche** [comment]
I don't think it should be that hard to implement, since we already previous looked for the last build of a job for a given PR.

**Comment by DavidTanner** [comment]
I don't think it is along the same lines as the previous build.  We just need to look at the current builds for a project and see if they match the PR, then tell them to stop.  I am not so sure about pending builds though.

**Comment by mmitche** [comment]
@DavidTanner Yeah, you don't need to look everything, just an example of how we already have a mechanism of telling whether a previous build was for the PR we are about to launch.  I think stopping pending is good too, since input parameters could be slightly different (which would cause them not to be elided)

**Comment by DavidTanner** [comment]
@mmitche if you want to see an example, I have the IT tests watching for the builds to finish before evaluating things.  They used to use timers.  I am thinking that same code will work here.

**Comment by DavidTanner** [comment]
@mmitche https://github.com/jenkinsci/ghprb-plugin/blob/ghprb-1.30.3/src/test/java/org/jenkinsci/plugins/ghprb/GhprbTestUtil.java#L404

**Comment by mmitche** [comment]
@DavidTanner Yeah, you would walk through the queue before tryBuild and see whether you could find another build that is running that PR for that job and cancel.  The only thing that is interesting there is how to ensure that an aborted job doesn't update the GH status as failed (it should stay pending)

**Comment by DavidTanner** [comment]
@mmitche If the build knows it was cancelled then we can just watch for that, and not do any updates in that case.

**Comment by mmitche** [comment]
@DavidTanner That might be correct in the case where it got manually aborted (say, someone decided it was running too long).  In that case the PR is truly failed.  Maybe there is a way to find out how it was cancelled (manually vs. internally?)

**Comment by leandro-lucarella-sociomantic** [comment]
Wow! Amazing. Thanks!

**Comment by daniel-gomes-sociomantic** [comment]
this seems to still fail if there is a job running for a certain PR and the PR's branch is rebased and pushed (with -f), which creates a new job run but doesn't cancel the running job
