### ISSUE TITLE
 GitHub Pull Request Builder- GitHub API credentials is getting reverted in the jobs 

### ISSUE THREAD

**Issue by kishorerc** [jenkinsci/ghprb-plugin#243]
when there are multiple GitHub API credentials are setup and when selected in the jobs they are getting reverted to a default. unable to use different GitHub API credentials as part of GitHub Pull Request Builder option in the jobs. Could you please help with this issue and let us know for any further information.
Jenkins ver. 1.597 or Jenkins ver. 1609.3
GitHub Pull Request Builder plugin -1.27

**Comment by mnordsletten** [comment]
I'm running into this issue as well. Here is what I've noticed so far:
When selecting a credential to use, hitting save and apply it will work as intended. Though when going back into the configuration menu it will reset the drop down menu to the credential at the top. If you then hit save and apply it will indeed reset the choice you made earlier. Which means you must make sure you've selected the same credential every time you go into the configuration menu.
