### ISSUE TITLE
JobDSL doesn't expose Build Result Message

### ISSUE THREAD

**Issue by dgreene-r7** [jenkinsci/ghprb-plugin#247]
Hi,

I'd like to programmatically define a Build Result Message (i.e. what displays as a comment in the pull request when the build is complete) in a Job DSL file. Unfortunately, it looks like only the `commitStatus` extension has been created. Am I missing something and this just isn't documented or is this just a missing feature?

**Comment by DavidTanner** [comment]
Check out #229

**Comment by andrewfraley** [comment]
So is it still missing or just undocumented?

**Comment by andrewfraley** [comment]
I'm sure there's a cleaner way to do this, but I don't know what I'm doing.  This works, however.  Add this to your dsl groovy

```
 configure {
        it / triggers / 'org.jenkinsci.plugins.ghprb.GhprbTrigger' / extensions / 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildStatus' / messages << 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildResultMessage' {
          message('All tests passed!')
          result('SUCCESS')
        }
      }

      configure {
        it / triggers / 'org.jenkinsci.plugins.ghprb.GhprbTrigger' / extensions / 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildStatus' / messages << 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildResultMessage' {
          message('An unknown error occurred.')
          result('ERROR')
        }
      }

      configure {
        it / triggers / 'org.jenkinsci.plugins.ghprb.GhprbTrigger' / extensions / 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildStatus' / messages << 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildResultMessage' {
          message('Code failed to pass tests!')
          result('FAILURE')
        }
      }
```

**Comment by bphalak** [comment]
Not works for me can you please share complete job.

**Comment by bphalak** [comment]
This is working code for me...
`job('example') {`
  `    triggers {`
   ` githubPullRequest {`
.
.
    ` }`
  ` }`

`configure {`
    `def messages = it / triggers / 'org.jenkinsci.plugins.ghprb.GhprbTrigger' / extensions / 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildStatus' / messages`
    `messages << 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildResultMessage' {`
     ` message('All tests passed!')`
      `result('SUCCESS')`
    `}`
    `messages << 'org.jenkinsci.plugins.ghprb.extensions.comments.GhprbBuildResultMessage' {`
      `message('An unknown error occurred.')`
     ` result('ERROR')`
    `}`
 ` }`
`}`
` }`

**Comment by benpatterson** [comment]
Closing this; since it's documented in the README and implemented now.
