### ISSUE TITLE
sha1 is sha sometimes, pr ref others

### ISSUE THREAD

**Issue by timcosta** [jenkinsci/ghprb-plugin#248]
So I'm currently stuck using a super old version (1.9), and sometimes the `sha1` environment variable is showing up as the commit sha, aka mirroring `ghprbActualCommit`. Other time it is showing up as a PR ref such as `origin/pr/9/merge`. This seems to be repository specific, however I cannot figure out why I get the ref on some repositories and not others. 

I am cloning a known functional job that provides the pr ref, and simply updating the repository references and shell steps of the cloned job, however the environment variables do not seem to be consistent. 

`remotes/origin/pr/22/merge [5124cdf5]` is what I want, where the first part is the ref passed in.
`detached [f51af2dc]` is what I get more often than not.

`+refs/pull/*:refs/remotes/origin/pr/*` is the refspec on both of the above jobs.

Any thoughts? Hoping someone has seen this before as I am not able to quickly update to `ghprb@latest`.

**Comment by sonoble** [comment]
I am seeing this on the latest version.

**Comment by klaussilveira** [comment]
Confirmed on the latest version. `sha1` doesn't mirror `ghprbActualCommit`, causing parametrized builds to be stuck with the default value.

**Comment by bjoernhaeuser** [comment]
See #594 for an explanation, will land in master soon. If this does not solve your case please comment / reopen.

Thanks!
