### ISSUE TITLE
Option to add a custom label to a PR

### ISSUE THREAD

**Issue by erez-rabih** [jenkinsci/ghprb-plugin#254]
Hi,

I wanted to offer a feature: The user should be able to set a custom label that will be attached to a PR according to the build status.

Does it make sense?

**Comment by benpatterson** [comment]
Hi I'm helping clean up some old issues. This feature is available nowadays and is documented. I'm closing it.

**Comment by biaomingzhong** [comment]
@benpatterson Did not find any solutions for this feature. Why close this issue?

 **Add custom label** to PR according to the **build result**
