### ISSUE TITLE
ghprb stores transient info in the job file

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [jenkinsci/ghprb-plugin#256]
I recently upgrade from 1.29.5 to 1.30 and I noticed now the plugin stores the last PR tested in the config, for example:
```xml
      <pullRequests class="concurrent-hash-map">
        <entry>
          <int>955</int>
          <org.jenkinsci.plugins.ghprb.GhprbPullRequest>
            <id>955</id>
            <updated>2016-01-29 19:56:56.0 UTC</updated>
            <head>9ced4278ac0af138846672da6b103172a09e37ae</head>
            <accepted>true</accepted>
            <changed>false</changed>
          </org.jenkinsci.plugins.ghprb.GhprbPullRequest>
        </entry>
      </pullRequests>
```

This is quite inconvenient for me, as I have all jenkins config versioned. This is first time I see a job file storing information that changes from run to run, so this mean I will get a lot of config updates that are completely irrelevant, and not really data the user configure.

Can this information be stored in another file?

**Comment by DavidTanner** [comment]
Will be fixed in #259

**Comment by gregbeecroft-taulia** [comment]
+1, we use chef-client and upload all of our job XML files from a Git repo periodically, so when Chef overwrites the XML for a given job this info disappears, and we are seeing multiple builds for a single PR for no good reason.

**Comment by leandro-lucarella-sociomantic** [comment]
> Will be fixed in #259

Thanks!

**Comment by leandro-lucarella-sociomantic** [comment]
Oh, this is worse than I thought, if you change a job configuration via Jenkins' web interface, all PR metadata is removed from the job configuration too. Will be a release with this fix soon?

**Comment by DavidTanner** [comment]
The latest is released,  1.30.1

**Comment by DavidTanner** [comment]
@leandro-lucarella-sociomantic please check and close if the result is acceptable

**Comment by leandro-lucarella-sociomantic** [comment]
It's working great! Thanks a lot for the quick fix!
