### ISSUE TITLE
Merge only works when trigger phrase is present

### ISSUE THREAD

**Issue by bchavet** [jenkinsci/ghprb-plugin#257]
The code at https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequestMerge.java#L129-L135

```
        // If merge can only be triggered by a comment and there is a
        // comment
        if (commentBody == null || !helper.isTriggerPhrase(commentBody)) {
            logger.println("The comment does not contain the required trigger phrase.");
        } else {
            intendToMerge = true;
        }
```

Is preventing a merge if the trigger phrase is not present in the comment. Nowhere in the configuration does it say anything about a trigger phrase for merging, and "Only use trigger phrase for build triggering" in the Build Trigger config has no effect on this behavior.

I think we should be able to allow Jenkins to merge a pull request, regardless of the content of the comment.

**Comment by bchavet** [comment]
I should also add that this even prevents the merge if the trigger phrase is in the initial comment when the pull request is created. It only allows a merge if there is a later comment with the trigger phrase.

**Comment by mattkrea** [comment]
Definitely a +1 here.

This is causing the auto-merge feature to essentially be useless for our group.

**Comment by DavidTanner** [comment]
With the latest version it shouldn't matter when you add the trigger comment anymore.

**Comment by mattkrea** [comment]
@DavidTanner But is still requires one to auto-merge even if I don't have one set, correct? That is what I'm seeing at least.

**Comment by dulvac** [comment]
+1. Please let's have this. It doesn't make any sense to not allow merging if the jenkins job admin explicitly checked the box that says it should.

**Comment by dulvac** [comment]
@DavidTanner, could you have a look at https://github.com/jenkinsci/ghprb-plugin/pull/381 please?

**Comment by bchavet** [comment]
@dulvac I don't have a good way to test or verify this, but on the surface it looks good.

**Comment by dulvac** [comment]
The PR was merged, Thanks @DavidTanner. You can close the issue.

**Comment by bchavet** [comment]
👍 

This works great! Thanks @dulvac and @DavidTanner!
