### ISSUE TITLE
Duplicated comment asking to approve PR when using different jobs for different branches

### ISSUE THREAD

**Issue by psiroky** [jenkinsci/ghprb-plugin#267]
We are using two different Jenkins jobs to build PRs for different branches (using the branch white list feature). It works great for people present in the white-listed org. units, but once someone outside of that creates PR, Jenkins (ghprb) sends two different comments asking to approve the PR (see below):
![ghprb-duplicated-comment](https://cloud.githubusercontent.com/assets/670547/13004057/59a60424-d179-11e5-9695-be38ab3a4874.png)

I could not find anything related in the log besides this:

```
Feb 12, 2016 9:56:02 AM FINE org.jenkinsci.plugins.ghprb.GhprbTrigger
Running trigger for jbpm-pullrequests-6.x
Feb 12, 2016 9:56:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Looking up credentials for 21876262-6e87-4e1f-9e7f-0951d00e6c36, using context jbpm-pullrequests-6.x for url https://api.github.com
Feb 12, 2016 9:56:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Using null context because of issues not getting all credentias
Feb 12, 2016 9:56:02 AM FINE org.jenkinsci.plugins.ghprb.Ghprb
Found 6 credentials
Feb 12, 2016 9:56:02 AM FINEST org.jenkinsci.plugins.ghprb.GhprbGitHubAuth
Using username/password for context jbpm-pullrequests-6.x
Feb 12, 2016 9:56:02 AM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR #398 target branch: master isn't in our whitelist of target branches: org.jenkinsci.plugins.ghprb.GhprbBranch@64b0a254
```

So the plugin correctly figures out that the PR does not uses the white listed target branch, but still sends the comment asking for approval.

I will do some more digging in the sources (hopefully soon) and will let you know in case I find something.

Jenkins version: 1.642.1
Ghprb version: 1.29.8

**Comment by ifireball** [comment]
I can confirm this happens for every single job you define, we have multiple GitHub repos each with its own jobs, connected to the same Jenkins master. When non-org members send PRs, they get as many comment as we have jobs.

**Comment by psiroky** [comment]
Fixed by https://github.com/jenkinsci/ghprb-plugin/pull/533
