### ISSUE TITLE
Whitelisting causes log activity but no Whitelisting

### ISSUE THREAD

**Issue by larry-svds** [jenkinsci/ghprb-plugin#275]
Below is an odd problem we are having with whitelisting people.  More generally I just want it to work and would be quite happily to add everyone on my team to a whitelist without working through the git hub comments.     

 * is there a UI location where I can add people to a whitelist.
 * Where is the whitelist stored? 
 * the Admin List allows multiple people to be listed?  Do you put one per line or comma separated?
 * These admin list and whitelist entries are all github identities right?  

These would be good additions to the documentation.

So on with the strange behaviour described in the title. 

My config.xml shows   <version>1.644</version>
my plugins/ghprb/META-INF/MANIFEST.MF shows 

     Plugin-Version: 1.29.8
     Hudson-Version: 1.532
     Jenkins-Version: 1.532

In my jenkins configuration my admin list is "larry-svds"    this is my account on github. 

If say jeff-svds does a pull request on a repo with ghprb turned on.  Then the message "Can one of the admins verify this patch?"

If I come in and enter "ok to test" as a comment.  I get the following in the jenkins log. 

> Feb 24, 2016 6:28:43 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@39f29622' for repo silicon-valley-data-science/Trains
Feb 24, 2016 6:28:43 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests
Feb 24, 2016 6:28:43 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@5bbe4a22' for repo silicon-valley-data-science/Trains
Feb 24, 2016 6:28:44 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #159 was updated on silicon-valley-data-science/Trains at 2/24/16 6:28 PM by User:larry-svds
Feb 24, 2016 6:28:44 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests

And no build is actually performed.  

if I go to the pull request from jeff-svds I then go in and say 
"add to whitelist"   (my Add to white list phrase is   .*add\W+to\W+whitelist.*  )  then this happens in the logs. 

> Feb 24, 2016 6:48:28 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@3411d237' for repo silicon-valley-data-science/Trains
Feb 24, 2016 6:48:29 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #155 for job trains-pull-requests
Feb 24, 2016 6:48:29 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@51216140' for repo silicon-valley-data-science/Trains
Feb 24, 2016 6:48:29 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #155 was updated on silicon-valley-data-science/Trains at 2/24/16 6:48 PM by User:larry-svds
Feb 24, 2016 6:48:29 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #155 for job trains-pull-requests

If I the user jeff-svds, after being "whitelisted" then does a pull request.  He gets two comments on his pull request "Can one of the admins verify this patch?"  this is what is in the logs. 

>INFO: Received POST for https://github.com/silicon-valley-data-science/Trains
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #159 for silicon-valley-data-science/Trains
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #159 for silicon-valley-data-science/Trains
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #159 for silicon-valley-data-science/Trains
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking PR #159 for silicon-valley-data-science/Trains
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handlePR
INFO: Checking PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Author of #159 jeff-svds on silicon-valley-data-science/Trains not in whitelist!
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handlePR
INFO: Checking PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRepository onPullRequestHook
WARNING: Unknown Pull Request hook action: assigned
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handlePR
INFO: Checking PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Author of #159 jeff-svds on silicon-valley-data-science/Trains not in whitelist!
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handlePR
INFO: Checking PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:50 PM org.jenkinsci.plugins.ghprb.GhprbRepository onPullRequestHook
WARNING: Unknown Pull Request hook action: assigned
Feb 24, 2016 5:36:51 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Created Pull Request #159 on silicon-valley-data-science/Trains by jeff-svds (null) updated at: 2/24/16 5:36 PM SHA: test_jenkins
Feb 24, 2016 5:36:51 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest <init>
INFO: Created Pull Request #159 on silicon-valley-data-science/Trains by jeff-svds (null) updated at: 2/24/16 5:36 PM SHA: test_jenkins
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@59b7bd7' for repo silicon-valley-data-science/Trains
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@133da71' for repo silicon-valley-data-science/Trains
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@23d8ab40' for repo silicon-valley-data-science/Trains
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
INFO: Checking issue comment 'org.kohsuke.github.GHIssueComment@12863899' for repo silicon-valley-data-science/Trains
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #159 was updated on silicon-valley-data-science/Trains at 2/24/16 5:36 PM by User:jenkins-svds
Feb 24, 2016 5:36:53 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests
Feb 24, 2016 5:36:54 PM org.jenkinsci.plugins.ghprb.GhprbWebHook handleComment
INFO: Checking comment on PR #159 for job trains-pull-requests

Note it says he is not on the whitelist twice.   This may be because the project works on two repos. 

if I go in, the person listed in the configured Admin list, larry-svds, and submit a pull request, I also get 2 messages as well, and I also get log entries that say I am not on the whitelist.  

 * Are admins not automatically whitelisted?
 * is an admin a github account name entered into the Admin list box on the configuration?

Under none of these scenarios did a build kick off in such a way that it affected the statistics on the main dashboard.  The plugin is definitely chattering with jenkins and github..

**Comment by DavidTanner** [comment]
can you please post your config.xml for the job?

**Comment by larry-svds** [comment]
looks like I was looking at the wrong job for the whitelist information.  I added silicon-valley-data-science (our github org name) to the list of organizations on the correct project and everything is working as expected now.

As far as my account not being able to whitelist people with "add to whitelist" .  I was in the "Admin list" at the jenkins configuration level, but was not listed in the job's "Admin list".   is:

 * Admins specified at the Jenkins configuration level automatically an Admin at the Job level?
 * Admins at the Jenkins configuration level populate the Admin section at the Job level (but this only happens when the project is created after that configuration)?  or 
 * Each Job needs to specify its own admins. 

The section of the correct job's config.xml is 

```
<org.jenkinsci.plugins.ghprb.GhprbTrigger

 plugin="ghprb@1.29.8">
      <spec>H/5 * * * *</spec>
      <latestVersion>3</latestVersion>
      <triggerPhrase></triggerPhrase>
      <configVersion>3</configVersion>
      <adminlist></adminlist>
      <allowMembersOfWhitelistedOrgsAsAdmin>false</allowMembersOfWhitelistedOrgsAsAdmin>
      <orgslist>silicon-valley-data-science</orgslist>
      <cron>H/5 * * * *</cron>
      <buildDescTemplate></buildDescTemplate>
      <onlyTriggerPhrase>false</onlyTriggerPhrase>
      <useGitHubHooks>true</useGitHubHooks>
      <permitAll>false</permitAll>
      <whitelist></whitelist>
      <autoCloseFailedPullRequests>false</autoCloseFailedPullRequests>
      <displayBuildErrorsOnDownstreamBuilds>false</displayBuildErrorsOnDownstreamBuilds>
      <whiteListTargetBranches>
        <org.jenkinsci.plugins.ghprb.GhprbBranch>
          <branch></branch>
        </org.jenkinsci.plugins.ghprb.GhprbBranch>
      </whiteListTargetBranches>
      <project>trains-pull-requests</project>
      <__project class="maven2-moduleset" reference="../../.."/>
      <gitHubAuthId>f74986c4-6a5a-4f54-9664-c692d6cc1a4a</gitHubAuthId>
      <extensions>
        <org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus>
          <commitStatusContext></commitStatusContext>
          <triggeredStatus></triggeredStatus>
          <startedStatus></startedStatus>
          <statusUrl></statusUrl>
        </org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus>
      </extensions>
    </org.jenkinsci.plugins.ghprb.GhprbTrigger>
```

**Comment by DavidTanner** [comment]
Please try again with the latest release.

**Comment by benpatterson** [comment]
Closing but you can reopen with more detail if this is still an issue.
