### ISSUE TITLE
Question: How can I have multiple triggerPhrases?

### ISSUE THREAD

**Issue by danielcbright** [jenkinsci/ghprb-plugin#284]
I would like to be able to have multiple triggerPhrases for  a trigger such as:

```
<triggerPhrase>plan 1</triggerPhrase>
<onlyTriggerPhrase>false</onlyTriggerPhrase>
<triggerPhrase>plan 2</triggerPhrase>
<onlyTriggerPhrase>false</onlyTriggerPhrase>
```

Is this possible? If so I'll make a PR to update the README.md to reflect it.

Thanks

**Comment by DavidTanner** [comment]
The trigger phrase is a regular expression now.  `(plan 1|plan 2)` would give you two.

**Comment by danielcbright** [comment]
Great, thanks @DavidTanner

**Comment by DavidTanner** [comment]
Correct.

**Comment by djwgit** [comment]
if have several test phrases configured. 
in jenkins task, possible to know which test phrase triggered a task run ?
like to have the jenkins task do different things if triggered by a commit, or test phrase...
thanks
