### ISSUE TITLE
Plugin Tests Don't Run Correctly

### ISSUE THREAD

**Issue by tlusk** [jenkinsci/ghprb-plugin#285]
I forked and built the plugin with the intent of making some changes to it, but I can't get the plugin tests to run correctly no matter what I do.

First issue is it's throwing hundreds of `java.lang.NoClassDefFoundError: jenkins/model/TransientActionFactory` exceptions.  Turns out this was caused when a dependency to the plugin for `org.jenkins-ci.plugins:job-dsl:1.39` was added.  This is because the version of jenkins the plugin is being built against doesn't have the `TransientActionFactory` class the `job-dsl` plugin references.

This error can also be seen in all the logs on the jenkins server building the official plugin.  From what I can tell the unit tests aren't being run correctly there either.  [Check the console output on any of the builds here.](https://jenkins.ci.cloudbees.com/job/plugins/job/ghprb-plugin/)

I then tried upping the version it's being built against to `1.554.1`, and while that fixes the TransientActionFactory error I'm now getting NullPointerExceptions coming from the mocked `RequestImpl.bindJSON` method.

I also tried checking out older tags of the plugin and building/running the tests on them, but no matter what version I try the tests never run.

So the question is, am I missing something here?  Or do the tests just not work, and have they ever worked?

**Comment by DavidTanner** [comment]
I have a few questions first.  What version of Java are you using?  I have only been able to run it under 1.6.  If you are developing in eclipse did you run the mvn command to create the eclipse dependencies or did you import an existing maven project? 

I know the errors have been there in development, but I haven't known what to do to remove them.  I am not sure how the process works for updating the core version of Jenkins would need to go through.    In spite of all of the errors in the logs, the tests do run through properly.

**Comment by tlusk** [comment]
So I'm running it in IntelliJ with the imported pom.xml, all the dependencies are resolving correctly that's not an issue.

I was running it with a 1.8 JDK w/ 1.6 bytecode compatibility but I just tried running the tests on an older version with a 1.6 JDK and they mostly run without errors which the 1.8 JDK never did so it appears that does make a difference.

On the other hand, running the tests post 882bbd79f73e2099c7c1125ce5994d0952cf4464 still produces a giant wall of `java.lang.NoClassDefFoundError: jenkins/model/TransientActionFactory` errors no matter the JDK version.

**Comment by DavidTanner** [comment]
For the moment in development I am not sure how to get rid of that noClassDef error.  Maybe @daspilker, @mmitche, or @eriten can weigh in here?

**Comment by mmitche** [comment]
I haven't looked into it enough to find out what's going on.  Maybe ask on the dev list?

**Comment by daspilker** [comment]
Job DSL 1.39 depends on Jenkins core 1.596, but `TransientActionFactory` has been introduced in 1.548, see https://github.com/jenkinsci/jenkins/commit/f1a751f79dfbb975e4c436fd0967323e1ae7b8c6#diff-32ad850dc9eab2d9f7b2d9c0fd22b977.

So you need to update to Jenkins core 1.548 (or the 1.554 LTS line) in your POM (https://github.com/jenkinsci/ghprb-plugin/blob/master/pom.xml#L8) to get rid of the errors.

**Comment by tlusk** [comment]
@daspilker is correct on that, unfortunately upgrading the jenkins version isn't as straightforward as changing the jenkins core in the pom as version `1.548` / `1.554` and above cause issues in the unit tests related to the mocked out `RequestImpl` class.

I managed the suppress the warnings in #287 by adding a custom logging properties file for the test which suppress anything below `SEVERE` coming from the hudson namespace.  It also filters out all the hudson INFO tags which bloat the console output too as a bonus, leaving only unit test warnings and errors.

The jenkins core should probably be updated at some point though.  I don't think compatibility is needed to be maintained anymore on 1.532, a version from late 2013.

**Comment by DavidTanner** [comment]
I have never updated the core Jenkins dependency and am a bit timid about doing so.  If it is not as big an issue as I am fearing I wouldn't mind upgrading the version and fixing things as necessary.  Is this something I should ask in the Jenkins Dev channel, or should I just move ahead with it anyways?

**Comment by daspilker** [comment]
@DavidTanner see http://stats.jenkins-ci.org/plugin-installation-trend/jenkins-version-per-plugin-version.json for some statistics about your plugin installations (search for ghprb). As far as I see only a few people are using core versions older than 1.554, so just move ahead.

Updating the core version usually leads to some compile and test failures, but those can be fixed easily. @tlusk already did an analysis, so you know what to expect.

**Comment by tlusk** [comment]
@DavidTanner FYI If you change the core `>=1.557` you won't need the Java 8 workaround from https://github.com/tlusk/ghprb-plugin/commit/618f4004a0455ac731b052e5485520aae04d1609#diff-600376dffeb79835ede4a0b285078036R98

The newer version of xstream was introduced into the core in `1.557` here: https://github.com/jenkinsci/jenkins/commit/585eb87c2d1fdd93c585efca2b993ad734afdb20

**Comment by tlusk** [comment]
I tracked down the reason for the test failures in Jenkins `1.336+` were introduced by the increase in the stapler version from `1.118` to `1.120+` https://github.com/jenkinsci/jenkins/commit/c01333c346176c93e8cbf93b5822978d8d2c0bff#diff-357e4854869b2e21c38b1b437f11095aL45

I'm still working on the exact cause and coming up with a fix.

**Comment by tlusk** [comment]
Fixed it, but turns out I just implemented the same thing @DavidTanner already did in https://github.com/jenkinsci/ghprb-plugin/commit/5502aa9801e3827821db697c0ba7b64f9188d15b#diff-41f3169d5f341e0c6433978e173e325fR363

Guess there's no need anymore...
