### ISSUE TITLE
WebHook recieved but not triggering event.

### ISSUE THREAD

**Issue by sflint** [jenkinsci/ghprb-plugin#286]
Webhook set for github repository and the receiving 200 back from jenkins server.  Logs look like this: 

`
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:16:48 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
`

Have another project with the exact same configurations and this is what the logs look like for it. 
`
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook checkSignature
INFO: Signatures checking OK
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
INFO: Got payload event: push
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.ghprb.GhprbWebHook handleWebHook
WARNING: Request not known
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
INFO: Received POST for https://github.com/OdenTech/oden_dal
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber$1 run
INFO: Poked DevOdenDal
Mar 04, 2016 8:13:03 AM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber$1 run
INFO: Poked OdenDal
Mar 04, 2016 8:13:04 AM com.cloudbees.jenkins.GitHubPushTrigger$1 run
INFO: SCM changes detected in DevOdenDal. Triggering  #457
Mar 04, 2016 8:13:12 AM jenkins.plugins.slack.SlackNotifier$SlackJobProperty prebuild
INFO: Invoking Started...
Mar 04, 2016 8:13:12 AM jenkins.plugins.slack.ActiveNotifier getChanges
INFO: Entry hudson.plugins.git.GitChangeSet@8584ed66
Mar 04, 2016 8:13:12 AM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting: to #engineering on odentech using https://odentech.slack.com/services/hooks/jenkins-ci?token=F4m37RrBsfd9myItg0J4IA4B: DevOdenDal - #457 Started by changes from sam.flint (1 file(s) changed) (<http://github-jenkins-652346236.us-west-2.elb.amazonaws.com/job/DevOdenDal/457/|Open>) good
Mar 04, 2016 8:13:12 AM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
Mar 04, 2016 8:13:25 AM hudson.model.Run execute
INFO: DevOdenDal #457 main build action completed: SUCCESS
Mar 04, 2016 8:13:25 AM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting: to #engineering on odentech using https://odentech.slack.com/services/hooks/jenkins-ci?token=F4m37RrBsfd9myItg0J4IA4B: DevOdenDal - #457 Success after 15 sec (<http://github-jenkins-652346236.us-west-2.elb.amazonaws.com/job/DevOdenDal/457/|Open>)
No Tests found. good
Mar 04, 2016 8:13:26 AM jenkins.plugins.slack.StandardSlackService publish
INFO: Posting succeeded
`

The differences start with : 
`
org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
INFO: Received POST for https://github.com/OdenTech/oden_dal
`

I am not sure what is looking for this event but I also compared the payloads from github and they look identical except for the repo names and etc.    I have the "Build when a change is pushed to GitHub"  checked for both of these projects.   The only difference I can see between them is the GitHub project name.

**Comment by DavidTanner** [comment]
It looks like GitHub is sending the wrong kind of events.  The plugin only accepts pull_request and issue_comment events.  GitHub is sending a push event, so I am not sure but you might have configured the webhook using a different plugin??  Check your master config and make sure you are only telling the job triggers to use webhooks.  Also, make sure you have checked the box in each job you want that says to build using webhooks.

**Comment by benpatterson** [comment]
Hi - I'm cleaning up old issues. It looks like this is either abandoned or resolved, so  I am closing.

**Comment by Ascendance** [comment]
It's happing again, unfortunately

**Comment by EniariGames** [comment]
I'm having the same issues

**Comment by xkcoding** [comment]
I'm having the same issues

**Comment by pranavmody** [comment]
Facing the same issue!

**Comment by JackHowa** [comment]
facing the same issue
