### ISSUE TITLE
Ability to only post commit statuses from the top level matrix job and hide its children jobs

### ISSUE THREAD

**Issue by amritp55** [jenkinsci/ghprb-plugin#301]
Right now GHPRB commits statuses for both the matrix configuration build, and its individual children. However, problems arise when we only want/care about the status of only the matrix configuration build. With the current implementation, the commit status is changing frequently because it is being overridden by both the matrix build and its children, thus it yields inaccurate results. While this behaviour is correct when we want different context for every children, we also want behaviour where only the status of the parent is posted. 

**Desired Functionality **
Have an option that will ask the user whether the user wants to post commit statuses from the matrix configuration build but not the children builds. When this box is clicked, the the job's children will not post statuses, but the job itself will.

Functionality when the checkbox is not clicked: 
![screen shot 2016-03-16 at 2 15 56 pm](https://cloud.githubusercontent.com/assets/3113195/13828951/a3eeaef6-eb81-11e5-8a64-a7e9db8d9183.png)

Only the status of the Matrix Job is posted
![screen shot 2016-03-16 at 2 18 31 pm](https://cloud.githubusercontent.com/assets/3113195/13828955/a8f34ee8-eb81-11e5-9053-46436e8e8a7f.png)

**Comment by amritp55** [comment]
I have worked on this and have a working solution to this issue. However, the checkbox in the form will always default to false, and not the last option that was saved by the user.

**Comment by amritp55** [comment]
Got the checkbox to save the default value on [PR 309](https://github.com/jenkinsci/ghprb-plugin/pull/309)

**Comment by Eriten** [comment]
Hey @DavidTanner and @amritp55, The PR is now merged. I think we can close this issue.
