### ISSUE TITLE
Customize Build Status Message

### ISSUE THREAD

**Issue by mattjmorrison** [jenkinsci/ghprb-plugin#304]
From what I can tell it looks like updating that build status is pretty specific to test output ([based on what I can see here](https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/manager/impl/GhprbBaseBuildManager.java#L175) and [here](https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatus.java#L201)). That is what makes the build status appear like:

![image](https://cloud.githubusercontent.com/assets/150277/13848186/a78f2d7c-ec1e-11e5-8cd0-1aa526348a94.png)

I haven't been able to find a way to set that status to something more custom - for example I have a separate build that runs static analysis and uses the [Violations plugin](https://wiki.jenkins-ci.org/display/JENKINS/Violations) to report violations in the Jenkins UI - it would be nice if I could have the build status updated to "Build finished. X violations found." or something along those lines.

I've tried playing around with having my job set a custom environment variable and trying to use that but I couldn't seem to get that to work. Is there some way to already accomplish this? Is there some way to integrate this plugin with the Violations plugin to make that information available?

I'm open to any suggestions of things that may already accomplish this. I would also be willing to submit a PR to make this customization possible (however I may need some direction on the best way of accomplishing it).

Thank you!

**Comment by benpatterson** [comment]
Hi - I'm helping out with this repo. I'm not sure of the state on Mar 17; however, this kind of customization should be available in the downstream jobs pattern that's described in the README today. I'll close this but feel free to re-open if that's not helping.
