### ISSUE TITLE
Environment variables not being expanded on merge comment

### ISSUE THREAD

**Issue by fgimenez** [jenkinsci/ghprb-plugin#310]
Hi, not sure if this is the right place to ask this kind of question, for this project, sorry if not. I'm trying to set a merge comment in the "GitHub Pull Request Merger" postbuild action similar to what github uses:

```
Merge pull request #${ghprbPullId} from ${ghprbPullAuthorLogin}/${ghprbSourceBranch}
    
${ghprbPullTitle}

${ghprbPullLongDescription}
```

However the environment variables are not being expanded, how can this be done?

Thanks! :)

**Comment by DavidTanner** [comment]
That would be an oversight(bug) on my part.  I will get that fixed and pushed out this week.

**Comment by fgimenez** [comment]
@DavidTanner thanks a lot! :blush:
