### ISSUE TITLE
Rebase with master before merging

### ISSUE THREAD

**Issue by elopio** [jenkinsci/ghprb-plugin#311]
I would like to use the github pull request merger to land PRs into master. But I would like to rebase them with master before pushing there the PR code. Would that be possible?

**Comment by eriweb** [comment]
Would be great if the branch to rebase from was configurable per build job

**Comment by benpatterson** [comment]
How would one resolve merge conflicts in this case?

**Comment by benpatterson** [comment]
Another question..I wonder if it would make sense to rebase before running the tests.

**Comment by bjoernhaeuser** [comment]
I think the only way how this could work if the plugin utilizes the "merge target branch into branch". 

@eriweb @elopio would that work in your case? What do you think?

**Comment by elopio** [comment]
Sorry, we moved from jenkins to travis, so I no longer have a use case to see if this would work. Thanks a lot for your work here anyway.

**Comment by bjoernhaeuser** [comment]
Closing this for now, please reopen / comment if it pops up again.
