### ISSUE TITLE
Seeing "Trigger only phrase but we are not triggered" when no admins defined.

### ISSUE THREAD

**Issue by AaronME14** [jenkinsci/ghprb-plugin#323]
This issue: https://github.com/janinko/ghprb/issues/153 seems to have re-emerged. However, I have set up the job with no admins, and I have disabled treating members of whitelisted orgs as admins. I have removed whitelisted orgs to test and still cannot get the PR Builder to work with 1.31.3.

Comment was made after last update time, :+1: 
Apr 12, 2016 6:32:24 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
[AaronME14] Added comment: :+1: 
Apr 12, 2016 6:32:24 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Trigger only phrase but we are not triggered

**Comment by DavidTanner** [comment]
Do you have the trigger only option checked?

**Comment by AaronME14** [comment]
Yes. Here's some more information:
Admin list: Empty
Use github hooks for build triggering: true
Only use trigger phrase for build triggering: true
White list: empty
List of organization. Their members will be whitelisted: <name or repo owner org> (fails when empty, also)
Allow members of whitelisted organizations as admin: true (fails when false, also)

Installed plugins:
Git plugin 2.4.4
GitHub API Plugin: 1.72.1
GitHub Plugin: 1.18.2
GitHub Pull Request Builder: 1.31.3


Thanks.

**Comment by DavidTanner** [comment]
You have the trigger phrase only parameter set, but aren't using the trigger phrase to start the build.  There was a change that only trigger phrases allow merging, so you will have to set and use the trigger phrase to trigger a build and merge.

**Comment by AaronME14** [comment]
David,
Thank you. We have tracked down the issue and it's unrelated to the plugin. I really appreciate your assistance.

For anyone who might run into this:
We use +1 comments on github as code reviews/approvals to test. At some point in the last week github changed their +1 shortcut translation from :+1:  to <U+1F44D>

This resulted in several +1 comments not matching the trigger phrase.

-Aaron.
