### ISSUE TITLE
Line Coverage percentage  on build status

### ISSUE THREAD

**Issue by appraveen** [jenkinsci/ghprb-plugin#324]
Would it be possible to publish line coverage from jacoco plugin to github ?

Substitute $junit_line_coverage with actual value 

![image](https://cloud.githubusercontent.com/assets/2443047/14549346/cbff7124-0273-11e6-9052-e08ec97afe11.png)

**Comment by benpatterson** [comment]
This should be possible now with the downstream job pattern, which is described in the README. One would want to pass the jacoco data from the ghprb job to the downstream job for posting status.

**Comment by benpatterson** [comment]
Closing; no response so I assume we're all set.
