### ISSUE TITLE
Quotes in Pull Request title not properly escaped.

### ISSUE THREAD

**Issue by MicahZoltu** [jenkinsci/ghprb-plugin#327]
I created a pull request named:
> Moves to a "simplified" build/deploy process.

This resulted in build descriptions like:
> <a ​title=“Moves ​to ​a ​”simplified“ ​build/deploy ​process.” ​href=“ https://source.datanerd.us/bro​wser/metric-stat-aggregator/pu​ll/4" PR ​#4: ​Moves ​to ​a ​”simplified" ​bui…

Upon removing the quotes from my PR title, I now got a build description like this:
> PR #4: ​Moves ​to ​a ​simplified ​build…

![image](https://cloud.githubusercontent.com/assets/886059/14723967/25c1da64-0803-11e6-8b8a-b5cfc5eb218f.png)

**Comment by KostyaSha** [comment]
Disable HTML security markup in security page.

**Comment by kelseyq** [comment]
I had this problem too, if anyone stumbles upon it. I fixed it by selecting "Safe HTML" as the Markup Formatter on Manage Jenkins > Configure Global Security.

**Comment by benpatterson** [comment]
Resolved by #430
