### ISSUE TITLE
Unable to trigger job with "add to whitelist" comments

### ISSUE THREAD

**Issue by fgimenez** [jenkinsci/ghprb-plugin#329]
Hi, I'm working on a deployment with all the configuration under version control. In order to persist the modifications made by the "add to whitelist" comment on the running server, I've created a job that submits a PR against the CI repo, with "add to whitelist" as the trigger command, but it doesn't start after the comment has been sent (although the log acknowledges the command being received).

It would be very useful to be able to trigger additional jobs using reserved comments, pls let me know if any further info on the subject is needed.

Thanks!

**Comment by DavidTanner** [comment]
If you also have trigger phrase only on then you will need to use that comment to trigger the build. If this is not the case would you please post your logs and relevant portion of your job config.xml

**Comment by fgimenez** [comment]
@DavidTanner hey thanks for your response :)

The job is configured to be triggered by "add to whitelist", this is the relevant part: https://github.com/ubuntu-core/snappy-jenkins/pull/145/files#diff-7d7bb5dd60b2bdab0a5cebc5834b0298R46 

And this is the log I get after sending the "add to whitelist" comment http://paste.ubuntu.com/16126341/, the job doesn't get triggered

Thanks!

**Comment by DavidTanner** [comment]
A couple things stand out to me, the user that commented isn't an admin, and there are no branches included in the config.  So I think it will see the comment, but toss it as it isn't in an approved branch, wasn't commented by an admin or user that is whitelisted.

**Comment by fgimenez** [comment]
Sorry, the config and the log didn't match, this is the config used for testing that generated that log http://pastebin.com/rHXMjazU, the user sending the comment is in fact an admin. Where should the branches be included?

Thanks a lot :)

**Comment by benpatterson** [comment]
I'm wondering if this still an issue?
