### ISSUE TITLE
Feature-Request: Whitelist or blacklist events

### ISSUE THREAD

**Issue by jamischarles** [jenkinsci/ghprb-plugin#338]
Love the plugin!

Currently I force push to a PR a lot. That can mean I have 3-4 jobs going against the same PR. I have a phrase `buildme` that fires off a build as well. I want to build a job on the first PR push, AND then when I issue 'buildme' as a comment.

**Use case**: 

Currently I have this github webhook: 
**Pull Request**
_Pull Request opened, closed, assigned, labeled, or synchronized._

I really only want this event to be fired when the PR is opened. NOT when I force push.

Having a white/black list would allow me to ignore the `sync` event.

**Comment by bjoernhaeuser** [comment]
you can always use trigger configuration, parallel builds or cancel builds on new push. :)
