### ISSUE TITLE
Skip Build Phrase Fix and Improvements

### ISSUE THREAD

**Issue by rsennewald** [jenkinsci/ghprb-plugin#339]
1. Bug:  Skip Build Phrase in the Advanced Section under Github Pull Request Builder on a job cannot be modified.  If you change it's value to anything else, it doesn't work and will always retain the default value.
2. Improvement: It would be great if Skip Build Phrase would also check the pull request's title (it currently just checks the pull request's body) for the skip phrase.  I have members of my team requesting this.
3. Improvement: Skip Build Phrase doesn't have any Job DSL support, it would be great to add DSL support for this.

**Comment by benpatterson** [comment]
Looks like this has been addressed with #340. Closing.
