### ISSUE TITLE
Plugin does not provide the environment variables it is supposed to

### ISSUE THREAD

**Issue by fallberg** [jenkinsci/ghprb-plugin#342]
After a recent upgrade (Jenkins to 2.5 and plugin to 1.31.4) the plugin no longer provide the needed environment variables which cause the build to fail:

GitHub pull request #441 of commit 3433d2da7885066777bc177f073df87313b9947c, no merge conflicts.
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/MySensorsArduinoLibPR/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository git@github.com:mysensors/Arduino.git
 > git init /var/lib/jenkins/jobs/MySensorsArduinoLibPR/workspace # timeout=10
Fetching upstream changes from git@github.com:mysensors/Arduino.git
 > git --version # timeout=10
using GIT_SSH to set credentials GitHub SSH key account for Jenkins
 > git -c core.askpass=true fetch --tags --progress git@github.com:mysensors/Arduino.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url git@github.com:mysensors/Arduino.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@github.com:mysensors/Arduino.git # timeout=10
Fetching upstream changes from git@github.com:mysensors/Arduino.git
using GIT_SSH to set credentials GitHub SSH key account for Jenkins
 > git -c core.askpass=true fetch --tags --progress git@github.com:mysensors/Arduino.git +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse origin/${ghprbActualCommit}^{commit} # timeout=10
 > git rev-parse ${ghprbActualCommit}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
[WARNINGS] Skipping publisher since build result is FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/jobs/MySensorsArduinoLibPR/workspace/Documentation/html to /var/lib/jenkins/jobs/MySensorsArduinoLibPR/htmlreports/Doxygen_HTML
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Sending email to: ${ghprbActualCommitAuthorEmail}
Finished: FAILURE

No ghprb variables are present in the environment variables of the job:
_	/usr/bin/daemon
BUILD_CAUSE	GHPRBCAUSE
BUILD_CAUSE_GHPRBCAUSE	true
BUILD_DISPLAY_NAME	#134
BUILD_ID	134
BUILD_NUMBER	134
BUILD_TAG	jenkins-MySensorsArduinoLibPR-134
BUILD_URL	http://ci.mysensors.org/job/MySensorsArduinoLibPR/134/
EXECUTOR_NUMBER	4
HOME	/var/lib/jenkins
HUDSON_HOME	/var/lib/jenkins
HUDSON_SERVER_COOKIE	2792193ede3460f8
HUDSON_URL	http://ci.mysensors.org/
JENKINS_HOME	/var/lib/jenkins
JENKINS_SERVER_COOKIE	2792193ede3460f8
JENKINS_URL	http://ci.mysensors.org/
JOB_BASE_NAME	MySensorsArduinoLibPR
JOB_NAME	MySensorsArduinoLibPR
JOB_URL	http://ci.mysensors.org/job/MySensorsArduinoLibPR/
KEYMAP	sv-latin1
LANG	en_US.UTF-8
LC_ALL	sv_SE.UTF-8
LOGNAME	jenkins
MAIL	/var/mail/jenkins
NODE_LABELS	master
NODE_NAME	master
PATH	/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD	/var/lib/jenkins
ROOT_BUILD_CAUSE	GHPRBCAUSE
ROOT_BUILD_CAUSE_GHPRBCAUSE	true
SHELL	/bin/bash
SHLVL	1
USER	jenkins
XDG_RUNTIME_DIR	/run/user/110
XDG_SESSION_ID	c14

**Comment by jonnyhsu** [comment]
This is due to the latest security updates.
https://jenkins.io/blog/2016/05/11/security-update/
https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170

**Comment by fallberg** [comment]
Ok, thanks for the info. I will work around it locally per one of the suggestions and await an update that fixes this on a better way. I saw there was a PR on progress on the matter.

**Comment by jabooth** [comment]
@DavidTanner sorry if we're not understanding the implications of security 170, but we are still not getting the env variables injected using version 1.32.1. Here's a build log:
https://jenkins.menpo.org/view/pr/job/menpo-pr/PYTHON_VERSION=3.4/199/console

Of which the relevant section is:
```python
the following envs are set for inspection:
{'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.{***}/Render',
 'BINSTAR_USER': 'menpo',
 'BUILD_DISPLAY_NAME': '#199',
 'BUILD_ID': '199',
 'BUILD_NUMBER': '199',
 'BUILD_TAG': 'jenkins-menpo-pr-PYTHON_VERSION=3.4-199',
 'BUILD_URL': 'https://jenkins.menpo.org/job/menpo-pr/PYTHON_VERSION=3.4/199/',
 'CONDACI_VERSION': '0.7.0+4.g8ce5fec',
 'CONDA_PY': '34',
 'EXECUTOR_NUMBER': '1',
 'GIT_BRANCH': 'origin/pr/701/merge',
 'GIT_COMMIT': '8ce5fec70aec07fae5b48d7548978c6fbb7ec5c9',
 'GIT_PREVIOUS_COMMIT': 'c527b3c987dc4eb69c0d499bd80d58d15221c1ad',
 'GIT_URL': 'https://github.com/menpo/menpo',
 'HOME': '/Users/jenkins',
 'HUDSON_COOKIE': '{***}',
 'HUDSON_HOME': '/Users/jenkins/.jenkins',
 'HUDSON_SERVER_COOKIE': '{***}',
 'HUDSON_URL': 'https://jenkins.menpo.org/',
 'JAVA_HOME': '/Library/Internet '
              'Plug-Ins/JavaAppletPlugin.plugin/Contents/Home',
 'JAVA_MAIN_CLASS_274': 'Main',
 'JENKINS_HOME': '/Users/jenkins/.jenkins',
 'JENKINS_SERVER_COOKIE': '{***}',
 'JENKINS_URL': 'https://jenkins.menpo.org/',
 'JOB_BASE_NAME': 'PYTHON_VERSION=3.4',
 'JOB_NAME': 'menpo-pr/PYTHON_VERSION=3.4',
 'JOB_URL': 'https://jenkins.menpo.org/job/menpo-pr/PYTHON_VERSION=3.4/',
 'LOGNAME': 'jenkins',
 'NODE_LABELS': 'master',
 'NODE_NAME': 'master',
 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
 'PWD': '/Users/jenkins/.jenkins/jobs/menpo-pr/workspace/PYTHON_VERSION/3.4',
 'PYTHON_VERSION': '3.4',
 'SHELL': '/bin/bash',
 'SHLVL': '1',
 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.ur6vCSl6T7/Listeners',
 'TMPDIR': '/var/folders/hg/{***}/T/',
 'USER': 'jenkins',
 'WORKSPACE': '/Users/jenkins/.jenkins/jobs/menpo-pr/workspace/PYTHON_VERSION/3.4',
 'XPC_FLAGS': '0x0',
 'XPC_SERVICE_NAME': '0',
 '_': '/Users/jenkins/miniconda/1/3.4/bin/python',
 '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0'}
```

To check, using ghprb 1.32.1 with Jenkins 2.5 we should still expect the usual `ghprb*` env variables to be set without further action on our part right? If so, it seems that #344 hasn't fixed the issue, at least for us.

**Comment by orrc** [comment]
@jabooth: That's a matrix job you're running, and that plugin is also affected by SECURITY-170, though there's not a fix yet: https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170

So that's probably the reason why you're not seeing the variables.  1.32.1 works for me in a freestyle job.

**Comment by jabooth** [comment]
@orrc ah yes apologies, seems the PR is being discussed here https://github.com/jenkinsci/matrix-project-plugin/pull/36

Thanks!

**Comment by patricksnape** [comment]
We've updated to 1.32.2 and 1.7 on the matrix plugin and we are still seeing this problem.
