### ISSUE TITLE
Current build parameters are not passed to a downstream parameterized job

### ISSUE THREAD

**Issue by juhakuu** [jenkinsci/ghprb-plugin#352]
After upgrading this plugin from 1.31.4 to 1.32.1 on Jenkins 1.642.1, passing current build parameters to a downstream job stopped working.

Issue https://github.com/jenkinsci/ghprb-plugin/issues/350 sounds like it's probably related to this, too.

In our job configuration this plugin triggers a build on a Jenkins job that does some common preparatory actions and then triggers parameterized builds (using version 2.30 of the Parameterized Trigger Plugin) of multiple actual test jobs, passing through the current build parameters (so we have sha1, ghprbPullId etc available in the downstream jobs) so we can post test results to separate contexts in the github PR, as well as posting some static analysis findings as comments via [pronto](https://github.com/mmozuras/pronto). Now that the env variables are not getting passed through to the downstream job, neither setting commit status or posting comments via pronto from the downstream jobs works.

Using the "Predefined parameters" parameter passing option instead of "Current build parameters", and manually specifying all the required env variables seems to still work, so it might be possible to work around this issue with that.

**Comment by juhakuu** [comment]
Just verified that everything works fine with the workaround, by plugging the following to be passed as predefined parameters:

```
sha1=${sha1}
ghprbActualCommit=${ghprbActualCommit}
ghprbActualCommitAuthor=${ghprbActualCommitAuthor}
ghprbActualCommitAuthorEmail=${ghprbActualCommitAuthorEmail}
ghprbAuthorRepoGitUrl=${ghprbAuthorRepoGitUrl}
ghprbTriggerAuthor=${ghprbTriggerAuthor}
ghprbTriggerAuthorEmail=${ghprbTriggerAuthorEmail}
ghprbTriggerAuthorLogin=${ghprbTriggerAuthorLogin}
ghprbTriggerAuthorLoginMention=${ghprbTriggerAuthorLoginMention}
ghprbPullId=${ghprbPullId}
ghprbTargetBranch=${ghprbTargetBranch}
ghprbSourceBranch=${ghprbSourceBranch}
ghprbPullAuthorEmail=${ghprbPullAuthorEmail}
ghprbPullAuthorLogin=${ghprbPullAuthorLogin}
ghprbPullAuthorLoginMention=${ghprbPullAuthorLoginMention}
ghprbPullDescription=${ghprbPullDescription}
ghprbPullTitle=${ghprbPullTitle}
ghprbPullLink=${ghprbPullLink}
ghprbPullLongDescription=${ghprbPullLongDescription}
ghprbCommentBody=${ghprbCommentBody}
ghprbGhRepository=${ghprbGhRepository}
ghprbCredentialsId=${ghprbCredentialsId}
```

**Comment by juhakuu** [comment]
Tested upgrading to 1.32.2 and this issue still persists.

**Comment by lifeofguenter** [comment]
Still having problems as well

**Comment by jlebon** [comment]
Right, I think this is because ghprb now doesn't define parameters on the triggered job, but directly injects them as environment variables. As a result, the "Current build parameters" option doesn't have anything to pick up anymore.

> Just verified that everything works fine with the workaround, by plugging the following to be passed as predefined parameters:
> ```
> sha1=${sha1}
> ghprbActualCommit=${ghprbActualCommit}
> ghprbActualCommitAuthor=${ghprbActualCommitAuthor}
> ...
> ```

I'm surprised this even works. Don't you also have to add them as explicit parameters in the downstream job? Otherwise Jenkins will just ignore it. Quoting from [this page](https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170):

> Parameterized Trigger Plugin
> 
> Parameters (e.g. when using properties files as source) are only passed if they are defined on the downstream job. This is the behavior intended by the SECURITY-170, see Jenkins Security Advisory 2016-05-11

**Comment by oradwell** [comment]
We are having an issue caused by the same change. Our job has a parameter for "sha1" which we can use to specify a branch to build if we want to. After the upgrade to 1.32.1 the parameter no longer got set by the plugin.

Plugin documentation suggests us to add this sha1 parameter (which makes sense) to manually build the job. If it's no longer usable please update the documentation to avoid more people having the same issue.

Since our default sha1 value was master our job started building master instead of the PRs!

I downgraded our plugin back to 1.31.4 until this is fixed.

**Comment by johnnyshields** [comment]
:+1: exact same issue as oradwell. Filed issue here: https://issues.jenkins-ci.org/browse/JENKINS-35170

**Comment by juhakuu** [comment]
> I'm surprised this even works. Don't you also have to add them as explicit parameters in the downstream job? Otherwise Jenkins will just ignore it.
That's interesting! I've currently only configured one of the downstream jobs to explicitly take in ghprbPullId and sha1 as parameters (that one does the pronto stuff) - the rest of them aren't explicitly configured as being parameterized in the downstream job. All of the downstream jobs' build parameter listings still list all the parameters specified in the upstream job.

**Comment by johnnyshields** [comment]
@DavidTanner what's the plan for this? Running the latest version of GHPRB on latest Jenkins is broken...

**Comment by mmitche** [comment]
@DavidTanner @johnnyshields I saw this with the build flow plugin too.  I'll look into this today.

**Comment by mmitche** [comment]
I believe this is because of this security update: https://jenkins.io/blog/2016/05/11/security-update/

**Comment by davidparsson** [comment]
I've seen this on Jenkins v1.627 (2015/08/30) and v1.32.2 of this plugin as well.

**Comment by mmitche** [comment]
@davidparsson Did that include the security update?

**Comment by davidparsson** [comment]
@mmitche, nope, I doubt that since my Jenkins version was released almost a year before the security update. :smile:

**Comment by mmitche** [comment]
@davidparsson Then it must just be the fix that was made to ghprb to deal with the security issue that broke it.

**Comment by jglick** [comment]
Duplicated parameters links would certainly be a bug, if still reproducible.

_Current build parameters_ from the Parameterized Trigger plugin is not going to work any more. Perhaps it has an option to pass selected environment variables from the upstream build as parameters to the downstream build. If not, you will need to use _Predefined parameters_ with the parameters the downstream build actually needs.

**Comment by gtirloni** [comment]
We've seen this with Jenkins 2.14 and GHPRB 1.32.8 (also tried 1.32.1, 1.31.4, 1.31.1 and 1.30.1).

**Comment by gtirloni** [comment]
Tested with 1.33, same issue.

Besides not checking out the correct revision, it also seems to get confused when there are two PR's opened.

This was for the first unique PR submitted:

```
GitHub pull request #3 of commit 72632197f926fb54a109376a4ed996aea3b6cf7b, no merge conflicts.
...
Checking out Revision 8bf72ee7b68988da0dcf786e75cade81ad98bfac (origin/master)
```

And then the second PR (while the first was still open) had the same hash (72632197f926fb54a109376a4ed996aea3b6cf7b) in the first line.

**Comment by camillake** [comment]
There is no problem with Jenkins ver. 2.17. 
current build parameters would be passed to downstream jobs only if they are defined in "This project is parameterized" block, and then define parameters with the same name as those in upstream job.

**Comment by frekele** [comment]
+1

**Comment by AAverin** [comment]
What the state of this bug now?
Is it working? Was it resolved?

I am unable to make downstream job post any comments and status on github somehow.
No exceptions or errors, just nothing posted

**Comment by benpatterson** [comment]
Hi - I'm helping out with this repo; this issue is queued up. Still don't have a sense of how quickly I can work through the various logged issues but marking this as a higher priority.

**Comment by benpatterson** [comment]
Obviously not working as quickly as I'd like; this is still queued up but I'm happy to check out pull requests if anyone has already sorted out a solution.

**Comment by benpatterson** [comment]
Hi - I have a fix on #439 

Note that, echoing @jglick you'll need to declare the parameters that your downstream job expects. However, with this change, you can tell the Paramterized Trigger Plugin to send the current build parameters, and those will include the ones generated by ghprb with that fix. @juhakuu I'll tag you on it.

**Comment by benpatterson** [comment]
Merged the fix and released. I'm optimistic this will solve the problem and am closing this issue; however, pls let me/us know if you're still seeing issues on the latest (1.33.2).

**Comment by kencoenen** [comment]
@benpatterson 
We have Jenkins 2.19.3 installed and the latest GHPRB 1.33.2 and I'm experiencing problems with the environment variables. Adding an `echo` during build gives empty values...
Let me know if you need more input.
Thanks
