### ISSUE TITLE
Pull requests into different branches share the same build result

### ISSUE THREAD

**Issue by mheidenr** [jenkinsci/ghprb-plugin#353]
The branch `pr-builder-experiment` contains the bad commit.

![network graph](https://cloud.githubusercontent.com/assets/3294195/15603836/5cd1dd18-23fd-11e6-99f1-73e2b9c89dcb.png)

**When the first build fails...**
USER wants to merge 1 commit into `pr-builder-experiment` from `pr-builder-experiment-1`:

```
GitHub pull request #101 of commit 1ba9d30cc3199d682dd8c78dcfdeab3b595d5aa8, no merge conflicts.
[...]
Setting status of 1ba9d30cc3199d682dd8c78dcfdeab3b595d5aa8 to FAILURE with url https://jenkins/job/ci-configuration-pull-request-builder/124/ and message: 'Build finished. '
```

**...the result will be appended to all further pr-builds from this commit**
USER wants to merge 1 commit into `master` from `pr-builder-experiment-1`:

```
GitHub pull request #100 of commit 1ba9d30cc3199d682dd8c78dcfdeab3b595d5aa8, no merge conflicts. 
[...]
Setting status of 1ba9d30cc3199d682dd8c78dcfdeab3b595d5aa8 to SUCCESS with url https://jenkins/job/ci-configuration-pull-request-builder/125/ and message: 'Build finished. '
```

**Comment by benpatterson** [comment]
I would like some additional information on how the job is configured. It looks like it is using the tip of the branch, as opposed to the merge commit (which would show me two different hashes representing separate merge commits for each branch). Unless I am overlooking something...my hypothesis is that the job is set to not-test the merge commit. Therefore when status posts, indeed it's posting the same, because it's the same hash....

**Comment by mheidenr** [comment]
We looked through the configuration and didn't find a suitable configuration option for testing the merge commit. So we expect the plugin to merge the pull requests source branch into the target branch and label the last commit of the source branch via GitHub API. The trouble is the target branch is likely to evolve between labeling and accepting the pull request. So we would be happy if the plugin could push its local merge result to a configurable branch. Another option would be to attach the target branches current head commit to the pull request.

**Comment by bjoernhaeuser** [comment]
I am going through the old issue in this repo. The merge commit is already done by github.

If this issue still persists please reopen. I just need to get a start on the old issues somewhere.
