### ISSUE TITLE
Multiple queued PR builds trigger one build

### ISSUE THREAD

**Issue by oeuftete** [jenkinsci/ghprb-plugin#354]
At some recent point (after 1.31.4, maybe after 1.32.1), if a job building a PR was queued, then a job was triggered for the same job via a different PR, a new build would not be queued.  Instead a single job would be triggered with multiple triggers.  For example:

![jenkins-pr-cut](https://cloud.githubusercontent.com/assets/170730/15618532/8d95c2ec-241c-11e6-8b95-4bb8b2081bac.png)

The resulting build builds only one of the PR's merged codebases.  I'm not sure if which one is even determinate.

**Comment by oeuftete** [comment]
Added as https://issues.jenkins-ci.org/browse/JENKINS-35239.

**Comment by zsolt-biro** [comment]
The issue here is that a recent security update of Jenkins removed some of the build parameters from the build. Because there is no parameter recognized by Jenkins, it thinks that it is a duplicate build with the same parameters. Jenkins will not queue builds with same parameters twice. A detailed description of the problem can be found here:

https://jenkins.io/blog/2016/05/11/security-update/ 


Also, to confirm that this is is your problem, you can go to any build log and click on "Parameters" tab. It will be empty

**Comment by zsolt-biro** [comment]
Duplicate of #352

**Comment by oeuftete** [comment]
@zsolt-biro Thanks, well aware of the security issue and the disaster it has been for users of this plugin.

I guess it's sort of a duplicate of #352 in being caused my the same design issues, although I think this is a more serious problem.  We're not relying on any legacy parameter behaviour to trigger downstream jobs.  The ability to queue different PR builds should just work.

**Comment by riwnodennyk** [comment]
As a workaround I started using https://wiki.jenkins-ci.org/display/JENKINS/Random+String+Parameter+Plugin to parameterize each build with some random string.

**Comment by juhakuu** [comment]
Upgrading to version 1.32.4 of this plugin seems to have fixed this issue for me (with Jenkins version 1.642.1, though).

**Comment by ALeschinsky** [comment]
I ran into the same problem after upgrading Jenkins to 2.38 - even Random String Parameter isn't helping for some reason... it gets injected as a param, but still more pushes do not result in more builds in the queue :( 

![image](https://cloud.githubusercontent.com/assets/2109420/21530010/aaeef816-cd0b-11e6-98ef-25712edb4406.png)

**Comment by ALeschinsky** [comment]
Adding String parameters and then immediately pushing to GitHub again has no effect either :( it seems like parameters of my Jenkins job are ignored - as long as I have one job in the queue, new pushes are ignored every time. I cannot really downgrade... any help would be really appreciated, I'm stuck here. The only option I can see is to write a script that will be accepting a webhook from github and calling a job on jenkins, but that's a lot of work, it used to just work with the `ghprb` plugin... I'm out of ideas, please help.

**Comment by benpatterson** [comment]
@ALeschinsky which version of ghprb are you using? Is your other param defined on the job? Any output from the Jenkins logs?

**Comment by ALeschinsky** [comment]
@benpatterson it's the latest version - once I upgraded Jenkins, I upgraded all plugins to the latest versions. Yes, the other params are defined on the job - I tried the Random String parameter, and I also tried just adding a simple String param manually... no effect, unfortunately...

What output from the Jenkins logs do you mean? I looked under `/var/log/jenkins` but found nothing of interest there... you mean console logs maybe?

**Comment by benpatterson** [comment]
Hi @ALeschinsky 

Hmm, no I meant `/var/log/jenkins`. But I've had a little time to read through this a bit more and I think that we can keep it open. It doesn't have the security-breakage as noise anymore; however, the security requirements may be to blame for this behavior. I'll look into it when I have time in the coming weeks.

**Comment by LinkMJB** [comment]
@riwnodennyk @juhakuu @ALeschinsky I've confirmed that installing the Random String Parameter plugin and adding it as a parameter to the job has no effect in keeping the job separate. Just adds a random parameter 👎

**Comment by Nezz** [comment]
@benpatterson We encountered the same issue and found this report after digging for a day. Pull requests will not have their tests built if there is already one in the queue. This essentially makes the queue functionality of Jenkins entirely useless.

**Comment by gionn** [comment]
Same issue here, we are on jenkins 2.32.1 (current LTS) but the issue was present also on 2.19.4 (previous LTS), tested plugin version both 1.34.0 and 1.33.4.

Reproduce this by opening two new PR that would go to the build queue (because all slaves are occupied); when the queue became free, only one job is started and not both (not started job will remain in pending forever).

The evidence of the problem is that the job contains multiple references to different PRs in the changes section for a single build:

![image](https://cloud.githubusercontent.com/assets/71768/22102825/2689295e-de39-11e6-888b-2b8c0a0db3d3.png)

**Comment by benpatterson** [comment]
This is next on my list folks. It will likely be a couple weeks before I can make headway so if anyone else wants to take time on it, I'd appreciate it. Any additional info as you look at it is welcome, too.

But: I'll take a dive.

**Comment by Nezz** [comment]
Thanks a lot @benpatterson. As a workaround we added more machines, but not everyone can do that :/

**Comment by benpatterson** [comment]
And, does that solve the problem by shortening the time something is on a
queue?

**Comment by Nezz** [comment]
It just makes it less likely for two jobs to get queued. I also disabled the silent period to help when two people trigger builds at the same time. However, the queue is still useless and we still end up with cases like this:
![build](https://cloud.githubusercontent.com/assets/431167/22124322/07ac4c50-de98-11e6-9b11-fcc7148abdd6.png)

**Comment by benpatterson** [comment]
Fix candidate in #473. Cheers to @rubbish for pointing out the appropriate change needed.

**Comment by LinkMJB** [comment]
Any estimate on how quickly it will be released to the Plugin Update Center? :innocent:

**Comment by benpatterson** [comment]
@LinkMJB et al the fix has been pushed (v 1.35.0.) Just depends on your update center's cache, IIRC.

**Comment by LinkMJB** [comment]
@benpatterson: According to https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin 1.34 is the latest release atm... running "check now" in the Jenkins update center doesn't discover any new versions available. I saw CloudBees's Jenkins build the plugin successfully a couple of times at least:  (https://jenkins.ci.cloudbees.com/job/plugins/job/ghprb-plugin/971/) and (https://jenkins.ci.cloudbees.com/job/plugins/job/ghprb-plugin/973/). From what I can tell, the release still needs to be pushed to jenkins-ci.org: https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org

**Comment by benpatterson** [comment]
Matthew

I'm not familiar with that side of Cloudbees infrastructure. I assume there
is some syncing of artifacts that happens in batches.

Either way it looks like the latest version is available according to the
wiki page. I'm not at my desk right now but indications are that you should
be able to get the latest this morning.

**Comment by benpatterson** [comment]
Oh and to clarify I did follow the process you pointed out (and have been
doing so). No worries on that.

**Comment by LinkMJB** [comment]
Thanks @benpatterson! Yeah there must be a nightly Cloudbees job or something that accepts plugin updates into the global Jenkins Update Centre.

**Comment by benpatterson** [comment]
Closing this as resolved.
