### ISSUE TITLE
Trigger Pharse becomes garbled

### ISSUE THREAD

**Issue by nitinpadalia** [jenkinsci/ghprb-plugin#358]
Sometimes we see that Trigger Phrase get garbled having character /Q and /E attached to it, hence trigger stops working.

In which scenario this could happen and how to avoid this?

**Comment by benpatterson** [comment]
Hi, I'm wondering if you could provide more information. Where does it get garbled? How does it impact builds?

**Comment by bjoernhaeuser** [comment]
I am closing this for now. If it still happens please reopen.
