### ISSUE TITLE
Changelog Updates

### ISSUE THREAD

**Issue by bramwelt** [jenkinsci/ghprb-plugin#360]
The changelog has not been updated since 1.30.2.

**Comment by luis-silva** [comment]
+1. It's not ideal to guess the changes made by the developer by looking at the commits.

**Comment by petacz** [comment]
+1

**Comment by jasonaowen** [comment]
If you're going to use GitHub to manage the change log, it might be better to put the changelog entries in the git tag or in the corresponding GitHub release, and then the wiki link can just point to the [list of releases](https://github.com/jenkinsci/ghprb-plugin/releases).

**Comment by benpatterson** [comment]
Addressing with #424
