### ISSUE TITLE
PR checks status is not updated by manually triggered job

### ISSUE THREAD

**Issue by mazimkhan** [jenkinsci/ghprb-plugin#370]
When triggering a GHPRB job via a pipeline job build step the PR status does not get updated.

**Comment by benpatterson** [comment]
I'm wondering if you could describe your pipeline. Why would a ghprb job be somewhere in the middle of a pipeline? Does it serve multiple purposes? Do you expect the ghprb job to update a commit status on GitHub?

**Comment by benpatterson** [comment]
Closing as abandoned/needs info.
