### ISSUE TITLE
[Jenkins-2.11] The "sha1, ghprbActual*****"was not found in Build Parameters but in Environment variables.

### ISSUE THREAD

**Issue by tom-aa** [jenkinsci/ghprb-plugin#371]
Jenkins Version: 2.11(think may related to 2.0+)
Ghprb Plugin Version: 1.32.6

Build Parameters:
<img width="437" alt="screen shot 2016-06-28 at 10 42 04 am" src="https://cloud.githubusercontent.com/assets/5906756/16402230/8941dffe-3d1d-11e6-99e6-b807c5d7f3ba.png">

Build Environment Variables:
<img width="438" alt="screen shot 2016-06-28 at 10 42 27 am" src="https://cloud.githubusercontent.com/assets/5906756/16402233/8d6ccd1e-3d1d-11e6-8bfb-79c2f4222df2.png">

**Comment by tom-aa** [comment]
Works fine on old version:
jenkins: 1.647
ghprb: 1.31.1

**Comment by tom-aa** [comment]
issues reproduced on 
Jenkins ver. 1.651.3
ghprb: 1.32.6

**Comment by zelonght** [comment]
@tom-aa Please try 1.32.8 ?

**Comment by jameslaspada** [comment]
I had just experienced the same issue when upgrading to Jenkins 2.12. The log was stating "Skipped parameter `sha1` as it is undefined on JOBNAME". 

You can either explicitly set the sha1 as a parameter in the PR job, or if you just upgrade the ghprb to 1.32.8 should work.  👍

**Comment by firon** [comment]
I'm running 1.33.0 but I'm still seeing a lot of spam in the logs about the ghprb params being skipped?
e.g.
WARNING: Skipped parameter `sha1` as it is undefined
Skipped parameter `ghprbActualCommit`

Do we have to define *all* the ghprb parameters in our job to use any of them?

**Comment by Puneeth-n** [comment]
Same issue here.

```
jenkins version: 2.7.1
ghprb version: 1.33.1
```

**Comment by benpatterson** [comment]
Looks like #352

**Comment by dalejoel** [comment]
Same issue 
jenkins: 2.7.4
ghprb: 1.33.1
