### ISSUE TITLE
Can't create multiple hooks

### ISSUE THREAD

**Issue by prachikhadke** [jenkinsci/ghprb-plugin#374]
Went through the ghprb-plugin documentation and code. Played with Jenkins. Only available web-hook  endpoint is `/ghprbhook`. The changelog for version 1.8 says that 2 hooks are possible, but I don't understand how. Looking at the code, the value of  `/ghprbhook` is hardcoded as `GhprbRootAction.URL`.

**Comment by prachikhadke** [comment]
I was able to use the same webhook for my multiple repos. so closing this.

**Comment by DotComing** [comment]
@prachikhadke I wonder how you did this, I try to use github_webhook to handle both github and ghprb, but failed.

**Comment by prachikhadke** [comment]
@DotComing You gotta use the string `ghprbhook` instead of `github_webhook`. Crazy right that you can't use a custom name right? but it's documented somewhere in their wiki too - to use `ghprbhook`.

**Comment by DotComing** [comment]
Thanks @prachikhadke, I am trying to solve this.
