### ISSUE TITLE
How to set up shared secret for webhook?

### ISSUE THREAD

**Issue by hughperkins** [jenkinsci/ghprb-plugin#378]
Hi,

I filled in a value for 'shared secret' in the '/configure' page of my jenkins, and put the same value for the 'secret' in the webhook token, but I just get 403 when I test the webhook from github:

![webhookfail](https://cloud.githubusercontent.com/assets/123560/16608286/cb84e9a0-437c-11e6-8121-67f269628ba4.png)

I tried things like:
- shut jenkins down, remove the org.githubAuth.org.secret node from org.jenkinsci.plugins.ghprb.GhprbTrigger.xml , bounce jenkins
- shut jenkins down, set the org.githubAuth.org.secret node to blank from org.jenkinsci.plugins.ghprb.GhprbTrigger.xml , bounce jenkins
- shut jenkins down, set the org.githubAuth.org.secret node to the same secret I put in github from org.jenkinsci.plugins.ghprb.GhprbTrigger.xml , bounce jenkins
... but results were identical, when testing the webhook from github.

Thoughts?

**Comment by hughperkins** [comment]
Figured it out, thanks to http://stackoverflow.com/questions/7427557/jenkins-and-github-webhook-http-403/7431548#7431548  Cos I need to auth as a user too, and have a secret.

![successfulhook](https://cloud.githubusercontent.com/assets/123560/16614390/8cb961d4-43a3-11e6-8a97-6f4082974baf.png)

**Comment by ChaiBapchya** [comment]
what is meant by auth as a user?
I'm currently unable to use my shared secret...
