### ISSUE TITLE
Pushing new commit to existing PR does not stop previous build

### ISSUE THREAD

**Issue by slefrancois** [jenkinsci/ghprb-plugin#379]
We are using Github hooks to trigger builds. It seems that when pushing a new commit to a PR that already has a Jenkins build running, it starts a new build as expected, but does not automatically close the old build on the previous commit.

**Comment by gharcombe-minson** [comment]
In your job configuration, under `Trigger Setup`, you can add `Cancel Build on Update`, which will terminate the job.

**Comment by slefrancois** [comment]
Thanks, seems I missed that option.

**Comment by aballano** [comment]
@gharcombe-minson Hi there, is there any way to configure that using the DSL plugin? Otherwise, won't that config be overriden by the DSL script?

**Comment by ggrell** [comment]
Is there any place to check why this wouldn't be working? Our Jenkins PR job has the "Cancel build on update" added under trigger setup, but no matter how many subsequent pushes happens on the GH PR, it keeps adding new jobs and old ones stay in the queue. Don't know if it matters that it's Enterprise GH.

**Comment by perguth** [comment]
Because it's so incredibly well hidden:

**`Cancel Build on Update`**

- At the job level, it is found under Trigger Setup. Select Cancel build on update.
- In configure system, it is found under GitHub Pull Request Builder -> Application Setup -> Cancel build on update

Thanks https://github.com/janinko/ghprb/issues/440#issuecomment-248346848

**Comment by 16slowly** [comment]
when I add this selection "Cancel Build on Update", it still dosen't cancel the previous build @perguth , it seem to about with https://jenkins.io/security/advisory/2018-03-26/#SECURITY-261

**Comment by forpix** [comment]
is it possible to restrict the build for pull request.

**Comment by bjoernhaeuser** [comment]
@forpix please create a new Issue which detailly explains your problem :)

**Comment by tulku** [comment]
Is there a way to achieve this (cancel builds when new things are pushed to a branch / PR) when using the Pipeline Multibranch Plugin?

**Comment by nouiz** [comment]
When you make the PR, I think you can put something like this in the
description;
[skip ci]

I didn't use it myself, but I read that some times ago in the documentation.

**Comment by unphased** [comment]
We have the Cancel Build on Update feature working great, but I was curious to know if this will behave properly. Let's say two developers working on two different branches and PRs are rapidly pushing and updating their PRs. Will it correctly only abort the intended stale jobs?

**Comment by peter-formlogic** [comment]
For those looking to get this working with declarative pipelines (stopping older builds when new commits are pushed), this appears to be working for us https://issues.jenkins.io/browse/JENKINS-43353:

```
pipeline {
    options {
        disableConcurrentBuilds(abortPrevious: true)
    }
    ... 
}
```
