### ISSUE TITLE
Pull Requests do not trigger builds on Jenkins 2.7.1 LTS and plugin 1.32.8

### ISSUE THREAD

**Issue by boonware** [jenkinsci/ghprb-plugin#380]
Upgraded Jenkins to version 2.7.1 LTS and GitHub Pull Request Builder to version 1.32.8. Jenkins jobs are no longer triggering automatically on pull requests when configured to do so. I can only get Jenkins to build PRs by relying upon the crontab schedule, which will poll and eventually see the pending PRs and build them.

Nothing unusual in the Jenkins log file. Is there any way I can enable more detailed logging for this plugin?

Please advise as this is a **major issue**.

**Comment by benpatterson** [comment]
Possibly related to #270

**Comment by benpatterson** [comment]
Hi - I'm helping with this repo now. I realize this is an older issue but I'd be curious for more information. I have a local environment set up and have been able to start builds via the webhook using 2.7.3 & 1.33.1 (the latest ghprb build available).

**Comment by benpatterson** [comment]
Closing as waiting on author. I've not been able to reproduce this problem.
