### ISSUE TITLE
"Unable to connect to GitHub anonymously" error when attempting to trigger build

### ISSUE THREAD

**Issue by hardboiled** [jenkinsci/ghprb-plugin#388]
Every time I try to trigger builds via pull request comments, I see the request going successfully out from github to my webhook.

However, even though I'm getting a 200 every time when I trigger the callback for pull request builder, I found that jenkins wasn't triggering the build. Upon further investigation, I looked in /var/log/jenkins/jenkins.log and found that ghprb prints out the event, but doesn't do anything with it. This happens for comments & pull requests.

```
INFO: Checking PR #2,108 for hardboiled/my-test-repo
```

I have configured jenkins with valid API Keys and confirmed that it can access my repo from the "Test Permissions to a Repository" section. It says "User has access to: Admin, Push, Pull."

What else can I do to debug the issue? My colleagues don't seem to have this problem, and I've gone over their setup with a fine-toothed comb. Doesn't seem to be different than mine. I even downgraded from 1.33.0 to 1.30.4 to more accurately replicate their setup. Nothing works.

**Comment by hardboiled** [comment]
An update: I was able to successfully get pull requests to build if I disable the *Use github hooks for build triggering* option and use polling instead. I don't know why there is a disparity. I still see the requests from the github hooks getting logged in jenkins.

**Comment by benpatterson** [comment]
I realize this is months later, but I'd try using the Jenkins logger with a finer-grained log in order to troubleshoot further. We do have a related issue wherein the API token being tested doesn't seem to be checking all the appropriate permissions.

**Comment by bjoernhaeuser** [comment]
Closing this for now because of age.
