### ISSUE TITLE
Custom docker command for nvidia-docker

### ISSUE THREAD

**Issue by slefrancois** [jenkinsci/ghprb-plugin#399]
For using docker with GPUs, [nvidia provides a wrapper](https://github.com/NVIDIA/nvidia-docker) that finds the device options for graphics cards and passes them to docker as arguments. This can be done by calling "nvidia-docker" instead of "docker" when launching the container.

I cannot find an option in ghprb to change the docker call, could this be added?

Alternatively, the device parameters --volume-driver={} --volume={} --device={}, could be passed manually, but I can't find where to do so in the plugin.

**Comment by benpatterson** [comment]
I'm ramping up on this plugin...when does ghprb make a docker call??

**Comment by slefrancois** [comment]
Looking back, this issue belongs in jenkins/docker-plugin, [I moved the issue there](https://github.com/jenkinsci/docker-plugin/issues/468).
