### ISSUE TITLE
Broken PR link

### ISSUE THREAD

**Issue by riuvshin** [jenkinsci/ghprb-plugin#405]
Hi guys I've just updated jenkins and ghprb plugin to latest versions and due to some reason links to PRs are broken on my jenkins.
![ghprb](https://cloud.githubusercontent.com/assets/1636732/18204459/92196be2-7125-11e6-9de4-8661467d9316.png)
Is it known issue?

**Comment by sam0delkin** [comment]
@riuvshin try "Configure Jenkins" -> "Configure Global Security" -> and change "Markup Formatter" to "Safe HTML"

**Comment by riuvshin** [comment]
@sam0delkin Thanks a lot!
