### ISSUE TITLE
Update commit status during build URL based on build status 

### ISSUE THREAD

**Issue by sam0delkin** [jenkinsci/ghprb-plugin#408]
Hi, i use jenkins + ghprb to build PRs of my project so that each PR is a builded web aplication, accessible to test the new code.

So, i have some questions:
1) Currently, during build, my PR commit status message is changed, based on build status. But URL can not be configured conditionally. So, what i want: if build is succeed, the status URL should link to my builded application (e.g. pr1111.mydomain.com). And if build is not succeed (still building or failed), it should link to build status URL (as usual). I tried to send status update, using CURL just to github API in `after build trigger`. But ghprb is updating status _after_ `after build trigger`.
2) Is it possible to run some jenkins build after PR is merged? In my example, i will need to remove virtual host for the application, it's working directory, database, etc.

Thanks!

**Comment by benpatterson** [comment]
I think this can be addressed using the downstream job pattern that's described in the README.

**Comment by bjoernhaeuser** [comment]
Will close this for now.
