### ISSUE TITLE
Does the ghprb-plugin on the Jenkins plugin archive site built from github repo: jenkinsci/ghprb-plugin or janinko/ghprb-plugin?

### ISSUE THREAD

**Issue by indrgun** [jenkinsci/ghprb-plugin#409]
Which github repo is the official src code that builds the plugin on http://updates.jenkins-ci.org/download/plugins/ghprb/?

The Wiki page, https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin, is linked to this jenkinci/ghrpb-plugin git repo.

However I see more issues were submitted on janinko/ghprb git repo.    If I run into issues on latest plugin version, where should I submit my issue and/or comment on an existing open issue?

Thank you

**Comment by benpatterson** [comment]
Hi @indrgun this is the correct repo. We are working on clearing up the confusion with the other repo presently, but I don't know how quickly that will get resolved. Cheers.
