### ISSUE TITLE
Cancel a PR test job in queue if more commits are made on the source branch and new PR test job is triggered.

### ISSUE THREAD

**Issue by sam1111** [jenkinsci/ghprb-plugin#411]
Hi,

Is it possible to achieve the following:
1. I have a PR test job triggered as soon as a PR is created from a source branch (say hotfix) to target branch (say main)
2. Now lets say I make a commit to hotfix on this another PR test job is triggred and it is in the queue.
3. I realize that ohh I missed this in my previous commit so I make another commit on the hotfix branch. Now what happens is that another PR test job is triggered and placed on the queue. 

Is it possible somehow to cancel the PR test job created in step 2 automatically when step 3 is executed?

**Comment by grdryn** [comment]
I might be misunderstanding either what the question is or what the option does, but is this already provided by the "cancel build on update" trigger setup option?

![ghprb-cancel-on-update](https://cloud.githubusercontent.com/assets/442386/19389179/cee0e01c-921a-11e6-9d19-7be6f510cd4b.png)

**Comment by benpatterson** [comment]
Re-reading this I agree with @grdryn; I think you just want to use to use that option in the trigger setup section of the plugin configuration. Closing this but you can re-open if there's a misunderstanding.
