### ISSUE TITLE
Job DSL not support for buildStatus

### ISSUE THREAD

**Issue by bphalak** [jenkinsci/ghprb-plugin#417]
Hi all,

I have used same example given in README but not able to create Job for GHPRB.
Getting below error 

_No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.buildStatus() is applicable for argument types: (script$_run_closure1_closure3_closure6_closure7_closure9) values:_ 

buildStatus {
completedStatus('SUCCESS', 'There were no errors, go have a cup of coffee...')
completedStatus('FAILURE', 'There were errors, for info, please see...')
completedStatus('ERROR', 'There was an error in the infrastructure, please contact...')
}

Can anyone please help me thanks,

**Comment by benpatterson** [comment]
I'm guessing it's a syntax error is all. Would you mind posting your script for the whole job?

**Comment by benpatterson** [comment]
Hi @bphalak I vaguely recall running into this after installing the plugin, but before restarting Jenkins. It may go away after you restart and it re-loads the plugins.

**Comment by davorbonaci** [comment]
I'm seeing this issue as well. @bphalak, were you able to figure this out?

`commitStatus` seems to work for me perfectly. Is it possible that `buildStatus` was added in a later release than other extensions, e.g. `commitStatus`?

@benpatterson, I'd be happy to post my script, but I don't think it's a simple syntax error.

**Comment by davorbonaci** [comment]
It seems this functionality was added in pull request #404 on September 1st. The last release (1.33.1) was completed on August 3rd. This should explain the issue.

Any ETA for the next release? I'd love to be able to use this new DSL functionality. Thanks!

**Comment by bphalak** [comment]
@benpatterson @davorbonaci 

please refer below link its resolved my problem
http://stackoverflow.com/questions/39704959/github-pull-request-builder-dsl-groovy-syntax-not-working

Thanks

**Comment by davorbonaci** [comment]
Thanks @bphalak; that's indeed a workaround. I'll give it a try.

My question on the next release for a proper solution still stands, however.

**Comment by benpatterson** [comment]
@mmitche After releasing the latest, I'm wondering if you think this is an issue still?

**Comment by mmitche** [comment]
I'm running a custom version, but this should have been fixed in #404.  @bphalak Can you confirm?

**Comment by chenrui333** [comment]
I have `buildStatus()` issue with the ghprb `1.33.1`, my Jenkins ver is `2.30`, I am going to test the latest one today, which is `1.33.4`.

**Comment by chenrui333** [comment]
The latest version works for me.

**Comment by bjoernhaeuser** [comment]
Closing this for now. If still happens please leave a comment and we will reopen! 

Thank you!
