### ISSUE TITLE
How "Build Message" post?

### ISSUE THREAD

**Issue by kakakakakku** [jenkinsci/ghprb-plugin#420]
Hi, I'm using ghprb v1.33.1 (Latest Release) with jenkins 2.22.

Build settings are almost finished.
- New PR trigger build -> ok
- keyword "test this please" trigger build -> ok

But, "Build Message" by Bot does not post to PR, like "SUCCESS", "ERROR", "FAILURE".

What do I need additional settings?

Maybe, my credential settings are correct. Because test post works good.

![settings](https://cloud.githubusercontent.com/assets/1573290/18859467/4e4022c4-84af-11e6-801f-2b8edf264da6.png)

 I don't know what to do 😓 
Thank you!!!

**Comment by benpatterson** [comment]
Any info from the Jenkins logs?

**Comment by kakakakakku** [comment]
@benpatterson 
Thank you for your response 👍 

"Build logs" and "Jenkins logs" are here.
Some values are masked.

## Build logs

```
GitHub pull request #243 of commit 5cd48cdb92de97f9a0a8bb6ef6c1942baaa267e3, no merge conflicts.

[snip]

Setting status of 5cd48cdb92de97f9a0a8bb6ef6c1942baaa267e3 to SUCCESS with url http://example.com/job/xxx/21/ and message: 'Build finished. '
Finished: SUCCESS
```

## Jenkins logs

Many of "WARNING: Skipped parameter" are written.

```
Sep 30, 2016 10:10:01 AM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #243 was updated/initialized on org/repo at 9/30/16 10:09 AM by Yoshiaki Yoshida (PR update)

[snip]

Sep 30, 2016 10:11:09 AM hudson.model.Run execute
INFO: xxx #21 main build action completed: SUCCESS
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `sha1` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `ghprbActualCommit` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `ghprbActualCommitAuthor` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `ghprbActualCommitAuthorEmail` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `ghprbAuthorRepoGitUrl` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter
WARNING: Skipped parameter `ghprbTriggerAuthor` as it is undefined on `xxx`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
Sep 30, 2016 10:11:09 AM hudson.model.ParametersAction filter

[snip]
```

Other logs are needed?
Thanks.

**Comment by kakakakakku** [comment]
Anyone can help?

**Comment by benpatterson** [comment]
Hi @kakakakakku 

I'd like to help, but think I need more information. Could you give me some steps or configuration settings to use, where I could reproduce the problem on a local instance of Jenkins?

**Comment by kakakakakku** [comment]
@benpatterson 

Thank you for your supports!
I wish my issue solve.

>Could you give me some steps or configuration settings to use, where I could reproduce the problem on a local instance of Jenkins?

OK, here are my setup steps.
Is it enough?
There steps can reproduce also on Vagrant.

# Provisions

At first, I installed Jenkins using by Chef with community cookbook.

* https://github.com/chef-cookbooks/jenkins
* https://supermarket.chef.io/cookbooks/jenkins/versions/2.6.0

And I updated `/etc/passwd` jenkins entry from `/bin/false` to `/bin/bash`.

# Jenkins Setups

Then, I installed some plugins with "Install suggested plugins" menu.
So, some plugins are automatically installed without ghprb.

Next, I installed "GitHub Pull Request Builder" manually.

# Manage Jenkins -> Configure System

* GitHub Pull Request Builder
    * GitHub Auth
        * Try "Test adding comment to Pull Request", then it's ok!

# Jobs

I created Jenkins Job named "ci" with FreeStyle.

* General
    * GitHub project
        * https://github.com/${org}/${repo}
* Source Code
    * Git
        * Repositories
            * git@github.com:#{org}/${repo}.git
        * Branches
            * ${sha1}
* Build Trigger
    * GitHub Pull Request Builder

It's all!

**Comment by kakakakakku** [comment]
Thanks !
I tried setting `https` url, but it does not work for me.

Job is triggered automatically by PR.
But build comment in PR done not posted.

**Comment by kakakakakku** [comment]
I'm still does not work.

Which version of ghprb is work good?
My server spec is bellow.

>Hi, I'm using ghprb v1.33.1 (Latest Release) with jenkins 2.22.

**Comment by benpatterson** [comment]
@kakakakakku We solved an issue on the latest release that might have been manifesting itself in this way. Could you take the latest (1.33.2) and see if you are still having problems?

**Comment by kakakakakku** [comment]
@benpatterson 
Hi !

Ohhhh, I updated v1.33.2 and restarted Jenkins, but still does not work for me 💦 💦 💦 
Any settings are required ? 😢 

# Case of "test is ok"

Auto comment by bot does not exist.

This is a part of console_log.

>Setting status of 5cd48cdb92de97f9a0a8bb6ef6c1942baaa267e3 to SUCCESS with url http://example.com/job/test/52/ and message: 'Build finished. '
Finished: SUCCESS

![jenkins_success](https://cloud.githubusercontent.com/assets/1573290/20657343/792e68c0-b578-11e6-95a5-c23f264b6b84.png)

# Case of "test is ng"

Auto comment by bot does not exist.

This is a part of console_log.

>Setting status of 3968a5bcad8c76b8720f63d1d0aa5285b5201fa3 to FAILURE with url http://example.com/job/test/53/ and message: 'Build finished. '
Finished: FAILURE

![jenkins_faild](https://cloud.githubusercontent.com/assets/1573290/20657346/7ce054d8-b578-11e6-83fc-662742e31d95.png)

# test post works good

Still, test post works good.

![settings](https://cloud.githubusercontent.com/assets/1573290/18859467/4e4022c4-84af-11e6-801f-2b8edf264da6.png)

**Comment by Sanne** [comment]
Hi @kakakakakku 

When you say:

> But, "Build Message" by Bot does not post to PR, like "SUCCESS", "ERROR", "FAILURE".

what do you expect exactly? The plugin will NOT comment by default on the PR.

The status is reported by the messages "All checks have passed" or "All checks have failed", like you are having in your screenshots.

**Comment by kakakakakku** [comment]
Sorry for late comment.
I understand for feature of this plugin.

>The plugin will NOT comment by default on the PR.

Thanks, and close it !
