### ISSUE TITLE
Does not compile properly upon opening pull requests 

### ISSUE THREAD

**Issue by danyaljj** [jenkinsci/ghprb-plugin#421]
This is the message I am getting whenever someone opens a pull request: 

<img width="994" alt="screen shot 2016-09-29 at 4 40 21 pm" src="https://cloud.githubusercontent.com/assets/2441454/18973417/034b42e8-8663-11e6-8ed0-8b7de3bf0a92.png">

And here are my git settings which I have set based on the [readme file](https://github.com/jenkinsci/ghprb-plugin#creating-a-job). 
<img width="972" alt="screen shot 2016-09-29 at 4 40 49 pm" src="https://cloud.githubusercontent.com/assets/2441454/18973420/05a700a4-8663-11e6-9d3b-ef7ac3953740.png">

Any ideas where I am going wrong?

**Comment by benpatterson** [comment]
Hmm, could you try just `+refs/pull/*:refs/remotes/origin/pr/*` and see if that helps?

Also I assume you looked at your build's environment variables and confirmed that the `sha1` that produced did in fact exist at the time? (Related: is this happening all the time, or intermittently?)

**Comment by danyaljj** [comment]
> Hmm, could you try just +refs/pull/*:refs/remotes/origin/pr/* and see if that helps?

 Will try. 

> Also I assume you looked at your build's environment variables and confirmed that the sha1 that produced did in fact exist at the time? 

em ... what's the easiest way to do that? 

>  is this happening all the time, or intermittently? 

I think it happens all the time (but not 100% sure).

**Comment by benpatterson** [comment]
You can check your job's "Parameters" and "Environment Variables" for that particular build-run.

**Comment by benpatterson** [comment]
Revisiting this: how are you kicking off the job? I think this configuration would only work if you were configured to use the webhook.

**Comment by danyaljj** [comment]
Seems like it got resolved for reasons that I don't understand (yet). Will open it if it comes up again.

**Comment by zarathon** [comment]
same problem, but not woking yet
![screenshot from 2016-11-09 16-56-51](https://cloud.githubusercontent.com/assets/930791/20152599/a3c66a54-a69d-11e6-967e-3fcd66362911.png)

**Comment by benpatterson** [comment]
We did see a problem similar to this related to a bug that was fixed. Please take the latest and see if your problem goes away.
