### ISSUE TITLE
Is not able to fetch repo from API when `GitHub project` is copy-pasted from clone URL

### ISSUE THREAD

**Issue by allardhoeve** [jenkinsci/ghprb-plugin#423]
I just updated to the latest verion of the plugin. The project had a `Github project` url that was copy-pasted from the Github project page. That URL is normally `https://github.com/project/project.git` (found under `Clone or download`).

The URL that the plugin expects has no `.git` suffix. I suppose it just removes `https://github.com/` from the given URL and preprends the API url. But I had to find the error in the logs, so that is not very user-friendly.

Maybe the plugin could remove the `.git` suffix if found, because it is a common pattern?

Thanks

**Comment by benpatterson** [comment]
@allardhoeve the github project appears in a couple of configuration fields. Which field in particular is this for?

**Comment by allardhoeve** [comment]
@benpatterson: it is the first github project url field in the config screen. The input has `name="_.projectUrlStr"`. It's under General, then under the checked `GitHub project` option, then `Project url`.

The plugin is unable to ping back to Github, because the parsing is not intelligent enough. Fixable by removing the `.git`, but still.

**Comment by bjoernhaeuser** [comment]
I will close this for now.
