### ISSUE TITLE
How to get the origin string of trigger phrase ?

### ISSUE THREAD

**Issue by jubel-han** [jenkinsci/ghprb-plugin#435]
Is there a way we can get string of trigger `phrase` as the environment variable ?

like those:
```
ghprbActualCommit
ghprbActualCommitAuthor
ghprbActualCommitAuthorEmail
ghprbPullDescription
ghprbPullId
ghprbPullLink
ghprbPullTitle
ghprbSourceBranch
ghprbTargetBranch
sha1
```
in my case, we need use this phrase control several build flow for the next steps.

**Comment by jubel-han** [comment]
Found `ghprbCommentBody` from https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbAdditionalParameterEnvironmentContributor.java#L33-L33 
It works for me!

**Comment by djwgit** [comment]
better to add this to doc.
