### ISSUE TITLE
Provide option for configurable webhook base URL

### ISSUE THREAD

**Issue by DavidWittman** [jenkinsci/ghprb-plugin#437]
When auto-managing webhooks, this plugin uses the root Jenkins URL as the base for the payload URL, but this is not always the case. Jenkins deployments often have separate entry points for external and internal traffic. The internal traffic comes from users within a corporate network and is how a majority of users reach Jenkins, and the external URL is accessible from the Internet, but whitelisted only for integrations like Github.

Providing a configuration option to specify a webhook base URL which is separate from the global Jenkins Root URL would solve this issue.

**Comment by bjoernhaeuser** [comment]
You can override the URL in the general settings by providing `Jenkins URL override`.

If this does not solve the problem for you please reopen the issue.
