### ISSUE TITLE
Need Help ? Jenkins sometimes unable to pickup latest job from anoter job 

### ISSUE THREAD

**Issue by rautdeepak55** [jenkinsci/ghprb-plugin#440]
Copied 1 artifact from "Project/Job1" build number 13
Where as Job1 has 14 Number current build so 
Jenkins cannot pickup 14 number job it happens sometimes 
Can any one help to sort this issue

**Comment by benpatterson** [comment]
Hi - Unfortunately there's not enough info in this issue to help out. I'm going to close it for now, but if you still need help, please provide more detail like job configuration and set of steps to take in order to reproduce the issue.
