### ISSUE TITLE
1.33.2: builds are not triggered

### ISSUE THREAD

**Issue by pascalw** [jenkinsci/ghprb-plugin#442]
Hi,

I updated to 1.33.2 today and noticed that my PR's were not being built anymore.
Logs looked fine:

```
<snip>
Retest accepted and user GHUser@59937e22[<snip>] is whitelisted
Dec 01, 2016 8:30:50 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running the build
Dec 01, 2016 8:30:50 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
PR is not null, checking if mergable
Dec 01, 2016 8:30:50 PM FINEST org.jenkinsci.plugins.ghprb.GhprbPullRequest
Running build...
```

But no actual builds were triggered, nor was the status on GitHub updated in any way.
Downgraded to 1.33.1 and my builds were working again.

**Comment by benpatterson** [comment]
@pascalw were you attempting to start builds with a comment? I'm wondering if you were encountering issue 441.

**Comment by pascalw** [comment]
Hi @benpatterson no initially I wasn't. When I noticed the build wasn't triggered when I created the PR I commented, which also didn't trigger the build.

I also didn't see that 404 mentioned in #441.

**Comment by pascalw** [comment]
@benpatterson after checking my logs again I do see the same exception raised. I'll close this issue and add a comment to the other one. Sorry for the confusion.

**Comment by benpatterson** [comment]
Right on. Thank you.
