### ISSUE TITLE
[Question] How to run a job only when sub module is part of the pull request.

### ISSUE THREAD

**Issue by petromir** [jenkinsci/ghprb-plugin#445]
I couldn't find the answer anywhere else.

We have a Git repository with the following structure:
```
backend
  addressbook
    src
    build.gradle
  common
    src
    build.gradle
  security
    src
    build.gradle
  users
    src
    build.gradle
build.gradle
settings.gradle
```
which translates to single repo with many independent projects and two used by all (common & security)

I have separate jobs for each of the main projects (e.g `addressbook` and `users`) that run when a pull request is submitted. The issues is that if a pull request is done in `addressbook` subdirectory then the job for `users` is also started. 

What should I set, so only the relevant jobs will be started?

Here are the job git settings for `addressbook`

![git](https://cloud.githubusercontent.com/assets/1680908/20839017/970f231e-b8b3-11e6-83f9-a8a8d3d53698.png)

**Comment by petromir** [comment]
Someone?

**Comment by benpatterson** [comment]
@petromir sorry to neglect you here. I personally don't know the answer to the question and don't see myself taking a closer look until after chewing through other items on the backlog... I'm going to label this as 'needs verification' for now.

**Comment by bjoernhaeuser** [comment]
@petromir 
You can set the regions for every pull request trigger. We are using that functionality to have different jobs inside the same repository.

If this does not solve the problem for you please reopen.
