### ISSUE TITLE
Disable whitelist?

### ISSUE THREAD

**Issue by JaredReady** [jenkinsci/ghprb-plugin#446]
We use Jenkins internally, we have people approved on our local GitHub instance, so there's no need to whitelist people in our case. Is there a way to disable the whitelist so that all PRs are merged regardless of who opened the PR?

Thanks

**Comment by benpatterson** [comment]
Jared

There is a checkbox in the job config that will just build everything.

You can also set an org on a whitelist, if it's a large group you can set
on Github.

**Comment by JaredReady** [comment]
Ah I see it now. It's the `Build every pull request automatically without asking (Dangerous!)` Advanced option for future people wondering.

Thanks @benpatterson!
