### ISSUE TITLE
 [Exception] Could not build due to pharse on github PR

### ISSUE THREAD

**Issue by regardfs** [jenkinsci/ghprb-plugin#448]
Need help:
When I leave a message "ok to test" on my PR(already set triggerPhrase('^ok to test$)), It could not trigger build but only below message print:
Dec 05, 2016 12:01:46 PM org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
INFO: Checking issue comment 'ok to test for web' for repo myrepo
Dec 05, 2016 12:01:46 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handleComment
INFO: Checking comment on PR #4,810 for job pull-request-test-builder-identify
Dec 05, 2016 12:01:46 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #4,810 was updated/initialized on myrepo at 12/5/16 12:01 PM by null (comment)
Dec 05, 2016 12:01:46 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handleComment
INFO: Checking comment on PR #4,810 for job genric-ft-pull-request
Dec 05, 2016 12:01:46 PM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #4,810 was updated/initialized on myrepo at 12/5/16 12:01 PM by null (comment)
Need help ASAP. T T

**Comment by benpatterson** [comment]
Did you try loosening the regex with wildcards? As written it wouldn't
allow return characters, etc

**Comment by regardfs** [comment]
Hi, @benpatterson, I just try with "ok to test" and ".*" ,  both print the same message as above.
I think it is not concern with regex.

**Comment by ilovezfs** [comment]
I think this may be the same as https://github.com/jenkinsci/ghprb-plugin/issues/450.

**Comment by ilovezfs** [comment]
@regardfs can you test 1.33.1 and see if the problem goes away?

**Comment by ilovezfs** [comment]
@regardfs do you have a "shared secret" set?

**Comment by benpatterson** [comment]
I haven't been able to reproduce this issue. Could you make sure that the user making the comment is an admin? That's my best guess at this point.

**Comment by regardfs** [comment]
Hi, I had never reproduce this problem again. It worked fine now just after a jenkins restart.Thanks u a lot for your guys help.@benpatterson , @ilovezfs

**Comment by benpatterson** [comment]
OK good to hear @regardfs
