### ISSUE TITLE
Not able to build PR

### ISSUE THREAD

**Issue by altimea** [jenkinsci/ghprb-plugin#459]
Hi

I know about the security bug that affected Jenkins recently. If I understand correctly, latest versions of this plugins solved that.

I have latest jenkins and this plugin's version, but I can't build any PR. I get:

```
 > git rev-parse origin/PR-3^{commit} # timeout=10
 > git rev-parse origin1/PR-3^{commit} # timeout=10
 > git rev-parse PR-3^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

I am using also the Github Plugin, if it is relevant.

Jenkins: 2.32.1
ghprb-plugin: 1.33.4
GitHub API Plugin: 1.82

**Comment by benpatterson** [comment]
This appears to be a configuration issue with respect to github permissions.

**Comment by bjoernhaeuser** [comment]
Closing this for now. If still happens please provide current config so we can help you resolve this!

Thanks!
