### ISSUE TITLE
Provide option to run separate PR builds for each PR

### ISSUE THREAD

**Issue by LinkMJB** [jenkinsci/ghprb-plugin#460]
The default behavior appears to squash/merge PR builds into a single job when a PR build is in the job queue. This creates difficulty tracking and communicating build status and success/failure messages to the individual PR's. The resulting behavior makes developers believe that their PR was never built, or their PR build failed when it was really because another PR was squashed/merged into their build. While the efficiency of this feature is beneficial/appreciated, I would like an option to force separate builds for each PR.

**Comment by LinkMJB** [comment]
I forgot to mention that this also seems to have the unintended consequence of failing to update the PR build status through the github API when the builds get merged. Only the PR that the build was originally for gets the API updates.

**Comment by benpatterson** [comment]
Related to #354 but leaving this as a unique issue

**Comment by benpatterson** [comment]
This issue should be resolved now, as part of the work to fix 354. Going to close.
