### ISSUE TITLE
Startup Time is slow

### ISSUE THREAD

**Issue by chr0n1x** [jenkinsci/ghprb-plugin#461]
When an instance of Jenkins has multiple jobs (say > 20)  that use this plugin, startup is extremely slow, probably due to the `createHook` call.

Have there been talks of making this process parallelized by default on startup?

**Comment by benpatterson** [comment]
No discussion on this @chr0n1x but your description makes sense. Marking this as an enhancement.

**Comment by chr0n1x** [comment]
@benpatterson thanks so much! Really appreciate it.
I actually wouldn't mind helping with development but I've never contributed to any Jenkins plugin before and don't even know where to start 😓

**Comment by benpatterson** [comment]
@chr0n1x Hey no problem. I'd appreciate help! For starters you can look at the Jenkins [guide to contributing](https://wiki.jenkins-ci.org/display/JENKINS/Beginners+Guide+to+Contributing). As far as this plugin is concerned, you can feel free to fork the repo and do development on it. The wiki has guidance on development as well...

**Comment by apottere** [comment]
@chr0n1x are you working on a fix for this?  I wouldn't mind creating a PR if you aren't.  This is causing our Jenkins instance to take more than 10 minutes to start :(

**Comment by chr0n1x** [comment]
@apottere I haven't been able to get any time to work on this 😞

**Comment by bjoernhaeuser** [comment]
I started to work on this and was able to create a PR which passes the tests: #535 

Afterwards I have seen #529. Not sure what is the best / better approach.

**Comment by chr0n1x** [comment]
@bjoernhaeuser I honestly wouldn't mind either, just as long as this gets fixed. @apottere @benpatterson - thoughts? 😄

**Comment by bjoernhaeuser** [comment]
IMHO #535 is simpler from a user perspective: less configuration knobs. So I personally vote for my proposal ;) (totally not biased)

**Comment by chr0n1x** [comment]
@bjoernhaeuser I'm fine with that. Have you tried it with a large # of jobs though? Say....2k? What's the improvement in startup time?

**Comment by benpatterson** [comment]
​Folks just letting you know I see this stream; I'm behind on work so am
still somewhat mum, but I'm here fwiw. Thanks for banding together on this
issue.

**Comment by bjoernhaeuser** [comment]
@chr0n1x I will test it tonight with our instance. It has around 100 hooks.

**Comment by chr0n1x** [comment]
@bjoernhaeuser is it possible for you to test it with about 10x more than that? If not it's ok...I guess that the startup time would just linearly grow (approx) 🤔 

Just left a comment though - might be better to allow the size of the thread pool to be configurable.

**Comment by apottere** [comment]
I agree that #535 is the way to go, but a configurable thread-pool would be awesome.  It could be as simple as adding a system property, but I know with 2k jobs we're going to want to up the size.

Thanks for looking into this!  I started myself but I got sidetracked with different work :(

**Comment by bjoernhaeuser** [comment]
With 5 threads, 216 hooks: two minutes.

**Comment by chr0n1x** [comment]
bump

**Comment by benpatterson** [comment]
Addressed partially through #535. Closing this issue.
