### ISSUE TITLE
Local cache / repository

### ISSUE THREAD

**Issue by hkroger** [jenkinsci/ghprb-plugin#468]
Is there a way to have a local repository cache so that when the git repo is cloned, first the local copy would be synced from GH and then clone is done from that copy?

This would speed up the cloning of bigger repositories  a lot.

**Comment by benpatterson** [comment]
@hkroger Good news. You can accomplish this using the reference clone feature on the [Git plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin). 

I don't see it documented on the wiki, but it is an advanced setting; you provide a path to the reference location. (I can't remember if it needs to be pre-populated or not...you'd have to play with it.)

**Comment by hkroger** [comment]
Oh cool, thanks!
