### ISSUE TITLE
GitHubPRBuildStatusPublisher.perform: NPE

### ISSUE THREAD

**Issue by pzoleex** [jenkinsci/ghprb-plugin#477]
Hi guys,

I have the next problem: I configured GitHub Pull Request Builder in my jenkins, and it works, recognizes the pull request, does the expected things.
But if I add a post-build action called github pr: post comment, then it fails with the next error (basically this job does nothing just exit 0):

```
GitHub pull request #9 of commit 7ac17199ea45bd2bd2c11009ea16c68113fa955d, no merge conflicts.
...
> git rev-parse refs/remotes/origin/pr/9/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/9/merge^{commit} # timeout=10
Checking out Revision 16f6ff17f33dd1e7fc6d75c2c74214229ae01dd3 (refs/remotes/origin/pr/9/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 16f6ff17f33dd1e7fc6d75c2c74214229ae01dd3
First time build. Skipping changelog.
[request-flow] $ /bin/sh -xe /tmp/hudson5318767715325995404.sh
+ exit 0
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.github.pullrequest.publishers.impl.GitHubPRBuildStatusPublisher.perform(GitHubPRBuildStatusPublisher.java:94)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'GitHub PR: set PR status' marked build as failure
```

If I remove the post-build action it is green. I verified the Jenkins/global settings/GitHub Pull Request Builder/GitHub Auth/Test crendentials and the given user has all permission everything is fine.

I don't understand what is the reason of this NPE. In the PR, the check appears as "x default — Build finished." so jenkins could update the PR.

Can anyone help me?

**Comment by pzoleex** [comment]
Ehh, sorry I mixed Build GitHub Pull Requests and GitHub Pull Request Builder

**Comment by benpatterson** [comment]
@pzoleex I was about to point out the same. While I'm here, this is the plugin that might be spawning an error of yours: https://github.com/KostyaSha/github-integration-plugin

You can do status through the ghprb plugin, you can look at those options, too.

**Comment by ElijahLynn** [comment]
Thanks Ben, I found two issues there that look related to this =>> https://github.com/KostyaSha/github-integration-plugin/issues/285
https://github.com/KostyaSha/github-integration-plugin/issues/293

**Comment by cbladd** [comment]
I also see this error.  I'm using the 'gihub pull request builder' plugin, and the 'GitHub PR: set PR status' postbuild action to report back to github the check status.  I was also using the 'GitHub hook trigger for GITScm polling' trigger to build on commit.  I hit this error when the job is triggered by a regular commit, when there is no PR.  My workaround is to have separate build jobs, one for PRs and one for commits.  It is a bad workaround, it doubles the number of jobs I have to maintain, What else can be done?
