### ISSUE TITLE
Add option to rebuild PR if destination branch is updated

### ISSUE THREAD

**Issue by remitaffin** [jenkinsci/ghprb-plugin#478]
It would be great if the plugin had an option to rebuild a pull-request if the target branch has been updated.

Here is the scenario:
We are using the plugin to run the unit tests when a new PR is created or updated.
Say we have 2 PRs: PR#1 and PR#2.
PR#1 and PR#2 passed the tests, but PR#2 gets merged first because it just passed code review.
The merge of PR#2 into PR#1 is breaking the unit tests, but since the tests weren't run again when PR#2 was merged, PR#1 is still "Passed" unless PR#1 gets rebased.
PR#1 gets merged as well and the unit tests are now breaking on the sprint branch (or master depending on where the branches are merged to).

I haven't found a workaround for that issue just yet...

If that can help, the Stash PR plugin already has that feature:
https://wiki.jenkins-ci.org/display/JENKINS/Stash+pullrequest+builder+plugin

**Comment by nitelite** [comment]
You can configure Github to require a new build status to be set if the PR branch updates. This will mean the approved status from the previous run of the test will disappear if you merge PR#2 branch into PR#1 branch, and they will run again. Try this setting:

![image](https://user-images.githubusercontent.com/1143814/29826086-a36280c8-8cd6-11e7-9846-ff70858a1272.png)

**Comment by remitaffin** [comment]
Thanks @nitelite, we found this a few months ago and we have been using it yes.
That's a great workaround, thanks!

**Comment by bjoernhaeuser** [comment]
I see we can close this issue because the problem can and should be solved by using the "require branches to be up to date before merging". :)

**Comment by esafronova** [comment]
#rebuild
