### ISSUE TITLE
Add capability to be Integrated with jenkins pipeline

### ISSUE THREAD

**Issue by alamsz** [jenkinsci/ghprb-plugin#479]
Since jenkins 2.0 introduction, there is pipeline job style, which using groovy DSL similar to job DSL.

It would be nice if this plugin also be made avaialble to be used in jenkins pipeline job similar to job DSL, since jenkins pipeline offers flexibility in scripting build script

**Comment by arthurlm44** [comment]
This would be a great feature. My organization would use it for sure.

**Comment by benpatterson** [comment]
This work is now being carried out in #497

**Comment by benpatterson** [comment]
Resolved in #497. Closing this ticket. If there's an issue with the new release (coming out shortly), please log a separate issue. Thank you!

**Comment by akhfa** [comment]
Is there any documentation how to use this in jenkinsfile? 

I can't find this plugin name in my jenkins pipeline syntax. This plugin documentation just cover jenkins  configuration instead of pipeline syntax.

**Comment by roguishmountain** [comment]
@akhfa it's usage is the same as the freestyle project. there's a checkbox in the configuration section of the project.

**Comment by akhfa** [comment]
@roguishmountain I know that there is checkbox in freestyle project, but there is no any checkbox in `Github Organization` project (or maybe I can't find it).

Can you upload pics when you configure your `github organization` project?

**Comment by roguishmountain** [comment]
@akhfa The GitHub Organization jobs have their own way to build PRs. I have no idea if this is compatible with GitHub Org projects, but it doesn't need to be. If you create a standard pipeline project then you'll see the ghprb.

**Comment by arcivanov** [comment]
@roguishmountain From everything I've been able to gather all Multibranch Pipeline projects have no support for chat-ops style, command execution and rudimentary policy support on GHPRB.
