### ISSUE TITLE
multiple builds requested by the same pr needs manual stoppage of old redundant builds

### ISSUE THREAD

**Issue by ananthakeshavabs-path** [jenkinsci/ghprb-plugin#482]
If we rebase a pr, each rebase triggers a new build but if the build time is long, all the builds need to go through or I need to manually stop older builds. It will be super cool to use the pr id to kill an existing build by the same pr and jump to the latest.

**Comment by benpatterson** [comment]
Anantha - you should be able to use the 'cancel' feature under the
triggers... option. Give that a try?
​

**Comment by ananthakeshavabs-path** [comment]
@benpatterson, thanks for the response. Is this the manual option? or can we enable this option to automatically cancel when we know subsequent build was also triggered by the same pr?

**Comment by benpatterson** [comment]
Hi  Anantha - This can be configured in the job and executed automatically.
:)

In your job, go to ghprb settings > Advanced... > Triggers... and you
should see an option for cancellations.
​

**Comment by ananthakeshavabs-path** [comment]
Thanks for the help. It works.
