### ISSUE TITLE
"Skip comment on closed PR"

### ISSUE THREAD

**Issue by ljacobford** [jenkinsci/ghprb-plugin#484]
Hi There,

I've been using your plugin to trigger Jenkins jobs and it works great--thank you for making it! One issue that I have, which would be really great to solve, is that the plugin seems to ignore comments made after the PR has been merged. We would like to create a workflow like so:

1. Create PR
2. Comment trigger phrase to start build and report back status when finished
3. Developer then manually merges the PR when (s)he sees that the build was successful.
4. Developer provides _another_ trigger phrase that zips up the repo and copies it somewhere.

So, I guess I'm wondering if (1) there's a way to tell your plugin to consider comments made after the PR is closed or (2) whether or not I'm looking at this the wrong way and there's a different way to do this.

Thank you!

**Comment by benpatterson** [comment]
Hi - Thanks for you interest!
​
I understand what you mean; however, the plugin doesn't do that. We don't
have plans to give it that capability either. However, depending on your
usecase, you could consider writing a job based on merges to master and
storing your artifacts on Jenkins or elsewhere. That way you could be sure
to capture the merge commit. Hope that helps!

**Comment by ljacobford** [comment]
I see. Thanks for your quick response--I'll look into your proposed solutions.
