### ISSUE TITLE
CI misses github webhook POST call

### ISSUE THREAD

**Issue by sathiya-mit** [jenkinsci/ghprb-plugin#492]
In our org we have lot of CI's, hence there is lot of poll scm calls which is creating unnecessary traffic on github server. Hence we planned to go ahead with github web hooks. In this model builds won't get triggered if web hook POST call did not reach CI due to network glitch or if CI itself is down for some reason. How about implementing long interval polling logic to cover the missed PR even if user is selected web hook model ? Please share your thoughts.

**Comment by mmitche** [comment]
@sathiya-mit Github itself does appear to do some level of retry for delivery failures.

**Comment by bjoernhaeuser** [comment]
I would argue that this is a bit out of scope. 

If you think otherwise you just reopen the issue please.
