### ISSUE TITLE
Allow separate "Commit Status URL" for "Build triggered" and "Build started" phases

### ISSUE THREAD

**Issue by LinkMJB** [jenkinsci/ghprb-plugin#498]
If a "Commit Status URL" is assigned that contains any build-specific parameters/variables, they hold no meaning until the job is out of the job queue and being built.

This causes a "Commit Status URL" of "https://jenkins.example.com/job/${JOB_NAME}/${BUILD_NUMBER}" to expand as "https://jenkins.example.com/job/MyJob/$%7BBUILD_NUMBER%7D" until the job has begun to build (big problem if your job is in the queue for an extended amount of time).

I believe allowing different "Commit Status URL" contexts for "Build triggered" and "Build started" phases would allow a more generic URL to be assigned until the job actually has a BUILD_NUMBER assigned.

Another way around this would be to provide a unique/primaryID/UUID for each build that sticks with it from job scheduling all the way through to job completion, preferably one that could be resolved when provided via a URL path in some format.

**Comment by bjoernhaeuser** [comment]
I like the idea with the unique build id more. But this is something core jenkins needs to provide, not sure if they already do.

@LinkMJB are you interested in finding this out and maybe scratch out a implementation?

**Comment by bjoernhaeuser** [comment]
Closing this for now, feel free to reopen a new ticket if you wanna move on! :)
