### ISSUE TITLE
is it possible to access the content of the trigger comment?

### ISSUE THREAD

**Issue by pzoleex** [jenkinsci/ghprb-plugin#501]
Hi,

You know you can control the plugin via "retest this please" comments and similar.
The question: can we access the text of the comment within the job (for example in environment variable)?

The reason: sometimes if a test fails I don't want to run all of the test just the failed test.
Like: "retest test-001 please" or similar. If I can access the comment in the job, then I can parse this and use the required part (in that case, run only the test-001)

**Comment by benpatterson** [comment]
@pzoleex there is a comment body available (`ghprbCommentBody`) which is set [here](https://github.com/jenkinsci/ghprb-plugin/blob/5cbe08938401bb04e65f9a6b1bbe4d2a37e1f036/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L370)

If you set that environment variable as a parameter on the job, you could likely parse it with an independent script.

**Comment by pzoleex** [comment]
Thank you! This is what I was missing.

**Comment by pzoleex** [comment]
Just one more short question:
is it possible to add test result as comment? I mean there is this checkbox:
"Add test result one liner" but this will add the result to commit status and I would need it in a comment.

**Comment by benpatterson** [comment]
@pzoleex Hmm this one I'm less sure about. I'd have to look closer but won't have time to dig in for a little while. Let me know if you beat me to it.

**Comment by brandonsturgeon** [comment]
Are we able to set this value from within our build script? I have some handy messages I'd like to put in the test one-liner as a result of various conditions in my script.
