### ISSUE TITLE
Usage with Jenkinsfile for pipeline?

### ISSUE THREAD

**Issue by chrylis** [jenkinsci/ghprb-plugin#507]
I'm new to the Pipelines feature, so I'm sure this is just a configuration error, but it may be a good starting point for a recipe in the docs.

I am trying to get a basic skeleton project building (which I'll then flesh out with real build steps). I've successfully gotten my pipeline to run by manually adding it (the GH plugin couldn't find the repo), and I was able to add the ghprb trigger in the project configuration page, and ghprb does try to kick off a build.

I believe that in order to pick up changes in my `Jenkinsfile`, I need to set the pipeline to "Pipeline script from SCM". I set everything up as I would for the regular checkout, using `${sha1}` as the Branch Specifier. However, when I triggered ghprb, my build failed with this message, which makes it appear as though the `${sha1}` placeholder is not being expanded at this stage:

```
hudson.plugins.git.GitException: Command "git fetch --tags --progress origin +refs/heads/${sha1}:refs/remotes/origin/${sha1} --prune" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/heads/${sha1}
```

How can I configure the combination of ghprb and Pipelines to pull the pipeline definition from the PR?

**Comment by liborbitala** [comment]
I am stuck exactly at the same point. 
Is there a way/plan to make it work with pipeline script placed in Jenkinsfile on GitHub with all the advantages of ghprb?

**Comment by anton-unity** [comment]
I'm planning to use jenkins pipeline + ghprb. Now wondering, does it actually work without Jenkinsfile, but plain script in jenkins project?

**Comment by liborbitala** [comment]
@anton-unity It works pretty well that way for me.

**Comment by roguishmountain** [comment]
Do you have lightweight checkout selected in the Pipeline SCM section? Unchecking lightweight checkout fixed this issue for me.

**Comment by liborbitala** [comment]
@roguishmountain I love when most important solutions are the easiest one :slightly_smiling_face: 
Thank you very much. Works exactly as expected for me.

**Comment by chrylis** [comment]
Looks like the "lightweight" checkout solves it. I have no idea _how_ it works, but it does.

**Comment by davetobin** [comment]
@chrylis Do you have an example JenkinsFile using ghprb that you could share? There doesn't seem to be much out there in terms of documentation so it would be very helpful.

**Comment by sean797** [comment]
@davetobin its not a option in your Jenkinsfile. https://i.stack.imgur.com/UdX86.png

**Comment by erstaples** [comment]
@roguishmountain You've saved me a world of headache. Two days of frustration and all for a damn checkbox!

**Comment by tyanko1** [comment]
@roguishmountain nice, saved me a headache!

**Comment by joeypiccola** [comment]
Also solved my problem... 

> Unchecking lightweight checkout fixed this issue for me.

**Comment by zadigus** [comment]
> Do you have lightweight checkout selected in the Pipeline SCM section? Unchecking lightweight checkout fixed this issue for me.

Thank you so much. I spent so much time trying to find out what the problem could be ...

**Comment by cSchubes** [comment]
I would like to reopen this - unchecking Lightweight Checkout is not an option in certain cases (if you are using Git LFS, for example) which makes this plugin unusable.

**Comment by aresares** [comment]
hudson.plugins.git.GitException: Command "git fetch --tags --force --progress --prune -- origin +refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH}" returned status code 128:
 with **kubernetes** agent and with  **Lightweight Checkout** disabled

**Comment by RPGillespie6** [comment]
> Unchecking lightweight checkout fixed this issue for me.

What the heck... you're absolutely right. This is why people hate Jenkins

**Comment by pranay511** [comment]
> Do you have lightweight checkout selected in the Pipeline SCM section? Unchecking lightweight checkout fixed this issue for me.

thanks for the quick help, now its working.

**Comment by sivas053** [comment]
> Do you have lightweight checkout selected in the Pipeline SCM section? Unchecking lightweight checkout fixed this issue for me.

Thank you so much

**Comment by Praveenkumar99** [comment]
> Do you have lightweight checkout selected in the Pipeline SCM section? Unchecking lightweight checkout fixed this issue for me.


Thanks
