### ISSUE TITLE
Add possibility to check all commits of a pull request

### ISSUE THREAD

**Issue by UniQP** [jenkinsci/ghprb-plugin#511]
For pull requests with multiple commits it would be nice to have the option to check all commits rather than only the latest one.

For example, in https://github.com/jenkinsci/ghprb-plugin/pull/509 the first commit is not checked by the CI. Such unchecked commit may introduce bugs that are fixed by other commits of the pull request, which makes bisecting more difficult.

**Comment by bjoernhaeuser** [comment]
Thats out of scope for this plugin and needs to be done by jenkins itself.
