### ISSUE TITLE
Build flow plugin dependency

### ISSUE THREAD

**Issue by alexwhitman** [jenkinsci/ghprb-plugin#513]
The [Build Flow plugin](https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Plugin) is both deprecated and has a known arbitrary code execution vulnerability.  GHPRB depends on Build Flow so it's not possible to remove the Build Flow plugin.

Consideration should be made as to whether the dependency can be removed.

![jenkins-ghprb](https://cloud.githubusercontent.com/assets/422013/25478955/0bbd4782-2b3b-11e7-8878-fde9f87e780f.png)

**Comment by mmitche** [comment]
This should be able to be made an optional dependency.

**Comment by christian-boesch-srf** [comment]
I'm also very happy if this plugin dependency could be made optional. As I want to remove the Build Flow plugin as well.

**Comment by dejayc** [comment]
Crickets?  Oh well, I guess it doesn't really matter if Jenkins is secure, right?  Or better yet, maybe we can just stop using external services like GitHub.

**Comment by benpatterson** [comment]
Really you want to look at #560.

**Comment by bjoernhaeuser** [comment]
It now is a optional dependency, therefore closing this for now.

**Comment by Panajev** [comment]
@bjoernhaeuser 

A bit confused as Jenkins is mandating that I must use either both plugins or neither... It does not seem like it is an optional dependency. What would you suggest in this case?

<img width="419" alt="screenshot 2018-02-01 13 57 22" src="https://user-images.githubusercontent.com/562991/35682238-e04fe768-0757-11e8-95ab-6d303c821d79.png">

**Comment by alexwhitman** [comment]
In the case where it's already installed you need to manually disable the optional plugin before you can uninstall it.  See this bug comment: https://issues.jenkins-ci.org/browse/JENKINS-33843?focusedCommentId=307253&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-307253

**Comment by Panajev** [comment]
Thanks @alexwhitman
