### ISSUE TITLE
Disable PR merge option if the build fails

### ISSUE THREAD

**Issue by bhumikagoyal** [jenkinsci/ghprb-plugin#517]
Currently the PR merge option remains enabled whether the checks fails or succeeds. There should an option in the plugin to disable the PR merge option if any of the checks fails.
![selection_033](https://cloud.githubusercontent.com/assets/6457715/25793409/f129f138-33e9-11e7-872c-a0ac228fa673.png)

I want the merge option to be disabled.

**Comment by anton-unity** [comment]
@bhumikagoyal I think you are talking about default Github functionality and can be configured for your repository. See https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by bhumikagoyal** [comment]
@anton-unity Thanks for the fast response. This is what I wanted so thanks for sharing the link.

**Comment by bhumikagoyal** [comment]
@anton-unity Is there a way to achieve this without protecting the branch?

**Comment by anton-unity** [comment]
@bhumikagoyal see https://help.github.com/articles/defining-the-mergeability-of-pull-requests.

Probably you can do that opposite way, that only account used by plugin can merge PR. And configure plugin to merge PR automatically, when build passed. In that case it will not be merged, until build passed.

**Comment by bhumikagoyal** [comment]
> Probably you can do that opposite way, that only account used by plugin can merge PR. 

I didn't get it. Can you please elaborate?

**Comment by anton-unity** [comment]
@bhumikagoyal sorry, I was wrong, forget about that option. I was sure that GitHub allows to specify access privileges on a branch level, but it doesn't. Protected branches is something you would like to use.

**Comment by bhumika-goyal** [comment]
@anton-unity Actually, I don't want the merge to be automatic. I just want to disable the merge option if build fails and in case it passes then the merge can be performed manually by people with write access(general case). 
Now, in case Github allowed access privileges for branch, then what you are suggesting is that in case the build passes, it will get merged irrespective of the committer's access privileges but in case the build fails then the people with access privileges can still merge that PR but for the committer the status of merge button will be "blocked".

**Comment by bhumika-goyal** [comment]
@anton-unity I will go with protected branchesthen. Thanks!

**Comment by bjoernhaeuser** [comment]
This can only be done on github itself, use the protected branches feature for this. 

Closing this for now.
