### ISSUE TITLE
Executing newInstance on every job when restarting Jenkins

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/ghprb-plugin#524]
I'm not sure if others face this issue.  We have over 3000 jobs configured in our Jenkins instance.  A restart takes longer than 5 minutes because on every job we get:

```
INFO: Starting the ghprb trigger for the folder/some-job job; newInstance is false
```

That seems to indicate that GHPRB is doing something for every job during startup.

Plugin version: GHPRB 1.32.8.4

I checked the changelogs and there didn't appear to be notes relating to this issue.

**Comment by akeithball** [comment]
Experiencing same issue

**Comment by samrocketman** [comment]
This has actually been solved by a recent merged PR and should be available in the next release.  Fixed by #543.  Add the following property to Jenkins startup options after GHPRB 1.39.1 release; `-Dorg.jenkinsci.plugins.ghprb.GhprbTrigger.disableRegisterOnStartup=true`.

**Comment by jerrywei116** [comment]
I tried this plugin and it can work and the related Jenkins job can be triggered successfully when I create a pull request. 
But when I merge a pull request, the related Jenkins job cannot be triggered although the event was posted from Github to Jenkins successfully.   

Could you please let me how to make it can work when merging a pull request?

**Comment by samrocketman** [comment]
I recommend asking for help in the jenkinsci-users mailing list https://jenkins.io/mailing-lists/

See Community for other forms of help.  There’s also a jenkinsci reddit.

This is mainly used to track bugs and fix them.
