### ISSUE TITLE
Plugin is clogging up resources and running very slowly

### ISSUE THREAD

**Issue by luis-silva** [jenkinsci/ghprb-plugin#537]
When I upgraded from version 1.36.2 to 1.37.0, all my cron based jenkins jobs started running at inconsistent times, sometimes not even getting triggered at all.

I tested my setup with just changing this plugin version and rebooting jenkins after that. Every time I rollback to 1.36.2 the jobs execute at the correct time, once I update to 1.37.0 they all run from a few seconds to a few minutes late or don't run at all.

Looking at the logs for this plugin, I can clearly see that version 1.36.2 parses all my pull requests in about 1-2 seconds, while version 1.37.0 takes a few seconds for **EACH** pull request. Since I have dozens of PRs and the plugin checks them every minute, it can never process all of the PRs before a new check is started thus creating a block and clogging the systems

I'm able to replicate this by just upgrading/downgrading the plugin followed by a restart. No other changes.

I'm using jenkins 2.64.

**Comment by benpatterson** [comment]
@luis-silva v 1.39.0 has a performance enhancement. Once it's available, could you give it a try?

**Comment by benpatterson** [comment]
Oh also, you may have a very full ghprb cache. I'll see if I can link an issue (can't remember if it's logged), but we've seen that cause performance issues in the past.

**Comment by bjoernhaeuser** [comment]
@benpatterson @luis-silva 

Can you share some more background information?

**Comment by benpatterson** [comment]
@bjoernhaeuser The only area I know about is if the ghprb cache is too large. I've seen that on long-running systems that handle 1000s of PRs. I'm sure there could be other performance issues with the plugin, but that's the only one I've verified in a running system. Don't have much more information than that, though. Didn't have the cycles to reproduce in a test system after we deal with the problem in prod. Removing the cache and getting it re-created solved the issue, although obviously there was user impact in having to re-validate some PRs as being allowed to run.

**Comment by bjoernhaeuser** [comment]
We are running with a lot or PRs and we do not see any problems. Please comment if you are seeing this.

**Comment by levimatheri** [comment]
I'm having this problem with 1.42.0
