### ISSUE TITLE
How to disable comments on pull request, Job based?

### ISSUE THREAD

**Issue by eciancio** [jenkinsci/ghprb-plugin#538]
I am attempting to use this plugin to trigger another Jenkins job which performs more detailed tests on the contents of my repo. This other job will also comment to the pull request with test results. I would like to disable the ghprb comment so that there are not two comments created for each pull request. So far I have not discovered a way to disable to the PR commenting per job. Is there a way I can do this?

**Comment by mnordsletten** [comment]
I solved this by creating two different personal access tokens. They were configured in the following way.

1. WITH comment: repo:status and public_repo
2. NO comment: repo_status

Then configure the jobs with different access tokens and both will update commit statuses, but only 1 will actually comment.

**Comment by bjoernhaeuser** [comment]
@eciancio yes you can disable this in the settings! 

If this does not work for you a screenshot with the current settings would be much appreciated.

**Comment by bjoernhaeuser** [comment]
Please reopen if this does not solve the problem for you, i am just trying to cleanup some old issues :)

**Comment by colemickens** [comment]
Where? I don't see this in the job configuration (and don't know how to take a screenshot of something that I can't find).
