### ISSUE TITLE
It always add slash at the end of "project url" in ghprb 1.38.0

### ISSUE THREAD

**Issue by devops2seedlink** [jenkinsci/ghprb-plugin#539]
I installed the latest version ghprb.
When I add project url in job configuration, it will automatically add a slash after github repo url after I click save.
eg.
type in "git@github.com:<org\>/\<repo_name\>.git", it will show "git@github.com:<org\>/\<repo\>.git/" after saving.

This will cause ghprb not working with reporting 
"java.lang.IllegalStateException: Invalid GitHub project url: git@github.com:<org\>/\<repo_name\>.git/".

Is it a bug in some dep package?

**Comment by mthhs** [comment]
@devops2seedlink Did you ever figure this out? I have the same annoyance as well.

**Comment by lennybe** [comment]
recheck
