### ISSUE TITLE
Request doesn't contain payload

### ISSUE THREAD

**Issue by klausbayrhammer** [jenkinsci/ghprb-plugin#540]
Hi, 

We have been using your plugin for quite a while and have been really satisfied with it. Lately although we have some issues with getting webhooks to trigger builds consistently.
In most cases the webhooks work fine but roughly once every ten times the webhooks do not trigger a build. The github webhook delivery history shows the following error message: `We couldn’t deliver this payload: Failure when receiving data from the peer`.

When checking the Jenkins logs we get the following entries (Webhook Content Type set to `application/x-www-form-urlencoded`)
```
Jun 20, 2017 11:34:14 AM SEVERE org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Request doesn't contain payload. You're sending url encoded request, so you should pass github payload through 'payload' request parameter
```
This seems related to janinko/ghprb#164 so we tried switching the Content type of the webhook to `application/json` which had no real effect execpt that the error messages changed to
```
Jun 20, 2017 1:28:42 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbRootAction doIndex
Can't get request body for application/json.
```

The thing that bugs me is, that the integration works most of the time - but not always and I couldn't really find a pattern when it's not working.

More details:

github-api-plugin 1.85
GitHub plugin 1.27.0			
GitHub Pull Request Builder 1.35.0	
Jenkins 1.625.3

Thanks for this great plugin! i really appreciate your work! If there is anything I can do to support you - just let me know
Cheers Klaus

**Comment by bjoernhaeuser** [comment]
Hi!

Do you see any difference in the payload for the nonworking and working payloads? What happens if you resend the payload through the github ui? Does it work on the second try?

Are you using any kind of network equipment between github and jenkins which could alter the request? Do you use SSL for github -> jenkins?

**Comment by bjoernhaeuser** [comment]
Will close this for now.
