### ISSUE TITLE
skipping PR build and allowing the merge

### ISSUE THREAD

**Issue by dmitsh** [jenkinsci/ghprb-plugin#548]
Is it possible to skip the PR build on some changes (documentation, etc.) and allow the merge?
We can skip PR build by adding a blacklist label , or by adding "[skip ci]" to the PR title.
However, if our GitHub is configured to wait for the PR build status, we cannot merge this PR.
The status is never coming because the build has been skipped.
Did we miss any of the settings? Is there a workaround to allow the merge?

**Comment by anton-unity** [comment]
@dmitsh probably someone can correct me, but I don't think there can be such option.

"[skip ci]" used for commit, when you know it's not final and there is no need to overload your testing resources. So just use "skip" for intermediate commits and don't use for the final one, which will trigger build, which will change status of latest commit.

**Comment by bjoernhaeuser** [comment]
@dmitsh How would that look like? The plugin can not guess your intentions :)
