### ISSUE TITLE
no jobs triggered

### ISSUE THREAD

**Issue by ddwolf** [jenkinsci/ghprb-plugin#550]
this is the access log in tomcat8
"POST /github-webhook/ HTTP/1.1" 200 -
no other logs like in catalina.out

and no jobs triggered. I have configured my job to use github pull request builder, if something is wrong with config, there should be error messages, but nothing. so weird.

is there a config where I can use to turn on debug mode?

**Comment by benpatterson** [comment]
@ddwolf that endpoint is used for a different plugin. For this plugin, you'd use `ghprbhook`

**Comment by ddwolf** [comment]
@benpatterson Oh, I see, you are right, after I removed the github-webhook，system regenerages a new hook called ghprb, and now it works.
