### ISSUE TITLE
how to trigger pull request build by http call?

### ISSUE THREAD

**Issue by riuvshin** [jenkinsci/ghprb-plugin#554]
My goal is to have button in PR template by clicking which PR build will be triggered. We don't want spam comments like `ci-build` or `test this please` we just want to have embedded button in PR. Is that possible?

**Comment by benpatterson** [comment]
@riuvshin What you describe is an interesting idea, but is not something that the plugin currently does. The key underlying piece of it is what kinds of events GitHub will send webhooks on, and what kind of data can be taken out of those hooks vs what needs to be re-fetched. I think what you describe may be possible to implement, but it depends a little on what options we get out of GitHub.

**Comment by riuvshin** [comment]
@benpatterson thanks for the reply :) I believe that there is not that much info needed to trigger a build, right? perfect solution for me would be some url like "Trigger builds remotely" does. and put that url as a nice button embedded in PR template :) as super-duper advanced usecase it could have some customizable options over query param to make some decision inside of the job, this way it would be possible to have buttons like <BUILD> and <TEST> or <BUILD>  <DEPLOY> smt like that.

**Comment by bjoernhaeuser** [comment]
@riuvshin I think this is out of scope of the plugin. I think the best approach you can take is to try to trigger the build through the jenkins API itself.
