### ISSUE TITLE
Allow filtering by project

### ISSUE THREAD

**Issue by ifireball** [jenkinsci/ghprb-plugin#558]
When you have multiple projects attached to the same Jenkins master, it is currently impossible to make different jobs trigger for different projects.

Its is desirable to do this filtering before sending any whitelist request comments to PRs to prevent unnecessary messages to unrelated PRs as mentioned on #148 and #267

**Comment by bjoernhaeuser** [comment]
It's unclear what you mean with project. If you mean github project that should work as expected.

Can you please add some more information to the issue or is "just" a duplicate from the mentioned issues?

**Comment by ifireball** [comment]
Yeah, it turns out there is no project cross-talk. #267 still applies though. This can be safely close from my POV.
