### ISSUE TITLE
Need maintainer

### ISSUE THREAD

**Issue by benpatterson** [jenkinsci/ghprb-plugin#560]
I'm currently the maintainer for this plugin but don't have the time (and no longer use Jenkins) to be an effective maintainer. We need a new maintainer or group of maintainers to keep this plugin useful. Logging this as an issue and will also post on the dev list in case there are folks that feel they can put their time into this.

I think we did some good things with this plugin the past several months but it's time for someone(s) to take the reins and keep the good things going.

**Comment by benpatterson** [comment]
CC @bjoernhaeuser @chr0n1x @samrocketman

**Comment by benpatterson** [comment]
Oh also @jzoldak and @syoung whom I've worked with on the plugin although I was the one who did the contributions.

**Comment by bjoernhaeuser** [comment]
I would love to help bringing this plugin further and take a more active role here. 

What ever happens you (and your colleagues) did a amazing job and made this plugin what it is today: an amazing piece of software.

**Comment by samrocketman** [comment]
I wouldn't mind assisting with maintenance.  I currently maintain the GitHub OAuth plugin.

**Comment by papajulio** [comment]
Hello, I would love to help in the maintenance of this plugin I was looking around for a plugin to help with and I will love to help with this one.

I don't have too much experience with jenkins plugins, just one pull request some time ago. But I will love to learn and help. Let me know where I can be of some help and I will work on whatever you need, reproducing bugs, testing PRs. reviewing issues no problem at all.

**Comment by benpatterson** [comment]
Hi folks - great to see such a positive response! 

Also thank you for the compliments. :) Like any software, what it needs most to remain a good plugin, is proper care. I think it'll better with >1 person so I'm glad to see various folks are willing to give some time. Many hands make light work, as it were.

I'm going to give this another couple of days, and then figure out how we can move it.

**Comment by samrocketman** [comment]
As for moving forward, we can open an issue similar to this one -> https://github.com/jenkins-infra/repository-permissions-updater/pull/399

It serves as an example for how we can move forward once @benpatterson decides who they wish to add as co-maintainers.

Also, I recommend @benpatterson staying on as a co-maintainer at least long enough for an effective handoff in case the new maintainers have any questions around process.  It also helps to smooth the community transition.

For reference, here's GHPRB plugin https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-ghprb.yml

**Comment by benpatterson** [comment]
Indeed that is how I was looped in and +1 on the idea of me staying on for a while to help out.

**Comment by benpatterson** [comment]
Folks - I created a [wiki page](https://github.com/jenkinsci/ghprb-plugin/wiki/Short-and-medium-term-objectives) where we can think this through & add next steps. You should be able to edit this page and add your thoughts, but let me know if not and I can take a closer look at settings.

I'm planning to give each of you contributor level access at least. It's up to you on deciding whether or not giving you all the same permission level makes sense, or if it's better to have one person. (I'm thinking mostly about building releases here.) We can discuss access levels here or on the wiki, whichever you prefer. I think taking a few minutes to think about the things on the wiki may inform the operating model we want.

Hopefully this all makes sense. Please take a look and let us know what you think. If I'm totally going in the wrong direction here, I'm open to feedback, too. I mainly want to figure out what to do, then turn on the engine.

**Comment by JPWKU** [comment]
Hi Folks, I'd like to offer my services as a co-maintainer.  I currently work for the Linux Foundation as a Release Engineer.  I was able to get approval to carve out some work time for this project.  I can be super flexible as far as project needs and what not.  I'm going to read up on the wiki that Ben started and hopefully offer some of my perspective.  Looking forward to working with other folks on this!
Thanks
Jeremy

**Comment by papajulio** [comment]
All seems good to me, sorry for not being more on top of this but I was on holidays. I will check the PR and add my credentials sorry for the delay. 

I like the idea of @JPWKU about assign specific task to a maintainer but no limit that task to that maintainer so we can all learn and help with everything. 

I would love helping with the documentation or the new tests,  that @benpatterson added in the list of areas to improve.

**Comment by psiroky** [comment]
Hello everyone. I see there is already quite a few volunteers, but in case needed I would be interested in taking a part as a co-maintainer. Or if there is enough active maintainers, I can of course just submit PRs and get them reviewed (and hopefully merged). We use this plugin quite extensively and it would be great to get it back on the track :)

**Comment by papajulio** [comment]
@benpatterson Hello, I am having some family issues right now and I won't be able to dedicate the time that I thought to maintain this plugin in the short term, sorry. Whenever I am able to return to normality I will come back here to help with whatever I can. Sorry guys

CC @bjoernhaeuser @JPWKU  @samrocketman

**Comment by samrocketman** [comment]
No worries.  I understand it happens.  Good luck.

**Comment by sgleske-ias** [comment]
Has there been any additional movement here?

**Comment by bjoernhaeuser** [comment]
Shall we close this now? :)

**Comment by samrocketman** [comment]
Yep, I think it's sorted out
