### ISSUE TITLE
ghprbPullId not populated when job is triggered manually

### ISSUE THREAD

**Issue by imdadahad** [jenkinsci/ghprb-plugin#561]
We are using the pull request builder plugin. Our project is open source and an author has raised a PR (not whitelisted). The builder has popped this comment `Can one of the admins verify this patch?`, to which we responded `ok to test` for the tests to run (as documented here https://github.com/janinko/ghprb).

However, this does not seem to populate the environment variables such as `ghprbPullId`, `ghprbPullDescription`, etc. (https://wiki.jenkins.io/display/JENKINS/GitHub+pull+request+builder+plugin#GitHubpullrequestbuilderplugin-EnvironmentVariables)

These variables are populated fine when a PR is opened by a whitelisted member. Any idea what's going wrong here?

**Comment by bjoernhaeuser** [comment]
@imdadahad can you verify that the behaviour is still the same with the latest version of jenkins / this plugin?

We are using this technique every week and it works as expected :)

**Comment by imdadahad** [comment]
No longer on the project so closing this issue.
