### ISSUE TITLE
[Docs bug] Help me understand ${sha1} vs ${ghprbActualCommit}

### ISSUE THREAD

**Issue by hartzell** [jenkinsci/ghprb-plugin#563]
The README.md file says this about the Branch Specifier:

> - In Branch Specifier, enter ${sha1} instead of the default */master.
> - If you want to use the actual commit in the pull request, use ${ghprbActualCommit} instead of ${sha1}

I don't understand the difference.  If someone explains it to me I can buff up the README.md and PR it.

When I set it to use ${ghprbActualCommit} it seems to be the tip of the branch on which the work was done.

What is ${sha1}?

Thanks!

**Comment by hartzell** [comment]
I've been experimenting and I think what's happening is this:

- if the Branch Specifier is `${sha1}`
  - if the "base" branch and the "compare" branch can be merged
    - this runs the test on the merged result, e.g. `/origin/pr/4/merge`
  - else
    - this runs the test on the head of the compare branch, e.g. `/origin/pr/4/head`
- if the Branch Specifier is `${ghbprbActualCommit}`
  - this runs the test on the head of the compare branch, e.g. `/origin/pr/4/head`

Is that correct?

**Comment by papajulio** [comment]
@hartzell you seem to be right and your explanation makes sense to me so :+1: 

But probably would be nice to wait for somebody with more experience than me that acknowledge this.

**Comment by bjoernhaeuser** [comment]
@hartzell 

Your explanation is correct! Do you mind adding this explanation?

**Comment by hartzell** [comment]
@bjoernhaeuser -- done.
