### ISSUE TITLE
can't connect to  Github Enterprise

### ISSUE THREAD

**Issue by panpan0000** [jenkinsci/ghprb-plugin#566]
I'm recording the issue here, hope it can help anyone who may meet the same issue...

**Error Keyword:** 
"Unable to connect to GitHub API: org.kohsuke.github.HttpException"

**Problem Plugin version:**
- GitHub plugin  v1.27
- GitHub Pull Request Builder  v1.37

**Error Details**

in Jenkins Admin --> Configuration --> GitHub Pull Request Builder

![image](https://user-images.githubusercontent.com/14049268/30157836-e3f66516-93f5-11e7-8a5e-9c61cf236887.png)

when "Test Connection" it will always fail even the "curl -u user:pwd  https://ent2git.cec.lab.***.com/api/v3/user  " works well in the Jenkins master.

the "Test Connection error message" looks like below( sorry, I lost the failure snapshot and I can't afford to downgrade the plugin again to reproduce the issue (it's our production Jenkins), so I can't recalled every character correctly for below error messages . )
```
Unable to connect to GitHub API: org.kohsuke.github.HttpException
{"message":"null","xxxxx_url":"https://entgit.cec.lab.***.com/api/v3/user"}
```

**Fix**

the issue was gone when I upgrade the both plugs in 
- GitHub plugin  v1.28
- GitHub Pull Request Builder  v1.39
so I don't know which upgrade fixed the problem.

But another Jenkins instance runs below lower plugin version , and issue does not appear there  
- GitHub plugin   1.26
- GitHub Pull Request Builder   1.35

**Comment by bjoernhaeuser** [comment]
I suspect this problem in git Github Api Plugin. But if it works now I will go ahead and close the issue.
