### ISSUE TITLE
Deleting a project doesn't de-register the project from the webhooks repo

### ISSUE THREAD

**Issue by patrickvinas** [jenkinsci/ghprb-plugin#569]
I had a multijob project set up with a ghprb trigger and "Use github hooks for build triggering". For various reasons, I copied the original project to a new project, and then deleted the new project. Now PRs to the monitored github repo are triggering both the original project and _the deleted project_.

This is on jenkins 1.642.4 with ghprb 1.35.0.

Is there a way to manually remove the deleted project from the webhooks repo? I already tried re-creating the job and then unsetting "use github hooks for build triggering" but that registered and then unregistered the new job (webhooks repo length was 5, then 6, then 5 - I need it to be 4).

**Comment by bjoernhaeuser** [comment]
Hey, the described usecase should work right now. The hook would not be registered twice. What's still missing though would be to delete the hook. Problem here is that we do not know if the project that was deleted is the last project which uses the hook.

Closing this for now, please comment & vote for the issue if this is relevant for you.
