### ISSUE TITLE
Can't trigger the job when working with Organizations

### ISSUE THREAD

**Issue by nordri** [jenkinsci/ghprb-plugin#571]
Hi there.
We're trying to configure Jenkins (2.60.1) with ghprb and for some unknow reason the job is not triggered when one of the admin writes the trigger sentence in the PR.
We checked twice the configuration and the "Test credentials" section under "GitHub Pull Request Builder" returns OK to all checks. [png](http://federnetes.com/issue.png)
Everytime the admin writes the comment we can see it on the logs but nothing else. No errors, nothing.
The same configuration works fine with a single user. Repos that belongs to a single user. Not organizations.
Plugins versions:
```GitHub Pull Request Builder 1.39.0
GitHub API Plugin           1.86
GitHub plugin               1.28.0
Git plugin                  3.5.1
Credentials plugin          2.1.16
Plain crendentials plugin   1.4
```
Please, can anyone give me some advice of what could be going on? It's quite desesperate because doesn't seem that is been happening anybody else.
Thanks.

**Comment by nordri** [comment]
Hi,
No one is strugging with this in their environment??

**Comment by bjoernhaeuser** [comment]
Can you please add the logs of the plugin so we can understand it a bit better? 

From your description: We are using the plugin in the same way you described and it works perfectly.
