### ISSUE TITLE
how to trigger build on creating the PR and updating the PR with the commits

### ISSUE THREAD

**Issue by vaisakhsaikripa** [jenkinsci/ghprb-plugin#576]
I am checking on how to configure the jobs / jenkins in order to trigger a build while creating a PR and on updating the PR with the commits. We are now using the trigger phase to start the build by commenting them on the PR comment Box. Appreciating the help if any one can.

**Comment by bjoernhaeuser** [comment]
The author of the PR needs to be whitelisted (If I understand your issue correctly). If the author is whitelisted the build should start automatically.

If this does not solve the problem for you please reopen the issue again.
