### ISSUE TITLE
Is whitelisting the ghprb block when using sandbox necessary?

### ISSUE THREAD

**Issue by hartzell** [jenkinsci/ghprb-plugin#583]
Whenever I add a trigger via the Job DSL from a job that's running within the sandbox it gets blocked with an error like:

```
Processing DSL script jobs.groovy
ERROR: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (javaposse.jobdsl.dsl.helpers.triggers.TriggerContext githubPullRequest jobs_ghe_rss$_run_closure2$_closure13$_closure18)
```

That also generates an approval request in the Manage Jenkins -> Script Approval page.

Once I approve it, everything works as expected.

In other cases when I generate this error it's been because I had Job DSL blocks in incorrect locations (moving forward in versions and onto a new server, I believe that the details changed)
In this case I seem to be doing everything as I'm supposed to.  I'm wondering if there's something missing in the ghprb job dsl setup that would straighten this out.

Having to approve it every time won't scale well.

Thanks!

**Comment by bjoernhaeuser** [comment]
Can you share your dsl script? I am also using dsl and do not have these problems.

**Comment by hartzell** [comment]
I no longer have access to these systems, and don't have a reasonable way to set up a similar test.

Perhaps I should close this?

**Comment by bjoernhaeuser** [comment]
Lets do it for now, i anyone has some new insights to it let's reopen and fix it!
