### ISSUE TITLE
Github pull not triggering Jenkins build launch

### ISSUE THREAD

**Issue by dockernewbie** [jenkinsci/ghprb-plugin#590]
I was following along the below article to get GHPRB working but am not sure what is wrong in my set up.

http://www.inanzzz.com/index.php/post/ljgv/setup-github-and-jenkins-integration-for-pull-request-builder-and-merger

Jenkins 2.73.1
GitHubPull Request Builder 1.39.0
GitHub API Plugin 1.90

From the jenkins logs I receive what appears to be correct after pushing the new branch per the above article.

Nov 07, 2017 10:32:16 AM org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
WARNING: Request not known for event: push
Nov 07, 2017 10:32:16 AM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
INFO: Received PushEvent for https://github.xxx.xxx.com/yy/zzzzz from 1.1.1.1 â http://jenkins-xx.xxx.com:8080/github-webhook/

However in the part where it is supposed to start the build I only see the following.

Nov 07, 2017 10:32:20 AM org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
INFO: Checking PR #123 for yy/zzzzz

Per the tutorial doc, I expected to see this though (org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction) and more which I never do.

Jan 14, 2017 8:21:35 PM org.jenkinsci.plugins.ghprb.GhprbRootAction handleAction
 
INFO: Checking PR #3 for Inanzzz/nation
 
Jan 14, 2017 8:21:35 PM org.jenkinsci.plugins.ghprb.GhprbTrigger handlePR

Is there potentially a bug or most likely a misconfiguration on my part that someone can help guide me to?

Thanks in advance.

**Comment by bjoernhaeuser** [comment]
It is this line: `WARNING: Request not known for event: push`

This pluing is only for pull requests, for normales pushes to master you need the github plugin: https://wiki.jenkins.io/display/JENKINS/GitHub+Plugin

If this does not answer your question please reopen the issue.
