### ISSUE TITLE
GitHub webhook SSL verification disabled by default

### ISSUE THREAD

**Issue by marcokrikke** [jenkinsci/ghprb-plugin#596]
The ghprb plugin by default sets `insecure_ssl` to "0" when managing repository webhooks, resulting in SSL verification by GitHub being disabled:

![screen shot 2017-11-23 at 15 52 35](https://user-images.githubusercontent.com/1352315/33178463-8386797a-d066-11e7-87a6-a5b540d0cbde.png)

Is there a specific reason why this behaviour is implemented? IMHO this setting should be configurable.

https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/GhprbRepository.java#L294

**Comment by bjoernhaeuser** [comment]
Probably noone cared about this until now :)

I think the implementation should have a global configuration for enabling it and than the hook can be created with ssl verification.

Do you want to contribute the required changes? :)

**Comment by marcokrikke** [comment]
I'll try to find some time to look into this, but no promises ;)

**Comment by bjoernhaeuser** [comment]
Closing this in favor #663
