### ISSUE TITLE
Allow user managed webhook

### ISSUE THREAD

**Issue by karataliu** [jenkinsci/ghprb-plugin#611]
If a user created the github token without hook permission, and he would like to manage the web hook, the plugin should not try to create a hook.

Currently the plugin will still keep on doing the check and try creating the hook:
```
Jan 08, 2018 5:49:49 AM org.jenkinsci.plugins.ghprb.GhprbRepository createHook
SEVERE: Could not create web hook for repository foo/bar. Does the user (from global configuration) have admin rights to the repository?
```

A simple call graph is :
start->createHook->hookExist->ghRepository.createHook

Actually if user would manage the hook, there's also no value in checking 'hookExist' every time.

Can we have an option to allow user managed webhook?

**Comment by bjoernhaeuser** [comment]
@karataliu this option is already implemented:

<img width="1394" alt="screen shot 2018-01-13 at 11 02 50" src="https://user-images.githubusercontent.com/1449155/34905050-5b8ade6c-f851-11e7-96f1-72e6a6fbcc42.png">

If you setup the hook manually builds will still be triggered through the hook. Closing this for now, if it does not help you please reopen / comment.

**Comment by karataliu** [comment]
@bjoernhaeuser  Thanks for taking a look. I saw that option, but it does not seem to address this issue.

This issue is bit more about user **managed** hook, rather than user **manually setup** hook.

I've chosen `Use github hooks for build triggering` and also setup the hooks manually according to the guidance.  The plugin functions as expected, and everything looks good so far.

But when checking the jenkins log, we'll find a lot of following entries:
```
Jan 08, 2018 5:49:49 AM org.jenkinsci.plugins.ghprb.GhprbRepository createHook
SEVERE: Could not create web hook for repository foo/bar. Does the user (from global configuration) have admin rights to the repository?
```

Since I would manually create the hook, I don't give the github token `hook` permission, thus it reports such error. But it also reveals that the plugin is still trying to validate and create the hook periodically. 

And when looking at the code, we can find the call chain:
`start->createHook->hookExist->ghRepository.createHook`


I would propose an additional  sub-option, say 'User managed hook'. Which indicates the user would manually create and maintain the hook, thus the plugin should skip the `createIfNotExists` logic.

This would be useful in at least two cases:
1. User manually sets the hook, and does not give `hook` permission to the github token. In this case, `createIfNotExists` would fail.
2. User uses a proxy service for managing hook callbacks, which then forwards call to internal jenkins server. In this case, `createIfNotExists` might setup a hook with incorrect endpoint.

If we have the new option, the plugin could just feel free to skip the hook validation.

**Comment by bjoernhaeuser** [comment]
@karataliu there is a global setting `Auto-manage webhooks`. If you deactivate this (default is true), the plugin will use webhooks for triggering but will not try to create them. This should do the trick for you :)

**Comment by silverfort-eyal** [comment]
test this please
