### ISSUE TITLE
mail commander plugin 

### ISSUE THREAD

**Issue by rmusale** [jenkinsci/ghprb-plugin#625]
Hello there,

 

I am trying to build to project by sending an email .For this I  follow the steps as per below link 

still build is not getting triggered by sending an email to configured pop3 email 

 

Link used to set up  project config is  :- 

  https://wiki.jenkins.io/display/JENKINS/Mail+Commander+Plugin

 

 

Thanks in Advance

**Comment by bjoernhaeuser** [comment]
This plugin is to trigger builds from github pull requests / commits / comments. Not seeing the mail thingy here :)
