### ISSUE TITLE
Cancel Builds On Update is not exposed via DSL

### ISSUE THREAD

**Issue by bsudy** [jenkinsci/ghprb-plugin#628]
I couldn't set 'Cancel Builds On Update' extension using DSL. As a solution I fall back to [configure block](https://github.com/jenkinsci/job-dsl-plugin/wiki/The-Configure-Block) using

```groovy
configure { projectNode ->
    projectNode / 'triggers' / 'org.jenkinsci.plugins.ghprb.GhprbTrigger' / 'extensions' << 'org.jenkinsci.plugins.ghprb.extensions.build.GhprbCancelBuildsOnUpdate' {
        overrideGlobal(false)
    }
}
```

I think it would be great to have it also exposed in the DSL.

**Comment by bjoernhaeuser** [comment]
@bsudy do you want to take the chance and contribute that change? :)

**Comment by bjoernhaeuser** [comment]
I have a PR for this: #664

**Comment by vfarafonov** [comment]
Just an FYI: PR for this was merged a long time ago but no release happened since then. Any plans to release soon?
