### ISSUE TITLE
ssh sites not working

### ISSUE THREAD

**Issue by rdumi7ru** [jenkinsci/ghprb-plugin#635]
Hello,
I'm trying to add ssh sites but the User Name and Password fields are not present.
I'm adding the hostname and port, but when I'm check the connection I get back "Please fill host, port and credentials."
![image](https://user-images.githubusercontent.com/25224964/36633566-d0be46d6-19a0-11e8-828e-61c907195a75.png)

Someone had this issue before?

**Comment by bjoernhaeuser** [comment]
Sorry, ssh remote sites are out of scope for this plugin.
