### ISSUE TITLE
Is it possible to run my checks on each commit added by the PR?

### ISSUE THREAD

**Issue by Ippo343** [jenkinsci/ghprb-plugin#636]
I would like to have my checks (build and tests) run on every commit that is added by the pull request, but I cannot find a way to do this.

I could achieve almost the same result using git and some scripting, but that would report the status only for the last commit.

If at all possible I would like to run:
- a light set of checks on each commit that is added by the PR;
- a more thorough set of checks on the last commit to ensure that the merge is good.

Thanks!

**Comment by bjoernhaeuser** [comment]
@Ippo343 this is currently not possible and personally I do not see the benefit of this :)

Though I could imagine that we will accept changes for this, so feel freee to contribute. We can help you scratch out the idea and see how the changes could be intercorporated.

**Comment by Ippo343** [comment]
We'll, the "hypothetical" benefit is when you want to make sure that all the commits are, at least, buildable. I'll try to find some time to poke around the source code, in the meantime thanks for your time :)
