### ISSUE TITLE
Latest version of ghprb job DSL integration is not working

### ISSUE THREAD

**Issue by ezyang** [jenkinsci/ghprb-plugin#640]
Steps to reproduce:
1. `git clone https://github.com/sheehan/job-dsl-gradle-example` ; I tested on c14c1f5
2. Modify `build.gradle`, updating `ghprb` to 1.39.
3. Run `./gradlew test`. It passes
4. Modify `build.gradle`, updating ghprb` to 1.40
5. Run `./gradlew test`. It fails

**Comment by bjoernhaeuser** [comment]
Whats the error message you are getting?

**Comment by ezyang** [comment]
No signature of method: "javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.githubPullRequest() is applicable for closure arugment"

**Comment by bjoernhaeuser** [comment]
I opened a PR which fixes this in the example, this not a problem ot GHPRB.

**Comment by ezyang** [comment]
Which PR is this?

**Comment by bjoernhaeuser** [comment]
I linked it :) but for completeness: https://github.com/sheehan/job-dsl-gradle-example/pull/100
