### ISSUE TITLE
Support multiple concurrent pull request builds (pr# mod n)

### ISSUE THREAD

**Issue by ctubbsii** [jenkinsci/ghprb-plugin#650]
In my Jenkins server, I would like to have two jobs (`pr# mod 2 == 0` and `pr# mod 2 == 1`), so that one pull request does not block building a second pull request. I can imagine even more concurrent tasks, using `mod 3`, etc.

To achieve this, I propose adding a very simple conditional in the advanced plugin configuration for a job... to build jobs whose pull request number matches a specific condition (using a language that supports modulus, and perhaps other conditional checks).

**Comment by egherrmann** [comment]
Is there a reason why checking the "Execute concurrent builds if necessary" box on your job doesn't solve your problem?

**Comment by ctubbsii** [comment]
LOL, okay, so I'm just an idiot, and didn't notice that checkbox. Thanks. :smiley_cat:
