### ISSUE TITLE
Trigger Jenkins build only on merging to master

### ISSUE THREAD

**Issue by bpinske** [jenkinsci/ghprb-plugin#651]
I am having an absolutely miserable time trying to achieve this.

I do not want to trigger on PR submission, or git push. I DO want to trigger a jenkins build of master AFTER a PR has been merged to master.

Is there clear straight instructions for this somewhere?

**Comment by MaitreyaBuddha** [comment]
What you're asking for is outside the scope of this plugin. Unless you want to *only* trigger after a PR, this is easily achievable by other means. If you search "jenkins trigger build on git commit" you will find many articles detailing how to do that.

**Comment by bpinske** [comment]
I still don't understand.

I've followed every guide that I can find, but I can't find what I actually want. The guides are either specifically for git post-commit hooks which isn't what I want. I don't want the act of `git commit` to do anything. I want the content of a PR getting placed into a master branch to be the trigger.

https://i.imgur.com/WafuMvt.png

When I click squash and merge. I want Jenkins to do something. No matter what I try, if I use this command, I get a trigger on the PR submission.

`echo ok >> test1; git add test1; git commit -m "jenkins pr webhook testing" --amend; git push -u -f origin brandon/testingjenkins7`

Can you link me specifically the article that you think details this?

**Comment by MaitreyaBuddha** [comment]
This one looks good: https://medium.com/@marc_best/trigger-a-jenkins-build-from-a-github-push-b922468ef1ae

**Comment by bjoernhaeuser** [comment]
This plugin is purely for github pull requests. If you want to do something only on master just configure a job in jenkins, which polls the repository every x minutes or you can optionally use the `github-plugin` to add an webhook.

**Comment by mwtzzz** [comment]
I have to say I am in the same boat as the OP, and am not finding *anything* that explains how to do it. The "this one looks good" comment above only works with Git Pushes (of all kinds, to any branch) but not on merging PRs to master. If Jenkins is unable to support this, seems like a serious flaw in Jenkins.

**Comment by jayaganthan** [comment]
> I have to say I am in the same boat as the OP, and am not finding anything that explains how to do it. The "this one looks good" comment above only works with Git Pushes (of all kinds, to any branch) but not on merging PRs to master. If Jenkins is unable to support this, seems like a serious flaw in Jenkins.

@mwtzzz or anyone who is still trying to find a way to do this. 
I found a way to do this with a help of jenkins pugin([Generic Webhook Trigger Plugin](https://wiki.jenkins.io/display/JENKINS/Generic+Webhook+Trigger+Plugin)). With the help of this plugin, it is possible to parse the contents of the webhook payload sent by the github. The Payload data will have what type of event it is and whether the pull request is merged or not. You can parse this data and send it to your jenkins build job as variables. Depending upon the values you get on the variables you can either skip a build step or execute.

I also wrote a blog post on how to achieve this step by step. 
http://bit-basics.com/post/2019/september/jenkins-job-github-pullrequest/

**Comment by ManvendraFlipkart** [comment]
@jayaganthan The blog post link is not working. Could you please check again?

**Comment by mihaitodor** [comment]
I think this is the right link from @jayaganthan http://bit-basics.com/2019/september/jenkins-job-github-pullrequest/

**Comment by jayaganthan** [comment]
Thanks for correcting the link @ManvendraFlipkart

**Comment by pedrodparkes** [comment]
there's a bit simpler way to reach the same goal:
https://github.com/pedrodparkes/JenkinsMergedPRBuilder

**Comment by sing011** [comment]
@jayaganthan that second link is expired. Can you please update it?

**Comment by jayaganthan** [comment]
@sing011 Sorry for the delayed response. Here is the back for the original link.
https://bit-basics-backup.netlify.com/2019/september/jenkins-job-github-pullrequest/

**Comment by EricoCartmanez** [comment]
> I am having an absolutely miserable time trying to achieve this.
> 
> I do not want to trigger on PR submission, or git push. I DO want to trigger a jenkins build of master AFTER a PR has been merged to master.
> 
> Is there clear straight instructions for this somewhere?

I was looking for the same thing and it was simpler than I thought (except if I am missing something). Merging after PR is like pushing to the master. So you have to look for pushing to the master and trigger the build.

To trigger the build on **PR** I did it with "github pull request builder" plugin.
To trigger the build on **merge** I did it with github plugin (manage jenkins/configure system/ github server section)

Of course the necessary webhook on GitHub 

I hope it helps.

**Comment by devakone** [comment]
> > I am having an absolutely miserable time trying to achieve this.
> > I do not want to trigger on PR submission, or git push. I DO want to trigger a jenkins build of master AFTER a PR has been merged to master.
> > Is there clear straight instructions for this somewhere?
> 
> I was looking for the same thing and it was simpler than I thought (except if I am missing something). Merging after PR is like pushing to the master. So you have to look for pushing to the master and trigger the build.
> 
> To trigger the build on **PR** I did it with "github pull request builder" plugin.
> To trigger the build on **merge** I did it with github plugin (manage jenkins/configure system/ github server section)
> 
> Of course the necessary webhook on GitHub
> 
> I hope it helps.

To add to this, in case it is not clear for everybody else. You will need 2 webhooks in your Github repo.

1. The webhook to trigger your PR builds. This is the webhook for the GHPRB plugin
2. Another webhook just set for push events that uses the Github Integration plugin in Jenkins. This is the webhook that will trigger your builds on push to master.

**Comment by EricoCartmanez** [comment]
Yes, correct.

- Webhook for Github pull request builder looks like this: http://myhost:8080/ghprbhook/

- Webhook for Github plugin (push request/merge) looks like this: http://myhost:8080/github-webhook/

**Comment by Mrinali05** [comment]
Hi, 
Please can anyone help me understand which event to choose when building ' http://myhost:8080/ghprbhook/ ' web-hook
Moreover, what do we need to do at  Jenkins end please tell me.

**Comment by omishagupta** [comment]
Tried looking everywhere, then figured out this solution myself

I'm assuming you've already configured webhook for jenkins, hence skipping that. The idea is to capture merge status and only trigger build if its true.

I'm using generic webhook trigger on jenkins and optional filters to achieve this.

This variable returns true if the build was merged (The same jsonpath will work for your job too).
![image](https://user-images.githubusercontent.com/25386170/124581213-85f31000-de6e-11eb-8c7e-b282583cdccb.png)

And the triggering the build only if this variable is true.
![image](https://user-images.githubusercontent.com/25386170/124581143-75db3080-de6e-11eb-94d3-39f904d4c8c3.png)
