### ISSUE TITLE
project url re-written with incorrect url

### ISSUE THREAD

**Issue by mthhs** [jenkinsci/ghprb-plugin#654]
Whenever trying to set a project url to be git@github.com:user/project the ghprb plugin always rewrites the url as git@github.com:user/project.git/ which breaks the github server config in ghprb.  

This is a duplicate of #539 which seems to have been closed without resolution.

**Comment by bjoernhaeuser** [comment]
Can you add a screenshot of your settings? Or the build.xml?

**Comment by xwartz** [comment]
Cant't use SSH ? 
https://github.com/jenkinsci/ghprb-plugin/blob/19ac57913bcb08c99aada4f31fbe50cfaa6a8079/src/main/java/org/jenkinsci/plugins/ghprb/Ghprb.java#L62

**Comment by xwartz** [comment]
@mthhs  resolve by using https

**Comment by mthhs** [comment]
Thank you @xwartz

The documentation should probably be updated, as it states:


`When creating a job, specify that is connects to git. Under "Github project", put in: git@github.com:Person/Project.git Under "Source Code Management" select Git, and put in git@github.com:Person/Project.git
`

**Comment by bjoernhaeuser** [comment]
@mthhs would be great if you can provide the PR for this. :)
