### ISSUE TITLE
Remove "Build comment file:" from the final comment content

### ISSUE THREAD

**Issue by jkandasa** [jenkinsci/ghprb-plugin#655]
When adding build comment file. Java code adding additional string as follows,

```
msg.append("Build comment file: \n--------------\n");
msg.append(content);
msg.append("\n--------------\n");
```

These extra lines break 100% customizations. Source code: https://github.com/jenkinsci/ghprb-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ghprb/extensions/comments/GhprbCommentFile.java#L63~L65

I would like to remove these extra lines. So that user can 100% space.
If you think this is ok to fix, It is my pleasure to send PR.

**Comment by tomqwu** [comment]
added PR #659 for this, I also found this comment is unuseful and sort of spamming the comment section.

**Comment by jrudolph** [comment]
It seems #659 was merged, so I guess this one could be closed as fixed.

**Comment by bjoernhaeuser** [comment]
I will close this.
