### ISSUE TITLE
how to restrict the jenkins  not to trigger the job for pull request (build trigger is -webhook)

### ISSUE THREAD

**Issue by forpix** [jenkinsci/ghprb-plugin#666]
In Jenkins I have a job which is configured to trigger on web-hook with GitHub, In GitHub I have 2 branches one is master and other is working branch. when I committed on master Jenkins trigger the job which is perfectly all right. But when I tried to pull request to working branch from master for the committed changes again a new build getting triggering which is completely annoying.
so is there any logic to stop the triggering the job for only pull-request

**Comment by saikirankv** [comment]
deselect this `Build every pull request automatically without asking (Dangerous!).` under advanced section.

**Comment by bjoernhaeuser** [comment]
@forpix not sure what you really mean. You created two PRs, both were built. Jenkins does not care about "things are already merged". 

Two options:

* only trigger builds for PRs manually (you have to set the triggers accordingly)
* only automatically trigger builds for a set of valid target branches

**Comment by bjoernhaeuser** [comment]
Will close this ticket in 7 to 14 days if we do not get a response :)

**Comment by amirmisgav** [comment]
A source branch whitelist is needed. There are cases only a specific feature is needed to be executed upon a pull request event.

**Comment by ChaiBapchya** [comment]
> * only trigger builds for PRs manually (you have to set the triggers accordingly)

Can you please point to how to do that?

**Comment by radhaprathyusha5** [comment]
> deselect this `Build every pull request automatically without asking (Dangerous!).` under advanced section.

But where we can get this option exactly.Actually I want to try this for my multibranch pipeline.I can not see this option for multibranch pipeline

**Comment by radhaprathyusha5** [comment]
> deselect this `Build every pull request automatically without asking (Dangerous!).` under advanced section.

Where we can get this option exactly. I need to try this for my multibranch pipeline.I can not get this option.pls help me with this

**Comment by radhaprathyusha5** [comment]
Where I can get this option for multibranch pipeline.How can I disregard the pull request from triggering the multibranch pipeline
