### ISSUE TITLE
Replay in pr-builder pipeline doesn't update GitHub PR status

### ISSUE THREAD

**Issue by charan28** [jenkinsci/ghprb-plugin#674]
We currently have a jenkins pipeline job that is triggered by a pull request builder.

The job works fine on the initial run which is triggered by PR builder - if the job passes the GitHub PR status is marked as passed, if it fails the PR status is marked as Failed.

But let's say there was something wrong with a run (related to the environment), and we replay the job in Jenkins. The job passes, but the GitHub PR status isn't updated.

We've used non-pipeline PR builder for this job before, and retries in jenkins would update the PR status.

Is it possible for a retry of a Jenkins Pipeline PR builder job to update the PR status in GitHub?

**Comment by bjoernhaeuser** [comment]
Yes it is, you need to setup all env variables for the job though. Also you need to have `keepUndefinedParameters` enabled to make this work.

**Comment by shirelvaiman** [comment]
@bjoernhaeuser I know this is closed, but we're experiencing the same issue.
What do you mean by "setup all env variables for the job"? 
If I enable `keepUndefinedParameters` and then "replay" the job, will it be enough?

**Comment by amleszk** [comment]
@bjoernhaeuser @shirelvaiman did you solve this issue? setting Jenkins option `keepUndefinedParameters` does not fix the problem.
i.e on startup this java option is supplied `-Dhudson.model.ParametersAction.keepUndefinedParameters=true` 

When restarting a stage the status against a pull request is never updated
Is there any further documentation to help out? Thanks
