### ISSUE TITLE
Only build if files matching regex pattern are triggered

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/ghprb-plugin#676]
It would be nice if there was a way to specify a list of regex file patterns which will cause the job to run. This allows us to automatically skip jobs that care about code for example if only files in the docs directory is updated or vice versa.

**Comment by bjoernhaeuser** [comment]
You can set the black and whitelisted regions accordingly :)

**Comment by zxiiro** [comment]
Thanks, missed that config.
