### ISSUE TITLE
Phrase triggering should not be filtered based on include/exclude regions

### ISSUE THREAD

**Issue by swegner** [jenkinsci/ghprb-plugin#678]
Our Jenkins setup uses includedRegions to filter down the set of jobs per-path, and phrase-triggering to explicitly request additional job runs. Unfortunately, it seems that include/exclude region filtering is applied even on phrase-triggering.

To be clear, here's our setup for repro'ing:

1. Create a Jenkins job with the following configuration:
  - Phrase triggering `run my jenkins job`
  - Included regions set to `pathA/.*`
1. Submit a PR which contains only changes on `pathB/`. As expected, the Jenkins job does not run.
1. Add a comment to the PR `run my jenkins job`.

I would expect phrase triggering to work even if paths are filtered; but it doesn't.

It appears the logic that would need to be changed is [here](https://github.com/jenkinsci/ghprb-plugin/blob/c943b3038b98f73b183b527d6ae3da7d58667e6e/src/main/java/org/jenkinsci/plugins/ghprb/GhprbPullRequest.java#L532). The conditional should be updated to only skip if `triggered` was false.

**Comment by swegner** [comment]
Let me know what you think. It seems like a simple enough change that I could work on a fix.

**Comment by swegner** [comment]
FYI, our planned work-around is to make copies of our job for each trigger type (cron, push, comment); that way we avoid interaction between the push and phrase triggering.

I'm still interested in seeing this get resolved, and I believe the patch in #680 is sufficient. @bjoernhaeuser any thoughts?

**Comment by bjoernhaeuser** [comment]
Hi!

Sorry for the rater late answer. I am not 100% with you that a comment to trigger the build should ignore watched paths. In the end these path are more a blocklist / allowlist and I cannot follow the reasoning for "overriding" the setting based on the build trigger type. 

In the end you are pointing to a weakness in the current plugin design: There should be more than one trigger configuration per job. Having this it would be rather easy to say "comment without allowlisted folders" and "normal operation with allowlisted".

To overcome this we also have several jobs per project with different trigger configurations.

**Comment by swegner** [comment]
Yes, it seems useful to be able to specify how multiple trigger configurations interact (AND vs OR). And since OR can be achieved by creating separate jobs, I can understand maintaining the AND behavior within a single job.

> I cannot follow the reasoning for "overriding" the setting based on the build trigger type.

Here are a couple scenarios where it is useful to manually trigger a set of tests on a PR which aren't automatically run due to include/exclude path:

1. If the include path configuration is imperfect and doesn't fully encapsulate the set of Jenkins job inputs. For example, we have a repository of java code and a `website/` directory for generating the website. The Jenkins job for generating the website runs only on changes to `website/`, even though it actually depends on the java source directory for generated Javadocs. We don't care about validating the website every time a Java file changes. Though in some cases we do, so we would manually trigger the website job via comment.

1. To prove that unrelated flaky tests are not broken. Some repositories have a "no-commit" policy if the CI tests are red. Non-deterministic flaky tests can thus block merging a PR if they randomly fail on the latest scheduled run. In these cases, it's useful to force the tests to run on your PR to prove they are green and it is safe to merge, even if the tests are unrelated to your changes.
