### ISSUE TITLE
Build is failing with no error

### ISSUE THREAD

**Issue by Shravandoe** [jenkinsci/ghprb-plugin#679]
PFB the console output: 

Started by user snagareddi
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/workspace/Squiz-preproduction-new-repo/All Squiz Sites PreProd Desktop Visual Tests
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://shravannagareddi@bitbucket.org/dec-ce/doe-automation.git # timeout=10
Fetching upstream changes from https://shravannagareddi@bitbucket.org/dec-ce/doe-automation.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://shravannagareddi@bitbucket.org/dec-ce/doe-automation.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/GXF-2469-update-webdriver-in-pom-file^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/GXF-2469-update-webdriver-in-pom-file^{commit} # timeout=10
Checking out Revision a3793b0d85f2b54608226dbb00581beb43177dd8 (refs/remotes/origin/GXF-2469-update-webdriver-in-pom-file)
Commit message: "commiting new changes"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a3793b0d85f2b54608226dbb00581beb43177dd8
First time build. Skipping changelog.
Triggering Squiz-preproduction-new-repo » All Squiz Sites PreProd Desktop Visual Tests » Windows_2008chrome60
Squiz-preproduction-new-repo » All Squiz Sites PreProd Desktop Visual Tests » Windows_2008chrome60 completed with result FAILURE
Finished: FAILURE

**Comment by bjoernhaeuser** [comment]
Hi @Shravandoe 

I do not believe this is a problem in the plugin, but rather one in your system itself :)
