### ISSUE TITLE
Using GHE with Pipeline DSL

### ISSUE THREAD

**Issue by zlesnr** [jenkinsci/ghprb-plugin#681]
I'm looking for a way to use GHE using the build pipeline DSL.  It looks like I need to modify the credentials, but I'd appreciate a way that we could use environment variables or some other way to point this plugin at a private Github Enterprise instance.

Any guidance here would be appreciated.

**Comment by zlesnr** [comment]
Alternatively, how would one change the configuration of the plugin from groovy?

**Comment by bat9r** [comment]
+1
