### ISSUE TITLE
Changing title of PR triggers build

### ISSUE THREAD

**Issue by kmaehashi** [jenkinsci/ghprb-plugin#689]
It seems that changing the title of PRs triggers the build.
Is it an expected behavior?

**Comment by saikirankv** [comment]
Changing the title won't trigger the build. 
This happens only in one case, raise a PR with **[DO not merge] PR title** and then remove **[DO not merge]** then tests will start triggering.

**Comment by bjoernhaeuser** [comment]
See the last comment.
