### ISSUE TITLE
Trigger build for PR opened in any repo from one organization 

### ISSUE THREAD

**Issue by marianpostole** [jenkinsci/ghprb-plugin#700]
Hello,

The goal is to trigger the job when a new PR is opened no matter which repo 
 (from the same organization) sent the event. So let's say I have https://github-...../org/repo1 in Configuration of the job and the PR is created in https://github-...../org/repo2.

The question is if anyone knows the name of the variable for Project url job's parameter, as should be found in /src/main/java/org/jenkinsci/plugins/ghprb/...java files ?

Thank you.

**Comment by bjoernhaeuser** [comment]
Hey, this seams out of scope of this plugin, maybe the multi-branch-plugin will help you.
