### ISSUE TITLE
Global configuration should be configuration-as-code compatible

### ISSUE THREAD

**Issue by jcrben** [jenkinsci/ghprb-plugin#701]
As I noted over at https://github.com/jenkinsci/configuration-as-code-plugin/issues/418 this plugin isn't really compatible with the yaml-based global configuration approach.

I started https://github.com/jcrben/ghprb/tree/config-as-code-2 by copying https://github.com/jenkinsci/github-plugin/blob/497f43251e3bfc130f125f75e45f73e06894361d/src/main/java/org/jenkinsci/plugins/github/config/GitHubPluginConfig.java and got the point where at least something showed up in the documentation, but I'm not in my element here so any help would be appreciated.

![image](https://user-images.githubusercontent.com/5614134/43997110-1593414c-9d88-11e8-919f-9f5e7cd2478c.png)

I'm using https://gitlab.com/jcrben-not-mine/jenkins/casc-docker to build jenkins

**Comment by bjoernhaeuser** [comment]
Could you base your changes on this repo? Otherwise its impossible to review.

**Comment by jcrben** [comment]
The branch was based upon this repo, but the github fork was different so I can see how that would be confusing. Diff is https://github.com/jenkinsci/ghprb-plugin/compare/master...jcrben:config-as-code-2?expand=1 - I don't know much about jenkins.

The idea I had in mind was to have an entirely separate global config, and then load that into the place where the incompatible global config is loaded. That way, it can fall back to the old default if the new approach is empty.

But I'm pretty new to jenkins coding and I'm not really sure how to do that. 

![image](https://user-images.githubusercontent.com/5614134/45062441-c64a3800-b05d-11e8-81d3-9798dc47f056.png)

**Comment by bjoernhaeuser** [comment]
Sorry, never used configuration as code for jenkins, therefore not really able to help.

**Comment by jcrben** [comment]
Looks like there's work being done on this at https://github.com/jenkinsci/ghprb-plugin/pull/731

**Comment by jcrben** [comment]
looks like the PR referenced above was merged
