### ISSUE TITLE
fetching labels associated with a PR

### ISSUE THREAD

**Issue by abhiboost** [jenkinsci/ghprb-plugin#702]
is it possible to fetch the labels that have been assigned to a PR using this plugin? I’m not talking about whitelisting or blacklisting certain labels but to actually fetch them so that i can run my own script on it.

**Comment by saikirankv** [comment]
its not possible, you should use git command calls to do this

**Comment by bjoernhaeuser** [comment]
This seams out of scope for this plugin, therefore closing.
