### ISSUE TITLE
PR comments contains special formatting character 

### ISSUE THREAD

**Issue by Rizbe** [jenkinsci/ghprb-plugin#712]
Using Jenkins(2.121.3) to add Terraform plan output to each Github PR, Using ghprb version 1.42.0. GHPRB uses a log file to update the PR. Below is an example of what the PR comment looks like:

```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  �[32m+�[0m create
�[0m
Terraform will perform the following actions:

�[32m  �[32m+�[0m �[32mgithub_repository_collaborator
```

**Comment by bjoernhaeuser** [comment]
@Rizbe you need to disable terraform color codes with `-no-color` when executing terraform.
