### ISSUE TITLE
Sending status after the build to Github takes much longer

### ISSUE THREAD

**Issue by guruvamsichintala** [jenkinsci/ghprb-plugin#727]
In the pull request builds, sending status after the build, to Github takes much longer now. Sometimes it even takes 10 minutes waiting for the status to be reported.

**Comment by chrislovecnm** [comment]
We are noticing this as well.  Any ideas on the change?

**Comment by bjoernhaeuser** [comment]
This could only happen if either the github API are slow or the token/user is currently rate limited and the plugin is waiting for the rate limit to recover. Whats your case?

**Comment by chrislovecnm** [comment]
@bjoernhaeuser we have not seen this for awhile.  Feel free to close

**Comment by bjoernhaeuser** [comment]
Thank you!
