### ISSUE TITLE
How to trigger the build jenkins if master branch has changed?

### ISSUE THREAD

**Issue by xitrumm** [jenkinsci/ghprb-plugin#737]
I have a freestyle job with Gitea scm. I setup webhook on Gitea but when others branch change, jenkins will rebuilds once. How can I trigger the build on pushed to master branch only and pushed to others branch do nothing?

**Comment by andrew-garland** [comment]
Is this the same as https://github.com/jenkinsci/ghprb-plugin/issues/658

**Comment by bjoernhaeuser** [comment]
Yet it is! Thanks.
