### ISSUE TITLE
ghprbActualCommitAuthorEmail get the wrong email address

### ISSUE THREAD

**Issue by myhour** [jenkinsci/ghprb-plugin#742]
I created a PR and Jenkins build is triggered, but the ghprbActualCommitAuthorEmail can't get the correct email I set in github. the suffix is changed to an IP, why?  I need the email address to send a email to the author the build failed. 

ghprbActualCommit:  9932e2b7c665797b1af3f8fe894ace5197e21d51
ghprbActualCommitAuthor:  user
ghprbActualCommitAuthorEmail:  user@9.83.24.206

**Comment by myhour** [comment]
@David Tanner
Hi David Tanner, can you help to check what's the problem of the env-var : ghprbActualCommitAuthorEmail

**Comment by bjoernhaeuser** [comment]
@myhour this is likely to be your git configuration, check the commits metadata.
