### ISSUE TITLE
Slow trigger of builds

### ISSUE THREAD

**Issue by levimatheri** [jenkinsci/ghprb-plugin#744]
The poll works fine but when I do a PR on a project, the build takes a long time to get triggered or even sometimes the build never happens. I have tried downgrading to 1.36.2 from 1.42.0 with no success. I manually have to restart the Jenkins service to trigger builds which is not what we want.

**Comment by bjoernhaeuser** [comment]
Polling is usually slow, if you wanna have fast responses you need to use webhooks.
