### ISSUE TITLE
Unable to connect to GitHub API: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: 

### ISSUE THREAD

**Issue by dgedeon** [jenkinsci/ghprb-plugin#755]
Im having credential issues causing the error message listed in the title. Our organization uses the GitHub Enterprise Server and using curl scripts with the access token provided in GitHub works just fine. 
<img width="1155" alt="Screen Shot 2019-09-05 at 1 35 05 PM" src="https://user-images.githubusercontent.com/31417124/64370775-c10f2880-cfe4-11e9-91bd-b51bdf1a6101.png">

**Comment by dgedeon** [comment]
More context:

Github Plugin version:                                                1.29.4
Github Pull Request Builder version:                         1.42.0

Our organization uses a separate platform for authentication so using the username/password credential field does not work.

**Comment by dgedeon** [comment]
Was able to fix this issue by using the skip certificate check plugin. This may entail security risks but it worked for me.

**Comment by liudeing** [comment]
I use  skip certificate check plugin on github enterprise resolve the same problem.thank you!
