### ISSUE TITLE
Allow customisation of 'Details' destination in Github status

### ISSUE THREAD

**Issue by Igorshp** [jenkinsci/ghprb-plugin#79]
Currently the plugin updates the PullRequest status with link to the specific job (the 'Details' button on the right).
![githubstatus]
(http://i.imgur.com/oMP15FG.png)
Most of the time, when a job fails, the user will want to go to console to find out the reason and with current setup that requires 2 clicks, 2 page loads.

I believe the workflow can be simplified by allowing the endpoint destination to be changed in global config depending on job result status.

for example:
job created - link to job
job succeeded - link to job
job failed - link to console

**Comment by KostyaSha** [comment]
Good configured jobs and builds provides all needed info (failed tests, static analysing, etc) on the build page. Navigation to console is your  single use case.

**Comment by Igorshp** [comment]
@KostyaSha any chance you could link to some examples of configurations/plugins/setups/best_practices on setting up the buildpage

**Comment by KostyaSha** [comment]
You can wrote jenkins users maillist. 
Also changing link between steps may confuse users in jenkins navigation.

**Comment by Memphiz** [comment]
Consider matrix jobs or multijobs ... there is no single console output to jump to. Please don't change current behavior of this link. Jumping to the buildpage is the right thing to do.
