### ISSUE TITLE
Release 1.42.2 request

### ISSUE THREAD

**Issue by sp-ricard-valverde** [jenkinsci/ghprb-plugin#807]
Hello,

Would it be possible to start the release process for 1.42.2 version ?

https://github.com/jenkinsci/ghprb-plugin/compare/ghprb-1.42.1..master

There's just the changes regarding JCasC configuration, but it's a game-changer for us because it allows to fully configure a Jenkins installation without any further manual configuration.

Thanks

**Comment by fatmcgav** [comment]
:+1: from us aswell...

**Comment by kutzi** [comment]
This has been done, hasn't it?
So can someone close the issue as it's confusing to still see it open?

**Comment by sp-ricard-valverde** [comment]
> This has been done, hasn't it? So can someone close the issue as it's confusing to still see it open?

Yes it is, thank you
