### ISSUE TITLE
Do not automatically merge PRs/branches with master

### ISSUE THREAD

**Issue by kowalcj0** [jenkinsci/ghprb-plugin#84]
Something's going on with wiki.jenkins-ci.org and I can't add a comment there, so I was forced to post it here.

So my question is: 
* how can I configure ghprb so that it doesn't merge PRs or branches with master?

Basically what we need is to have 2 jobs for the same repo:
* 1st one, that will checkout only the PR/branch code without merging it with master
* 2nd that will merge PR/branch (if possible) with master 

Here's an excerpt from the current build log. 
I've highlighted things that bother me and is not what I need.

> GitHub pull request #15 of commit 4a2fce874f2d8e20c46423ffdc0ea21beb055953, no merge conflicts.
> Setting status of 4a2fce874f2d8e20c46423ffdc0ea21beb055953 to PENDING with url http://xxxxx:8080/job/xxxxxxxxxx/20/ and message: Build started, ***sha1 is merged***
> [EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/workspace/xxxxxxxxx
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.comxxxx/xxxxxx.git # timeout=10
Fetching upstream changes from git@github.com:xxxx/xxxxxxxx.git
 > git --version # timeout=10
using GIT_SSH to set credentials Used for Github integration
 > git -c core.askpass=true fetch --tags --progress git@github.com:xxxxxxxxxxxxx.git +refs/heads/*:refs/remotes/origin/*
 > ***git rev-parse refs/remotes/origin/pr/15/merge^{commit}*** # timeout=10
 > ***git rev-parse refs/remotes/origin/origin/pr/15/merge^{commit}*** # timeout=10
***Checking out Revision 4fd5b9af8a7d582cc02c0b8e6c43a197be1de452 (refs/remotes/origin/pr/15/merge)***
 > git config core.sparsecheckout # timeout=10
 > ***git checkout -f 4fd5b9af8a7d582cc02c0b8e6c43a197be1de452***

**Comment by DavidTanner** [comment]
The merging is done by Github, and not something you can stop.  In the current trigger if you use ${ghprbActualCommit} instead of ${sha1} then you will always get the original commit.
