### ISSUE TITLE
Is this plugin is not maintained anymore? if so, is there any alternative plugin for it ?

### ISSUE THREAD

**Issue by ofiry-tm** [jenkinsci/ghprb-plugin#857]
### Jenkins and plugins versions report

Is this plugin is not maintained anymore? if so, is there any alternative plugin for it ?

### What Operating System are you using (both controller, and any agents involved in the problem)?

Is this plugin is not maintained anymore? if so, is there any alternative plugin for it ?

### Reproduction steps

install the plugin

### Expected Results

that it will be maintained and release new versions at least once a year

### Actual Results

its not maintained for 2 years

**Comment by atsalolikhin-spokeo** [comment]
https://plugins.jenkins.io/ghprb/ says:

You should probably migrate to [GitHub Branch Source Plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin)
