### ISSUE TITLE
Comments on the PR trigger jenkins but jenkins does not trigger github

### ISSUE THREAD

**Issue by Nek-** [jenkinsci/ghprb-plugin#90]
Hello,

I notice a weird behavior when you trigger builds manually. (in my project, we don't want jenkins build automatically every PR because it takes a lot of time)

When you create a pull-request on the github, then you add the comment to trigger jenkins, everything is ok. The build start and jenkins tell github about the current status of the build. As you can see on this screenshot: 

![screen_jenkins_success](https://cloud.githubusercontent.com/assets/972456/7814720/3dbd2e78-03c4-11e5-9fce-8878534ed9e5.png)

After added a commit, then when you try to start again a build, the build is started by jenkins but github does not receive information about the build. Checkout the following screenshot:

![screen_jenkins_fail](https://cloud.githubusercontent.com/assets/972456/7814765/8ba6ef98-03c4-11e5-85fd-c954ed5c4dba.png)

I have no idea where comes this bug, or how to fix it. But i tried many configurations of the plugin and nothing to do, the problem is still here.

Don't hesitate to ask anything if i'm not clear enough.

**Comment by DavidTanner** [comment]
Please add a logger for org.jenkinsci.plugins.ghprb at FINEST, then maybe we can see what it going on .

**Comment by ashishmusale** [comment]
I have a similar issue and this is what I see in the logs

```
Jul 13, 2015 1:03:01 PM SEVERE org.jenkinsci.plugins.ghprb.GhprbPullRequest checkMergeable
Couldn't obtain mergeable status.
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.StringReader@380a0b05; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:1298)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1199)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:830)
	at org.kohsuke.github.Requester.parse(Requester.java:460)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	at org.kohsuke.github.Requester.to(Requester.java:198)
	at org.kohsuke.github.GHPullRequest.populate(GHPullRequest.java:196)
	at org.kohsuke.github.GHPullRequest.getMergeable(GHPullRequest.java:169)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.checkMergeable(GhprbPullReque
```

any idea what this might be?

**Comment by DavidTanner** [comment]
Looks like an issue in the github lib.  I have never seen that before, maybe @KostyaSha could shed some light on it?

**Comment by mrtuborg** [comment]
Is this issue solved? I have similar problem and not sure that this plugin is still in development.

**Comment by bjoernhaeuser** [comment]
The mentioned issue is not happening for us. 

Please reopen if the issue still persists and add as much logging as you can. I just going through the old issues here.

**Comment by PravinaBhatt** [comment]
I am facing the same issue, if I try to test the build through "test this please" comment, is communicates with Jenkins server but yet Jenkins build is not triggered. It displays http response code 401 error even I have admin authority.
