### ISSUE TITLE
does not build on new commits

### ISSUE THREAD

**Issue by funkaster** [jenkinsci/ghprb-plugin#91]
After a while, the plugin stopped looking at new commits and you can only trigger a new build with the `retest this please` phrase. No idea where to start looking: I checked github token, config, etc. and it looks ok. Commit status is also updated properly, the only thing not working is that the build is not triggered when a new commit is added to the pull request.

**Comment by DavidTanner** [comment]
Do you have the "Build All" setting checked?

**Comment by funkaster** [comment]
I don't see that setting. Is in the pull request builder config? I have tried this:

* build every pull request
* add everyone in the PR as admins
* add org as a whitelist
* move from hooks to polling

And nothing. Is there a way to get logs? Webhooks from github look ok (when you look at the request response), and as I said before, comments are triggering the build, just not the commits :disappointed:

**Comment by funkaster** [comment]
It's working again for our pull request, I closed & reopen the pull request and it's working again. We did rebase and rewrite parts of history for that PR a few times, I'm not sure how this plugin is keeping track of changes in the branch, but that could've affected it.

**Comment by DavidTanner** [comment]
Next time it happens, add a Jenkins log for org.jenkinsci.plugins.ghprb at the FINEST level.
